"""
Baked-in Top Beauty Brands reference data, sourced from Ulta.com.

Ranks 1-10 are the best-selling brands on Ulta.com in 2025 by share of online
sales (WWD / Navigo Marketing; excludes in-store and Ulta app sales), with
category, sales share and verified social/Wikipedia links. Ranks 11-500 are
drawn from Ulta's full brand directory (ulta.com/brand/all) in alphabetical
order; each row links to that brand's official Ulta page. The directory lists
~992 brands in total; this snapshot caps at 500. Refresh by re-reading
ulta.com/brand/all.

Source: https://www.ulta.com/brand/all
"""

BEAUTY_EDITION = "Ulta.com brands (top 10 by 2025 online sales share)"
BEAUTY_SOURCE_URL = "https://www.ulta.com/brand/all"

TOP_BEAUTY_BRANDS = [
    {"rank": 1, "brand": "Clinique", "category": "Skincare & makeup", "share": "3.3%", "ulta_url": "https://www.ulta.com/brand/clinique", "instagram": "https://www.instagram.com/clinique", "twitter": "https://x.com/clinique", "wikipedia": "https://en.wikipedia.org/wiki/Clinique"},
    {"rank": 2, "brand": "La Roche-Posay", "category": "Skincare (dermatological)", "share": "2.5%", "ulta_url": "https://www.ulta.com/brand/la-roche-posay", "instagram": "https://www.instagram.com/larocheposayusa", "twitter": "https://x.com/LaRochePosayUSA", "wikipedia": "https://en.wikipedia.org/wiki/La_Roche-Posay"},
    {"rank": 3, "brand": "Ulta Beauty Collection", "category": "Retailer own-brand", "share": "2.4%", "ulta_url": "https://www.ulta.com/brand/ulta-beauty-collection", "instagram": "https://www.instagram.com/ultabeauty", "twitter": "https://x.com/ultabeauty", "wikipedia": "https://en.wikipedia.org/wiki/Ulta_Beauty"},
    {"rank": 4, "brand": "Redken", "category": "Haircare (professional)", "share": "2.0%", "ulta_url": "https://www.ulta.com/brand/redken", "instagram": "https://www.instagram.com/redken", "twitter": "https://x.com/Redken5thAve", "wikipedia": "https://en.wikipedia.org/wiki/Redken"},
    {"rank": 5, "brand": "Sol de Janeiro", "category": "Body & fragrance", "share": "1.5%", "ulta_url": "https://www.ulta.com/brand/sol-de-janeiro", "instagram": "https://www.instagram.com/soldejaneiro", "twitter": "", "wikipedia": "https://en.wikipedia.org/wiki/Sol_de_Janeiro"},
    {"rank": 6, "brand": "e.l.f. Cosmetics", "category": "Makeup (mass)", "share": "1.4%", "ulta_url": "https://www.ulta.com/brand/elf-cosmetics", "instagram": "https://www.instagram.com/elfcosmetics", "twitter": "https://x.com/elfcosmetics", "wikipedia": "https://en.wikipedia.org/wiki/E.l.f."},
    {"rank": 7, "brand": "Tarte Cosmetics", "category": "Makeup", "share": "1.3%", "ulta_url": "https://www.ulta.com/brand/tarte", "instagram": "https://www.instagram.com/tartecosmetics", "twitter": "https://x.com/tartecosmetics", "wikipedia": ""},
    {"rank": 8, "brand": "OPI", "category": "Nail care", "share": "1.2%", "ulta_url": "https://www.ulta.com/brand/opi", "instagram": "https://www.instagram.com/opi", "twitter": "https://x.com/OPI_PRODUCTS", "wikipedia": "https://en.wikipedia.org/wiki/OPI_Products"},
    {"rank": 9, "brand": "NYX Professional Makeup", "category": "Makeup (mass)", "share": "1.2%", "ulta_url": "https://www.ulta.com/brand/nyx-professional-makeup", "instagram": "https://www.instagram.com/nyxcosmetics", "twitter": "https://x.com/nyxcosmetics", "wikipedia": "https://en.wikipedia.org/wiki/NYX_(company)"},
    {"rank": 10, "brand": "Tree Hut", "category": "Body care", "share": "1.1%", "ulta_url": "https://www.ulta.com/brand/tree-hut", "instagram": "https://www.instagram.com/treehut", "twitter": "", "wikipedia": "https://en.wikipedia.org/wiki/Tree_Hut"},
    {"rank": 11, "brand": "107", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/107", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 12, "brand": "18.21 Man Made", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/1821-man-made", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 13, "brand": "3H Nails", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/3h-nails", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 14, "brand": "7 E Wellness", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/7-e-wellness", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 15, "brand": "8Grow", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/8grow", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 16, "brand": "A313", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/a313", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 17, "brand": "Abature", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/abature", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 18, "brand": "about-face", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/about-face", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 19, "brand": "Acca Kappa", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/acca-kappa", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 20, "brand": "Active Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/active-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 21, "brand": "Admire My Skin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/admire-my-skin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 22, "brand": "af94", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/af94", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 23, "brand": "Afnan", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/afnan", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 24, "brand": "AG Care", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ag-care", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 25, "brand": "AG1", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ag1", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 26, "brand": "Ahava", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ahava", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 27, "brand": "Aippo", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aippo", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 28, "brand": "Algenist", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/algenist", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 29, "brand": "Alleyoop", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/alleyoop", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 30, "brand": "Almost Famous", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/almost-famous", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 31, "brand": "Alpha Skincare", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/alpha-skincare", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 32, "brand": "Alterna", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/alterna", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 33, "brand": "AMAZING COSMETICS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/amazing-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 34, "brand": "Amazing Grass", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/amazing-grass", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 35, "brand": "American Crew", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/american-crew", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 36, "brand": "amika", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/amika", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 37, "brand": "AmLactin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/amlactin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 38, "brand": "Anastasia Beverly Hills", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/anastasia-beverly-hills", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 39, "brand": "Andis", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/andis", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 40, "brand": "Andrew Fitzsimons", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/andrew-fitzsimons", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 41, "brand": "Anthony", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/anthony", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 42, "brand": "ANUA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/anua", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 43, "brand": "Aperire", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aperire", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 44, "brand": "Apieu", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/apieu", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 45, "brand": "APLB", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aplb", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 46, "brand": "Apostle", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/apostle", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 47, "brand": "APOTHEKE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/apotheke", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 48, "brand": "Apothékary", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/apothekary", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 49, "brand": "Aquaphor", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aquaphor", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 50, "brand": "AquaSonic", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aquasonic", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 51, "brand": "ARABIAN CREST DUBAI", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/arabian-crest-dubai", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 52, "brand": "Aramis", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aramis", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 53, "brand": "Aramore", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aramore", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 54, "brand": "Arctic Fox", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/arctic-fox", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 55, "brand": "Ardell", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ardell", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 56, "brand": "Ariana Grande", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ariana-grande", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 57, "brand": "ARMANI", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/armani", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 58, "brand": "ARMRA Colostrum", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/armra-colostrum", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 59, "brand": "arrae", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/arrae", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 60, "brand": "ASCENTION Parfums", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ascention-parfums", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 61, "brand": "ASNA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/asna", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 62, "brand": "Athletic Cosmetic Company", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/athletic-cosmetic-company", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 63, "brand": "ATWATER", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/atwater", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 64, "brand": "Avatara Skin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/avatara-skin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 65, "brand": "Aveeno", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/aveeno", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 66, "brand": "Avène", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/avene", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 67, "brand": "AXIS-Y", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/axis-y", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 68, "brand": "Azzaro", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/azzaro", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 69, "brand": "b.tan", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/btan", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 70, "brand": "Babe Original", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/babe-original", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 71, "brand": "Baby Foot", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/baby-foot", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 72, "brand": "BaBylissPRO", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/babylisspro", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 73, "brand": "Bali Body", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bali-body", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 74, "brand": "Balmain Paris", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/balmain-paris", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 75, "brand": "Banila Co", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/banila-co", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 76, "brand": "Barbasol Shaving", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/barbasol-shaving", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 77, "brand": "Barberino's", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/barberinos", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 78, "brand": "BarberMate", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/barbermate", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 79, "brand": "bareMinerals", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bareminerals", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 80, "brand": "Barrière", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/barriere", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 81, "brand": "Batiste", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/batiste", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 82, "brand": "Baxter of California", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/baxter-of-california", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 83, "brand": "bdy.", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bdy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 84, "brand": "Be Your Own Desire", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/be-your-own-desire", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 85, "brand": "Beachwaver Co.", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beachwaver-co", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 86, "brand": "BEAUND", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beaund", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 87, "brand": "Beautifect", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beautifect", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 88, "brand": "Beauty Core", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beauty-core", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 89, "brand": "Beauty Finds by ULTA Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beauty-finds-by-ulta-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 90, "brand": "BeautyBio", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beautybio", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 91, "brand": "beautyblender", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beautyblender", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 92, "brand": "BeautyStat Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beautystat-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 93, "brand": "Bed Head", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bed-head", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 94, "brand": "Beekman 1802", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beekman-1802", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 95, "brand": "Before Oral Care", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/before-oral-care", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 96, "brand": "being", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/being", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 97, "brand": "Being Frenshe", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/being-frenshe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 98, "brand": "Bejou", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bejou", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 99, "brand": "belif", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/belif", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 100, "brand": "Benefit Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/benefit-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 101, "brand": "BETTER WORLD FRAGRANCE HOUSE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/better-world-fragrance-house", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 102, "brand": "BEVEL", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bevel", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 103, "brand": "Bewants", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bewants", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 104, "brand": "Beyoncé Parfums", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/beyonce-parfums", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 105, "brand": "billie", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/billie", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 106, "brand": "Billie Eilish", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/billie-eilish", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 107, "brand": "Bio Ionic", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bio-ionic", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 108, "brand": "Bio-Oil", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bio-oil", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 109, "brand": "Bioderma", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bioderma", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 110, "brand": "Biolage", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/biolage", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 111, "brand": "Bioré", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/biore", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 112, "brand": "Biosilk", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/biosilk", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 113, "brand": "Bird&Be", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bird-be", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 114, "brand": "BK Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bk-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 115, "brand": "Black Girl Sunscreen", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/black-girl-sunscreen", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 116, "brand": "BLACKWOOD FOR MEN", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blackwood-men", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 117, "brand": "Blinc", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blinc", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 118, "brand": "Blind Barber", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blind-barber", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 119, "brand": "Blissy", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blissy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 120, "brand": "BLK/OPL", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blkopl", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 121, "brand": "BLONDME", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blondme", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 122, "brand": "Bloom", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bloom", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 123, "brand": "Bloomeffects", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bloomeffects", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 124, "brand": "BLOSSOM", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blossom", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 125, "brand": "Blossom Essentials", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blossom-essentials", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 126, "brand": "Blu Atlas", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blu-atlas", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 127, "brand": "Blue Lagoon Skin Science", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blue-lagoon-skin-science", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 128, "brand": "BLUE LIZARD AUSTRALIAN SUNSCREEN", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blue-lizard-australian-sunscreen", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 129, "brand": "BLUME", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blume", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 130, "brand": "Blushly", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/blushly", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 131, "brand": "BOBBI BROWN", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bobbi-brown", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 132, "brand": "Bondi Boost", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bondi-boost", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 133, "brand": "Bondi Sands", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bondi-sands", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 134, "brand": "Bonika Shears", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bonika-shears", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 135, "brand": "Borghese", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/borghese", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 136, "brand": "BREAD BEAUTY SUPPLY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bread-beauty-supply", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 137, "brand": "Bridgerton", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bridgerton", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 138, "brand": "Briogeo", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/briogeo", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 139, "brand": "BRMUD", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/brmud", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 140, "brand": "Bubble", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bubble", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 141, "brand": "Bubble T", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bubble-t", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 142, "brand": "Bumble and bumble", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bumble-bumble", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 143, "brand": "Burberry", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/burberry", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 144, "brand": "Bushbalm", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/bushbalm", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 145, "brand": "Buttah Skin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/buttah-skin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 146, "brand": "Buxom", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/buxom", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 147, "brand": "By the Beach", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/by-beach", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 148, "brand": "BYOMA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/byoma", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 149, "brand": "BYROE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/byroe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 150, "brand": "Caboodles", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/caboodles", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 151, "brand": "CAKES Body", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cakes-body", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 152, "brand": "Caldera + Lab", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/caldera-lab", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 153, "brand": "Caliber Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/caliber-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 154, "brand": "California Naturals", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/california-naturals", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 155, "brand": "Calvin Klein", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/calvin-klein", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 156, "brand": "Camille Rose", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/camille-rose", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 157, "brand": "Candier", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/candier", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 158, "brand": "Candorlov", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/candorlov", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 159, "brand": "Capelli New York", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/capelli-new-york", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 160, "brand": "Captain Fawcett", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/captain-fawcett", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 161, "brand": "Carbon Theory.", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/carbon-theory", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 162, "brand": "Carol's Daughter", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/carols-daughter", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 163, "brand": "Carolina Herrera", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/carolina-herrera", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 164, "brand": "Carroten", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/carroten", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 165, "brand": "Caswell-Massey", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/caswell-massey", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 166, "brand": "Cayla Gray", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cayla-gray", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 167, "brand": "celimax", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/celimax", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 168, "brand": "Cell Fusion C", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cell-fusion-c", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 169, "brand": "Centellian24", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/centellian24", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 170, "brand": "CeraVe", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cerave", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 171, "brand": "Cetaphil", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cetaphil", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 172, "brand": "CHANEL", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/chanel", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 173, "brand": "Charlotte Tilbury", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/charlotte-tilbury", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 174, "brand": "Chasin' Rabbits", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/chasin-rabbits", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 175, "brand": "CHI", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/chi", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 176, "brand": "China Glaze", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/china-glaze", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 177, "brand": "Chloé", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/chloe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 178, "brand": "Christophe Robin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/christophe-robin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 179, "brand": "ChungMijung", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/chungmijung", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 180, "brand": "Cinema Secrets", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cinema-secrets", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 181, "brand": "Clairol", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/clairol", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 182, "brand": "Clarins", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/clarins", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 183, "brand": "CLE Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cle-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 184, "brand": "Clean", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/clean", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 185, "brand": "Clean Skin Club", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/clean-skin-club", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 186, "brand": "Clean Your Dirty Face", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/clean-your-dirty-face", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 187, "brand": "ClearDea.", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cleardea", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 188, "brand": "Cleverman", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cleverman", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 189, "brand": "clöud café", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cloud-cafe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 190, "brand": "CND", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cnd", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 191, "brand": "CNP Laboratory", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cnp-laboratory", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 192, "brand": "Coach", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/coach", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 193, "brand": "Coco & Eve", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/coco-eve", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 194, "brand": "cocokind", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cocokind", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 195, "brand": "CODEAGE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/codeage", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 196, "brand": "Codex Labs", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/codex-labs", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 197, "brand": "Color Wow", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/color-wow", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 198, "brand": "ColourPop", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/colourpop", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 199, "brand": "Conair", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/conair", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 200, "brand": "Conair Accessories", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/conair-accessories", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 201, "brand": "Contently", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/contently", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 202, "brand": "COOLA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/coola", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 203, "brand": "CORPUS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/corpus", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 204, "brand": "Cosnori", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cosnori", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 205, "brand": "COSRX", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cosrx", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 206, "brand": "CoverGirl", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/covergirl", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 207, "brand": "Cozy Clip", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cozy-clip", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 208, "brand": "Crave", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/crave", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 209, "brand": "Cricket", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cricket", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 210, "brand": "CROC", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/croc", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 211, "brand": "CRVFT", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/crvft", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 212, "brand": "Cure Hydration", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cure-hydration", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 213, "brand": "CurlMix", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/curlmix", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 214, "brand": "Curlsmith", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/curlsmith", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 215, "brand": "Cutting Edge", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cutting-edge", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 216, "brand": "Cymbiotika", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cymbiotika", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 217, "brand": "CÉCRED", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/cecred", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 218, "brand": "d'Alba Piedmont", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dalba-piedmont", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 219, "brand": "Daeng Gi Meo Ri", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/daeng-gi-meo-ri", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 220, "brand": "Daily Habits", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/daily-habits", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 221, "brand": "DAISE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/daise", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 222, "brand": "Dashing Diva", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dashing-diva", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 223, "brand": "dearcloud", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dearcloud", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 224, "brand": "Decorté", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/decorte", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 225, "brand": "Dehiya Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dehiya-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 226, "brand": "Denman", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/denman", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 227, "brand": "DERMA E", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/derma-e", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 228, "brand": "Dermablend", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dermablend", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 229, "brand": "DERMAFLASH", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dermaflash", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 230, "brand": "Dermalogica", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dermalogica", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 231, "brand": "Dermasuri", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dermasuri", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 232, "brand": "Dermelect", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dermelect", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 233, "brand": "Design Essentials", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/design-essentials", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 234, "brand": "DevaCurl", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/devacurl", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 235, "brand": "DHC", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dhc", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 236, "brand": "Diamond Drunk", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/diamond-drunk", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 237, "brand": "Diane", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/diane", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 238, "brand": "DIBS Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dibs-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 239, "brand": "Differin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/differin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 240, "brand": "DIGI Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/digi-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 241, "brand": "DIME", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dime", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 242, "brand": "Dionis", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dionis", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 243, "brand": "Dior", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dior", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 244, "brand": "Divi", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/divi", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 245, "brand": "DKNY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dkny", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 246, "brand": "Dolce Glow", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dolce-glow", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 247, "brand": "Dolce&Gabbana", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dolce-gabbana", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 248, "brand": "Doll 10", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/doll-10", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 249, "brand": "Donna Karan", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/donna-karan", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 250, "brand": "DONNA'S RECIPE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/donnas-recipe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 251, "brand": "Doré", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dore", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 252, "brand": "dpHUE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dphue", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 253, "brand": "Dr Rossi, Derm MD", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-rossi-derm-md", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 254, "brand": "Dr Teal's", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-teals", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 255, "brand": "Dr. Althea", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-althea", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 256, "brand": "Dr. Brandt", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-brandt", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 257, "brand": "Dr. Melaxin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-melaxin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 258, "brand": "Dr. PAWPAW", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-pawpaw", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 259, "brand": "Dr. Reju-All", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-reju-all", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 260, "brand": "Dr. Squatch", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dr-squatch", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 261, "brand": "DRMTLGY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/drmtlgy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 262, "brand": "Drowsy", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/drowsy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 263, "brand": "Drunk Elephant", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/drunk-elephant", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 264, "brand": "Drybar", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/drybar", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 265, "brand": "Dryope", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dryope", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 266, "brand": "DS Laboratories", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ds-laboratories", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 267, "brand": "DUFT & DOFT", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/duft-doft", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 268, "brand": "Duke Cannon Supply Co", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/duke-cannon-supply-co", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 269, "brand": "DUNE SUNCARE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dune-suncare", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 270, "brand": "Duo Toothpaste", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/duo-toothpaste", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 271, "brand": "Dyson", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dyson", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 272, "brand": "Dēp Slēpwear", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/dep-slepwear", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 273, "brand": "Each & Every", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/each-every", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 274, "brand": "Earth Harbor", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/earth-harbor", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 275, "brand": "Earth Therapeutics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/earth-therapeutics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 276, "brand": "Eco Style", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eco-style", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 277, "brand": "Ecolline", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ecolline", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 278, "brand": "EcoTools", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ecotools", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 279, "brand": "ELEMIS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/elemis", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 280, "brand": "Elizabeth Arden", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/elizabeth-arden", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 281, "brand": "Elizavecca", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/elizavecca", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 282, "brand": "Ellis Brooklyn", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ellis-brooklyn", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 283, "brand": "Embr Labs", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/embr-labs", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 284, "brand": "EMBRYOLISSE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/embryolisse", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 285, "brand": "Enzo Milano", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/enzo-milano", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 286, "brand": "Eos", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eos", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 287, "brand": "Equlib", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/equlib", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 288, "brand": "Erborian", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/erborian", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 289, "brand": "Ere Perez", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ere-perez", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 290, "brand": "ERLY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/erly", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 291, "brand": "Esha", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/esha", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 292, "brand": "Esker Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/esker-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 293, "brand": "Essence", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/essence", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 294, "brand": "Essie", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/essie", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 295, "brand": "Estée Lauder", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/estee-lauder", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 296, "brand": "Ethique Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ethique-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 297, "brand": "Ettitude", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ettitude", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 298, "brand": "ETUDE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/etude", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 299, "brand": "Eucerin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eucerin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 300, "brand": "Eva Nyc", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eva-nyc", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 301, "brand": "EvasHair", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/evashair", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 302, "brand": "Eve Lom", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eve-lom", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 303, "brand": "Evian Mineral Spray", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/evian-mineral-spray", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 304, "brand": "Evil Goods", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/evil-goods", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 305, "brand": "Evre Skincare", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/evre-skincare", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 306, "brand": "Exoceuticals", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/exoceuticals", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 307, "brand": "Exuviance", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/exuviance", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 308, "brand": "Eyeko", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eyeko", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 309, "brand": "Eylure", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/eylure", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 310, "brand": "Face Republic", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/face-republic", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 311, "brand": "Fairy Tales", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fairy-tales", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 312, "brand": "FARMACY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/farmacy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 313, "brand": "FEKKAI", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fekkai", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 314, "brand": "FENTY BEAUTY by Rihanna", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fenty-beauty-by-rihanna", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 315, "brand": "FENTY SKIN body", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fenty-skin-body", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 316, "brand": "FilterBaby", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/filterbaby", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 317, "brand": "First Aid Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/first-aid-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 318, "brand": "Flimeal", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/flimeal", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 319, "brand": "Flora Code", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/flora-code", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 320, "brand": "Florasis", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/florasis", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 321, "brand": "florence by mills", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/florence-by-mills", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 322, "brand": "FLOWER Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/flower-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 323, "brand": "Flower Knows", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/flower-knows", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 324, "brand": "Flowery", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/flowery", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 325, "brand": "FMS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fms", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 326, "brand": "FOREO", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/foreo", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 327, "brand": "Foria", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/foria", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 328, "brand": "Forte Series", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/forte-series", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 329, "brand": "frank body", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/frank-body", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 330, "brand": "fresh", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fresh", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 331, "brand": "Fromm", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fromm", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 332, "brand": "FRUDIA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/frudia", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 333, "brand": "Fur", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fur", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 334, "brand": "fwee", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/fwee", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 335, "brand": "Ga.Ma Italy Professional", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/gama-italy-professional", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 336, "brand": "Garden of Life", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/garden-of-life", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 337, "brand": "Garnier", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/garnier", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 338, "brand": "Geske", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/geske", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 339, "brand": "ghd", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ghd", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 340, "brand": "Gigi", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/gigi", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 341, "brand": "GIMME beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/gimme-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 342, "brand": "Ginger Milk", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ginger-milk", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 343, "brand": "Givenchy", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/givenchy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 344, "brand": "Glam & Grace", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glam-grace", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 345, "brand": "Glamnetic", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glamnetic", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 346, "brand": "Glamnetic x Fanatics Nail", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glamnetic-x-fanatics-nail", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 347, "brand": "Glimmer Wish", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glimmer-wish", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 348, "brand": "GLISTER", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glister", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 349, "brand": "Glo24k", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glo24k", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 350, "brand": "glowiest", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/glowiest", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 351, "brand": "Goli Nutrition", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/goli-nutrition", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 352, "brand": "Good Dye Young", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/good-dye-young", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 353, "brand": "good light", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/good-light", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 354, "brand": "Good Molecules", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/good-molecules", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 355, "brand": "GOONGBE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/goongbe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 356, "brand": "goop", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/goop", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 357, "brand": "got2b", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/got2b", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 358, "brand": "Grande Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/grande-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 359, "brand": "GROWUS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/growus", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 360, "brand": "Grüns", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/gruns", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 361, "brand": "Gucci", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/gucci", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 362, "brand": "Guerlain", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/guerlain", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 363, "brand": "GuruNanda", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/gurunanda", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 364, "brand": "HAAN", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/haan", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 365, "brand": "HackU", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hacku", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 366, "brand": "Hair+", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hair", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 367, "brand": "Hairstory", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hairstory", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 368, "brand": "HAIRtamin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hairtamin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 369, "brand": "HALEYS Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/haleys-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 370, "brand": "HALF MAGIC", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/half-magic", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 371, "brand": "HALLY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hally", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 372, "brand": "Hampton Sun", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hampton-sun", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 373, "brand": "Hanskin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hanskin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 374, "brand": "HAPPYSKINCO", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/happyskinco", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 375, "brand": "Hatch", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hatch", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 376, "brand": "HATCH MAMA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hatch-mama", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 377, "brand": "Hauteness", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hauteness", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 378, "brand": "Hawkins & Brimble", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hawkins-brimble", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 379, "brand": "Hawthorne", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hawthorne", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 380, "brand": "Healing Bird", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/healing-bird", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 381, "brand": "Heimish", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/heimish", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 382, "brand": "Helight", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/helight", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 383, "brand": "Hempz", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hempz", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 384, "brand": "Her Own", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/her-own", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 385, "brand": "HERBIVORE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/herbivore", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 386, "brand": "Heritage Store", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/heritage-store", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 387, "brand": "Hero Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hero-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 388, "brand": "Hey Honey", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hey-honey", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 389, "brand": "Heywell", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/heywell", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 390, "brand": "Hollywood Fashion Secrets", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hollywood-fashion-secrets", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 391, "brand": "Holo Taco", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/holo-taco", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 392, "brand": "Homebody", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/homebody", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 393, "brand": "HomeWorx", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/homeworx", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 394, "brand": "Honest Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/honest-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 395, "brand": "Hot Tools", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hot-tools", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 396, "brand": "HOURGLASS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hourglass", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 397, "brand": "hOURS haircare", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hours-haircare", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 398, "brand": "House of Foils", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/house-of-foils", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 399, "brand": "House of Harlow 1960", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/house-of-harlow-1960", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 400, "brand": "House of Lashes", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/house-of-lashes", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 401, "brand": "Hugger Mugger", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hugger-mugger", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 402, "brand": "Hugo Boss", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hugo-boss", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 403, "brand": "Hum Nutrition", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hum-nutrition", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 404, "brand": "Humanist Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/humanist-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 405, "brand": "Hwarang", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hwarang", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 406, "brand": "Hyggee", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hyggee", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 407, "brand": "Hygiene Hero", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hygiene-hero", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 408, "brand": "Hypothesis", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/hypothesis", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 409, "brand": "I Dew Care", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/i-dew-care", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 410, "brand": "I'm From", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/im-from", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 411, "brand": "Ialuset", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ialuset", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 412, "brand": "ICONIC LONDON", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/iconic-london", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 413, "brand": "iDesign", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/idesign", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 414, "brand": "IGK", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/igk", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 415, "brand": "iHome", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ihome", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 416, "brand": "ILIA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ilia", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 417, "brand": "Ilso", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/ilso", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 418, "brand": "Imarais Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/imarais-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 419, "brand": "Impressions Vanity", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/impressions-vanity", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 420, "brand": "In Common", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/in-common", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 421, "brand": "INDIE LEE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/indie-lee", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 422, "brand": "InfoDPlus", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/infodplus", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 423, "brand": "inh HAIR", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/inh-hair", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 424, "brand": "Inked by Dani", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/inked-by-dani", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 425, "brand": "INNER CIRCLE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/inner-circle", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 426, "brand": "Innersense Organic Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/innersense-organic-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 427, "brand": "iota", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/iota", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 428, "brand": "isima", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/isima", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 429, "brand": "ISOI", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/isoi", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 430, "brand": "Isopure Protein", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/isopure-protein", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 431, "brand": "IT Brushes For ULTA", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/it-brushes-ulta", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 432, "brand": "IT Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/it-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 433, "brand": "It's A 10", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/its-a-10", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 434, "brand": "Izzy Zero Waste Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/izzy-zero-waste-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 435, "brand": "J.Cat Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jcat-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 436, "brand": "Jack Black", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jack-black", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 437, "brand": "Jack Henry", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jack-henry", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 438, "brand": "jane iredale", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jane-iredale", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 439, "brand": "Janet Collection", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/janet-collection", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 440, "brand": "JB Skrub", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jb-skrub", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 441, "brand": "Jean Paul Gaultier", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jean-paul-gaultier", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 442, "brand": "Jenny Patinkin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jenny-patinkin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 443, "brand": "Jill", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jill", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 444, "brand": "Jimmy Choo", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jimmy-choo", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 445, "brand": "Joan & David", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/joan-david", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 446, "brand": "Johnny B. Hair Care", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/johnny-b-hair-care", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 447, "brand": "Joico", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/joico", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 448, "brand": "Jolie", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jolie", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 449, "brand": "JooY", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jooy", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 450, "brand": "Jouer Cosmetics", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jouer-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 451, "brand": "JoyBright by Ulta Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/joybright-by-ulta-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 452, "brand": "Joylux", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/joylux", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 453, "brand": "Juicy Couture", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/juicy-couture", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 454, "brand": "Juvia's Place", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/juvias-place", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 455, "brand": "JVN", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/jvn", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 456, "brand": "KAHI", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kahi", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 457, "brand": "Kaja", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kaja", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 458, "brand": "Kate Somerville", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kate-somerville", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 459, "brand": "Kate Spade New York", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kate-spade-new-york", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 460, "brand": "Kenneth Cole New York", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kenneth-cole-new-york", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 461, "brand": "Kenra Professional", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kenra-professional", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 462, "brand": "Keracolor", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/keracolor", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 463, "brand": "Keranique", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/keranique", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 464, "brand": "Keratin Complex", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/keratin-complex", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 465, "brand": "Kevyn Aucoin", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kevyn-aucoin", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 466, "brand": "KHLOÉ KARDASHIAN", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/khloe-kardashian", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 467, "brand": "Kiehl's Since 1851", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kiehls-since-1851", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 468, "brand": "KimChi Chic Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kimchi-chic-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 469, "brand": "Kind Patches", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kind-patches", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 470, "brand": "Kiss", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kiss", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 471, "brand": "Kitsch", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kitsch", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 472, "brand": "Klairs", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/klairs", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 473, "brand": "Knemo", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/knemo", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 474, "brand": "Knours.", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/knours", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 475, "brand": "KOCOSTAR", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kocostar", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 476, "brand": "Kopari Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kopari-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 477, "brand": "KORRES", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/korres", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 478, "brand": "Kreyòl Essence", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kreyol-essence", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 479, "brand": "KRISTIN ESS HAIR", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kristin-ess-hair", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 480, "brand": "Kumbra With Love", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kumbra-with-love", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 481, "brand": "KUNDAL", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kundal", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 482, "brand": "KVD Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kvd-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 483, "brand": "KYLIE COSMETICS", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/kylie-cosmetics", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 484, "brand": "L'ange", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lange", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 485, "brand": "L'anza", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lanza", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 486, "brand": "L'Occitane", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/loccitane", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 487, "brand": "L'Oréal", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/loreal", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 488, "brand": "L'Oréal Professionnel", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/loreal-professionnel", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 489, "brand": "L.A. Girl", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/la-girl", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 490, "brand": "L3VEL3", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/l3vel3", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 491, "brand": "LADOR", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lador", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 492, "brand": "Laifen", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/laifen", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 493, "brand": "Lake & Skye", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lake-skye", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 494, "brand": "LALARECIPE", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lalarecipe", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 495, "brand": "LAMIK Beauty", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lamik-beauty", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 496, "brand": "Lancer Skincare", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lancer-skincare", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 497, "brand": "Lancôme", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lancome", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 498, "brand": "Landing International", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/landing-international", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 499, "brand": "Lanolips", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lanolips", "instagram": "", "twitter": "", "wikipedia": ""},
    {"rank": 500, "brand": "Lapcos", "category": "", "share": "", "ulta_url": "https://www.ulta.com/brand/lapcos", "instagram": "", "twitter": "", "wikipedia": ""},
]
