"""
Baked-in Best Colleges reference data: U.S. News 2026 Best National Universities
(Top 50), with official website and social handles.

Versioned yearly snapshot served by the app. The U.S. News rankings page is
JavaScript-rendered and gates the full list behind a login, so ranks are stored
here and refreshed each year. Ranks reflect ties as published (shared numbers).
Social handles are official main institutional accounts; blank where not verifiable.

Source: https://www.usnews.com/best-colleges/rankings/national-universities
"""

COLLEGES_EDITION = "2026"
COLLEGES_SOURCE_URL = "https://www.usnews.com/best-colleges/rankings/national-universities"

NATIONAL_UNIVERSITIES = [
    {"rank": 1, "university": "Princeton University", "city": "Princeton", "state": "New Jersey", "website": "https://www.princeton.edu/", "facebook": "https://www.facebook.com/Princeton", "instagram": "https://www.instagram.com/princeton", "twitter": "https://x.com/Princeton", "youtube": "https://www.youtube.com/princeton", "linkedin": "https://www.linkedin.com/school/princeton-university"},
    {"rank": 2, "university": "Massachusetts Institute of Technology", "city": "Cambridge", "state": "Massachusetts", "website": "https://www.mit.edu/", "facebook": "https://www.facebook.com/MITnews", "instagram": "https://www.instagram.com/mitpics", "twitter": "https://x.com/MIT", "youtube": "https://www.youtube.com/mit", "linkedin": "https://www.linkedin.com/school/mit"},
    {"rank": 3, "university": "Harvard University", "city": "Cambridge", "state": "Massachusetts", "website": "https://www.harvard.edu/", "facebook": "https://www.facebook.com/Harvard", "instagram": "https://www.instagram.com/harvard", "twitter": "https://x.com/Harvard", "youtube": "https://www.youtube.com/harvard", "linkedin": "https://www.linkedin.com/school/harvard-university"},
    {"rank": 4, "university": "Stanford University", "city": "Stanford", "state": "California", "website": "https://www.stanford.edu/", "facebook": "https://www.facebook.com/stanford", "instagram": "https://www.instagram.com/stanford", "twitter": "https://x.com/Stanford", "youtube": "https://www.youtube.com/stanford", "linkedin": "https://www.linkedin.com/school/stanford-university"},
    {"rank": 4, "university": "Yale University", "city": "New Haven", "state": "Connecticut", "website": "https://www.yale.edu/", "facebook": "https://www.facebook.com/YaleUniversity", "instagram": "https://www.instagram.com/yale", "twitter": "https://x.com/Yale", "youtube": "https://www.youtube.com/yale", "linkedin": "https://www.linkedin.com/school/yale-university"},
    {"rank": 6, "university": "University of Chicago", "city": "Chicago", "state": "Illinois", "website": "https://www.uchicago.edu/", "facebook": "https://www.facebook.com/uchicago", "instagram": "https://www.instagram.com/uchicago", "twitter": "https://x.com/UChicago", "youtube": "https://www.youtube.com/uchicago", "linkedin": "https://www.linkedin.com/school/university-of-chicago"},
    {"rank": 7, "university": "Duke University", "city": "Durham", "state": "North Carolina", "website": "https://www.duke.edu/", "facebook": "https://www.facebook.com/DukeUniversity", "instagram": "https://www.instagram.com/dukeuniversity", "twitter": "https://x.com/DukeU", "youtube": "https://www.youtube.com/duke", "linkedin": "https://www.linkedin.com/school/duke-university"},
    {"rank": 7, "university": "Johns Hopkins University", "city": "Baltimore", "state": "Maryland", "website": "https://www.jhu.edu/", "facebook": "https://www.facebook.com/johnshopkinsuniversity", "instagram": "https://www.instagram.com/johnshopkinsu", "twitter": "https://x.com/JohnsHopkins", "youtube": "https://www.youtube.com/johnshopkins", "linkedin": "https://www.linkedin.com/school/johns-hopkins-university"},
    {"rank": 7, "university": "Northwestern University", "city": "Evanston", "state": "Illinois", "website": "https://www.northwestern.edu/", "facebook": "https://www.facebook.com/northwesternu", "instagram": "https://www.instagram.com/northwesternu", "twitter": "https://x.com/NorthwesternU", "youtube": "https://www.youtube.com/northwestern", "linkedin": "https://www.linkedin.com/school/northwestern-university"},
    {"rank": 7, "university": "University of Pennsylvania", "city": "Philadelphia", "state": "Pennsylvania", "website": "https://www.upenn.edu/", "facebook": "https://www.facebook.com/UnivPennsylvania", "instagram": "https://www.instagram.com/uofpenn", "twitter": "https://x.com/Penn", "youtube": "https://www.youtube.com/universityofpenn", "linkedin": "https://www.linkedin.com/school/university-of-pennsylvania"},
    {"rank": 11, "university": "California Institute of Technology", "city": "Pasadena", "state": "California", "website": "https://www.caltech.edu/", "facebook": "https://www.facebook.com/californiainstituteoftechnology", "instagram": "https://www.instagram.com/caltechedu", "twitter": "https://x.com/Caltech", "youtube": "https://www.youtube.com/caltech", "linkedin": "https://www.linkedin.com/school/california-institute-of-technology"},
    {"rank": 12, "university": "Cornell University", "city": "Ithaca", "state": "New York", "website": "https://www.cornell.edu/", "facebook": "https://www.facebook.com/Cornell", "instagram": "https://www.instagram.com/cornelluniversity", "twitter": "https://x.com/Cornell", "youtube": "https://www.youtube.com/cornell", "linkedin": "https://www.linkedin.com/school/cornell-university"},
    {"rank": 13, "university": "Brown University", "city": "Providence", "state": "Rhode Island", "website": "https://www.brown.edu/", "facebook": "https://www.facebook.com/BrownUniversity", "instagram": "https://www.instagram.com/brownu", "twitter": "https://x.com/BrownUniversity", "youtube": "https://www.youtube.com/brownuniversity", "linkedin": "https://www.linkedin.com/school/brown-university"},
    {"rank": 13, "university": "Dartmouth College", "city": "Hanover", "state": "New Hampshire", "website": "https://www.dartmouth.edu/", "facebook": "https://www.facebook.com/Dartmouth", "instagram": "https://www.instagram.com/dartmouthcollege", "twitter": "https://x.com/dartmouth", "youtube": "https://www.youtube.com/dartmouth", "linkedin": "https://www.linkedin.com/school/dartmouth-college"},
    {"rank": 15, "university": "Columbia University", "city": "New York", "state": "New York", "website": "https://www.columbia.edu/", "facebook": "https://www.facebook.com/columbia", "instagram": "https://www.instagram.com/columbia", "twitter": "https://x.com/Columbia", "youtube": "https://www.youtube.com/columbia", "linkedin": "https://www.linkedin.com/school/columbia-university"},
    {"rank": 15, "university": "University of California, Berkeley", "city": "Berkeley", "state": "California", "website": "https://www.berkeley.edu/", "facebook": "https://www.facebook.com/UCBerkeley", "instagram": "https://www.instagram.com/ucberkeleyofficial", "twitter": "https://x.com/UCBerkeley", "youtube": "https://www.youtube.com/ucberkeley", "linkedin": "https://www.linkedin.com/school/uc-berkeley"},
    {"rank": 17, "university": "Rice University", "city": "Houston", "state": "Texas", "website": "https://www.rice.edu/", "facebook": "https://www.facebook.com/RiceUniversity", "instagram": "https://www.instagram.com/riceuniversity", "twitter": "https://x.com/RiceUniversity", "youtube": "https://www.youtube.com/riceuniversity", "linkedin": "https://www.linkedin.com/school/rice-university"},
    {"rank": 17, "university": "University of California, Los Angeles", "city": "Los Angeles", "state": "California", "website": "https://www.ucla.edu/", "facebook": "https://www.facebook.com/UCLA", "instagram": "https://www.instagram.com/ucla", "twitter": "https://x.com/UCLA", "youtube": "https://www.youtube.com/ucla", "linkedin": "https://www.linkedin.com/school/ucla"},
    {"rank": 17, "university": "Vanderbilt University", "city": "Nashville", "state": "Tennessee", "website": "https://www.vanderbilt.edu/", "facebook": "https://www.facebook.com/vanderbilt", "instagram": "https://www.instagram.com/vanderbiltu", "twitter": "https://x.com/VanderbiltU", "youtube": "https://www.youtube.com/vanderbiltuniversity", "linkedin": "https://www.linkedin.com/school/vanderbilt-university"},
    {"rank": 20, "university": "Carnegie Mellon University", "city": "Pittsburgh", "state": "Pennsylvania", "website": "https://www.cmu.edu/", "facebook": "https://www.facebook.com/carnegiemellonu", "instagram": "https://www.instagram.com/carnegiemellon", "twitter": "https://x.com/CarnegieMellon", "youtube": "https://www.youtube.com/carnegiemellonu", "linkedin": "https://www.linkedin.com/school/carnegie-mellon-university"},
    {"rank": 20, "university": "University of Michigan-Ann Arbor", "city": "Ann Arbor", "state": "Michigan", "website": "https://www.umich.edu/", "facebook": "https://www.facebook.com/universityofmichigan", "instagram": "https://www.instagram.com/uofmichigan", "twitter": "https://x.com/UMich", "youtube": "https://www.youtube.com/um", "linkedin": "https://www.linkedin.com/school/university-of-michigan"},
    {"rank": 20, "university": "University of Notre Dame", "city": "Notre Dame", "state": "Indiana", "website": "https://www.nd.edu/", "facebook": "https://www.facebook.com/notredame", "instagram": "https://www.instagram.com/notredame", "twitter": "https://x.com/NotreDame", "youtube": "https://www.youtube.com/notredame", "linkedin": "https://www.linkedin.com/school/university-of-notre-dame"},
    {"rank": 20, "university": "Washington University in St. Louis", "city": "St. Louis", "state": "Missouri", "website": "https://www.wustl.edu/", "facebook": "https://www.facebook.com/WUSTLofficial", "instagram": "https://www.instagram.com/washu", "twitter": "https://x.com/WUSTL", "youtube": "https://www.youtube.com/wustl", "linkedin": "https://www.linkedin.com/school/washington-university-in-st-louis"},
    {"rank": 24, "university": "Emory University", "city": "Atlanta", "state": "Georgia", "website": "https://www.emory.edu/", "facebook": "https://www.facebook.com/emoryuniversity", "instagram": "https://www.instagram.com/emoryuniversity", "twitter": "https://x.com/EmoryUniversity", "youtube": "https://www.youtube.com/emoryuniversity", "linkedin": "https://www.linkedin.com/school/emory-university"},
    {"rank": 24, "university": "Georgetown University", "city": "Washington", "state": "District of Columbia", "website": "https://www.georgetown.edu/", "facebook": "https://www.facebook.com/georgetownuniv", "instagram": "https://www.instagram.com/georgetownuniversity", "twitter": "https://x.com/Georgetown", "youtube": "https://www.youtube.com/georgetownuniversity", "linkedin": "https://www.linkedin.com/school/georgetown-university"},
    {"rank": 26, "university": "University of North Carolina at Chapel Hill", "city": "Chapel Hill", "state": "North Carolina", "website": "https://www.unc.edu/", "facebook": "https://www.facebook.com/UNCChapelHill", "instagram": "https://www.instagram.com/uncchapelhill", "twitter": "https://x.com/UNC", "youtube": "https://www.youtube.com/uncchapelhill", "linkedin": "https://www.linkedin.com/school/unc-chapel-hill"},
    {"rank": 26, "university": "University of Virginia", "city": "Charlottesville", "state": "Virginia", "website": "https://www.virginia.edu/", "facebook": "https://www.facebook.com/UniversityofVirginia", "instagram": "https://www.instagram.com/uva", "twitter": "https://x.com/UVA", "youtube": "https://www.youtube.com/uva", "linkedin": "https://www.linkedin.com/school/university-of-virginia"},
    {"rank": 28, "university": "University of Southern California", "city": "Los Angeles", "state": "California", "website": "https://www.usc.edu/", "facebook": "https://www.facebook.com/USC", "instagram": "https://www.instagram.com/usc", "twitter": "https://x.com/USC", "youtube": "https://www.youtube.com/usc", "linkedin": "https://www.linkedin.com/school/university-of-southern-california"},
    {"rank": 29, "university": "University of California, San Diego", "city": "La Jolla", "state": "California", "website": "https://www.ucsd.edu/", "facebook": "https://www.facebook.com/UCSanDiego", "instagram": "https://www.instagram.com/ucsandiego", "twitter": "https://x.com/UCSanDiego", "youtube": "https://www.youtube.com/ucsandiego", "linkedin": "https://www.linkedin.com/school/uc-san-diego"},
    {"rank": 30, "university": "University of Florida", "city": "Gainesville", "state": "Florida", "website": "https://www.ufl.edu/", "facebook": "https://www.facebook.com/uflorida", "instagram": "https://www.instagram.com/uflorida", "twitter": "https://x.com/UF", "youtube": "https://www.youtube.com/universityofflorida", "linkedin": "https://www.linkedin.com/school/university-of-florida"},
    {"rank": 30, "university": "University of Texas at Austin", "city": "Austin", "state": "Texas", "website": "https://www.utexas.edu/", "facebook": "https://www.facebook.com/UTAustinTX", "instagram": "https://www.instagram.com/utaustintx", "twitter": "https://x.com/UTAustin", "youtube": "https://www.youtube.com/universityoftexasataustin", "linkedin": "https://www.linkedin.com/school/university-of-texas-at-austin"},
    {"rank": 32, "university": "Georgia Institute of Technology", "city": "Atlanta", "state": "Georgia", "website": "https://www.gatech.edu/", "facebook": "https://www.facebook.com/georgiatech", "instagram": "https://www.instagram.com/georgiatech", "twitter": "https://x.com/GeorgiaTech", "youtube": "https://www.youtube.com/georgiatech", "linkedin": "https://www.linkedin.com/school/georgia-institute-of-technology"},
    {"rank": 32, "university": "New York University", "city": "New York", "state": "New York", "website": "https://www.nyu.edu/", "facebook": "https://www.facebook.com/NYU", "instagram": "https://www.instagram.com/nyuniversity", "twitter": "https://x.com/nyuniversity", "youtube": "https://www.youtube.com/nyu", "linkedin": "https://www.linkedin.com/school/new-york-university"},
    {"rank": 32, "university": "University of California, Davis", "city": "Davis", "state": "California", "website": "https://www.ucdavis.edu/", "facebook": "https://www.facebook.com/UCDavis", "instagram": "https://www.instagram.com/ucdavis", "twitter": "https://x.com/UCDavis", "youtube": "https://www.youtube.com/ucdavis", "linkedin": "https://www.linkedin.com/school/uc-davis"},
    {"rank": 32, "university": "University of California, Irvine", "city": "Irvine", "state": "California", "website": "https://www.uci.edu/", "facebook": "https://www.facebook.com/UCIrvine", "instagram": "https://www.instagram.com/ucirvine", "twitter": "https://x.com/UCIrvine", "youtube": "https://www.youtube.com/ucirvine", "linkedin": "https://www.linkedin.com/school/uc-irvine"},
    {"rank": 36, "university": "Boston College", "city": "Chestnut Hill", "state": "Massachusetts", "website": "https://www.bc.edu/", "facebook": "https://www.facebook.com/bostoncollege", "instagram": "https://www.instagram.com/bostoncollege", "twitter": "https://x.com/BostonCollege", "youtube": "https://www.youtube.com/bc", "linkedin": "https://www.linkedin.com/school/boston-college"},
    {"rank": 36, "university": "Tufts University", "city": "Medford", "state": "Massachusetts", "website": "https://www.tufts.edu/", "facebook": "https://www.facebook.com/tuftsuniversity", "instagram": "https://www.instagram.com/tuftsuniversity", "twitter": "https://x.com/TuftsUniversity", "youtube": "https://www.youtube.com/tuftsuniversity", "linkedin": "https://www.linkedin.com/school/tufts-university"},
    {"rank": 36, "university": "University of Illinois Urbana-Champaign", "city": "Champaign", "state": "Illinois", "website": "https://illinois.edu/", "facebook": "", "instagram": "https://www.instagram.com/illinois1867", "twitter": "", "youtube": "https://www.youtube.com/universityofillinois", "linkedin": "https://www.linkedin.com/school/university-of-illinois-at-urbana-champaign"},
    {"rank": 36, "university": "University of Wisconsin-Madison", "city": "Madison", "state": "Wisconsin", "website": "https://www.wisc.edu/", "facebook": "https://www.facebook.com/UWMadison", "instagram": "https://www.instagram.com/uwmadison", "twitter": "https://x.com/UWMadison", "youtube": "https://www.youtube.com/uwmadison", "linkedin": "https://www.linkedin.com/school/university-of-wisconsin-madison"},
    {"rank": 40, "university": "University of California, Santa Barbara", "city": "Santa Barbara", "state": "California", "website": "https://www.ucsb.edu/", "facebook": "https://www.facebook.com/ucsantabarbara", "instagram": "https://www.instagram.com/ucsantabarbara", "twitter": "https://x.com/ucsantabarbara", "youtube": "https://www.youtube.com/ucsantabarbara", "linkedin": "https://www.linkedin.com/school/uc-santa-barbara"},
    {"rank": 41, "university": "The Ohio State University", "city": "Columbus", "state": "Ohio", "website": "https://www.osu.edu/", "facebook": "https://www.facebook.com/osu", "instagram": "https://www.instagram.com/theohiostateuniversity", "twitter": "https://x.com/OhioState", "youtube": "https://www.youtube.com/theohiostateuniversity", "linkedin": "https://www.linkedin.com/school/the-ohio-state-university"},
    {"rank": 42, "university": "Boston University", "city": "Boston", "state": "Massachusetts", "website": "https://www.bu.edu/", "facebook": "https://www.facebook.com/BostonUniversity", "instagram": "https://www.instagram.com/bostonu", "twitter": "https://x.com/BU_Tweets", "youtube": "https://www.youtube.com/bostonuniversity", "linkedin": "https://www.linkedin.com/school/boston-university"},
    {"rank": 42, "university": "Rutgers University-New Brunswick", "city": "New Brunswick", "state": "New Jersey", "website": "https://www.rutgers.edu/", "facebook": "https://www.facebook.com/RutgersU", "instagram": "https://www.instagram.com/rutgersu", "twitter": "https://x.com/RutgersU", "youtube": "https://www.youtube.com/rutgersuniversity", "linkedin": "https://www.linkedin.com/school/rutgers-university"},
    {"rank": 42, "university": "University of Maryland, College Park", "city": "College Park", "state": "Maryland", "website": "https://www.umd.edu/", "facebook": "https://www.facebook.com/UnivofMaryland", "instagram": "https://www.instagram.com/univofmaryland", "twitter": "https://x.com/UofMaryland", "youtube": "https://www.youtube.com/universityofmaryland", "linkedin": "https://www.linkedin.com/school/university-of-maryland"},
    {"rank": 42, "university": "University of Washington", "city": "Seattle", "state": "Washington", "website": "https://www.washington.edu/", "facebook": "https://www.facebook.com/UofWA", "instagram": "https://www.instagram.com/uofwa", "twitter": "https://x.com/UW", "youtube": "", "linkedin": "https://www.linkedin.com/school/university-of-washington"},
    {"rank": 46, "university": "Lehigh University", "city": "Bethlehem", "state": "Pennsylvania", "website": "https://www.lehigh.edu/", "facebook": "https://www.facebook.com/LehighU", "instagram": "https://www.instagram.com/lehighu", "twitter": "https://x.com/LehighU", "youtube": "https://www.youtube.com/lehighuniversity", "linkedin": "https://www.linkedin.com/school/lehigh-university"},
    {"rank": 46, "university": "Northeastern University", "city": "Boston", "state": "Massachusetts", "website": "https://www.northeastern.edu/", "facebook": "https://www.facebook.com/northeastern", "instagram": "https://www.instagram.com/northeastern", "twitter": "https://x.com/Northeastern", "youtube": "https://www.youtube.com/northeastern", "linkedin": "https://www.linkedin.com/school/northeastern-university"},
    {"rank": 46, "university": "Purdue University-West Lafayette", "city": "West Lafayette", "state": "Indiana", "website": "https://www.purdue.edu/", "facebook": "https://www.facebook.com/purdue", "instagram": "https://www.instagram.com/lifeatpurdue", "twitter": "https://x.com/LifeAtPurdue", "youtube": "https://www.youtube.com/purdue", "linkedin": "https://www.linkedin.com/school/purdue-university"},
    {"rank": 46, "university": "University of Georgia", "city": "Athens", "state": "Georgia", "website": "https://www.uga.edu/", "facebook": "https://www.facebook.com/universityofga", "instagram": "https://www.instagram.com/universityofga", "twitter": "https://x.com/universityofga", "youtube": "https://www.youtube.com/universityofga", "linkedin": "https://www.linkedin.com/school/university-of-georgia"},
    {"rank": 46, "university": "University of Rochester", "city": "Rochester", "state": "New York", "website": "https://www.rochester.edu/", "facebook": "https://www.facebook.com/UniversityofRochester", "instagram": "https://www.instagram.com/urochester", "twitter": "https://x.com/UofR", "youtube": "https://www.youtube.com/universityofrochester", "linkedin": "https://www.linkedin.com/school/university-of-rochester"},
]
