"""Major consumer packaged goods (CPG) brands. Source: instacartbrandlist.com."""
CPG_EDITION = "Major CPG brands"
CPG_SOURCE_URL = "https://instacartbrandlist.com/"
W="https://en.wikipedia.org/wiki/"
def _t(rank,brand,parent,wiki):
    return {"rank":rank,"brand":brand,"parent":parent,"website":"","wikipedia":W+wiki}
CPG_BRANDS=[
 _t(1,"Coca-Cola","The Coca-Cola Company","Coca-Cola"),
 _t(2,"Pepsi","PepsiCo","Pepsi"),
 _t(3,"Lay's","PepsiCo","Lay's"),
 _t(4,"Doritos","PepsiCo","Doritos"),
 _t(5,"Gatorade","PepsiCo","Gatorade"),
 _t(6,"Mountain Dew","PepsiCo","Mountain_Dew"),
 _t(7,"Cheetos","PepsiCo","Cheetos"),
 _t(8,"Quaker Oats","PepsiCo","Quaker_Oats_Company"),
 _t(9,"Sprite","The Coca-Cola Company","Sprite_(drink)"),
 _t(10,"Fanta","The Coca-Cola Company","Fanta"),
 _t(11,"Nescafé","Nestlé","Nescafé"),
 _t(12,"Nestlé","Nestlé","Nestlé"),
 _t(13,"Kit Kat","Nestlé / Hershey (US)","Kit_Kat"),
 _t(14,"Häagen-Dazs","Nestlé / General Mills","Häagen-Dazs"),
 _t(15,"Oreo","Mondelez International","Oreo"),
 _t(16,"Ritz","Mondelez International","Ritz_Crackers"),
 _t(17,"Cadbury","Mondelez International","Cadbury"),
 _t(18,"Tide","Procter & Gamble","Tide_(brand)"),
 _t(19,"Pampers","Procter & Gamble","Pampers"),
 _t(20,"Gillette","Procter & Gamble","Gillette"),
 _t(21,"Crest","Procter & Gamble","Crest_(toothpaste)"),
 _t(22,"Bounty","Procter & Gamble","Bounty_(brand)"),
 _t(23,"Charmin","Procter & Gamble","Charmin"),
 _t(24,"Dove","Unilever","Dove_(brand)"),
 _t(25,"Hellmann's","Unilever","Hellmann's_and_Best_Foods"),
 _t(26,"Ben & Jerry's","Unilever","Ben_&_Jerry's"),
 _t(27,"Lipton","Unilever","Lipton"),
 _t(28,"Heinz","Kraft Heinz","Heinz"),
 _t(29,"Kraft Mac & Cheese","Kraft Heinz","Kraft_Dinner"),
 _t(30,"Oscar Mayer","Kraft Heinz","Oscar_Mayer"),
 _t(31,"Cheerios","General Mills","Cheerios"),
 _t(32,"Nature Valley","General Mills","Nature_Valley"),
 _t(33,"Betty Crocker","General Mills","Betty_Crocker"),
 _t(34,"Pillsbury","General Mills","Pillsbury_Company"),
 _t(35,"Frosted Flakes","Kellanova","Frosted_Flakes"),
 _t(36,"Pop-Tarts","Kellanova","Pop-Tarts"),
 _t(37,"Pringles","Kellanova","Pringles"),
 _t(38,"Hershey's","The Hershey Company","The_Hershey_Company"),
 _t(39,"Reese's","The Hershey Company","Reese's_Peanut_Butter_Cups"),
 _t(40,"M&M's","Mars, Incorporated","M&M's"),
 _t(41,"Snickers","Mars, Incorporated","Snickers"),
 _t(42,"Folgers","The J.M. Smucker Company","Folgers"),
 _t(43,"Campbell's","The Campbell's Company","Campbell_Soup_Company"),
 _t(44,"Clorox","The Clorox Company","Clorox"),
 _t(45,"Listerine","Kenvue","Listerine"),
 _t(46,"Huggies","Kimberly-Clark","Huggies"),
 _t(47,"Kleenex","Kimberly-Clark","Kleenex"),
 _t(48,"Red Bull","Red Bull GmbH","Red_Bull"),
 _t(49,"Chobani","Chobani","Chobani"),
 _t(50,"Nutella","Ferrero","Nutella"),
]
