"""
Baked-in best-hospital reference data (United States): website, official
socials, and Wikipedia page.

Versioned yearly snapshot served by the app. Social handles are official
system-level accounts; blank where not verifiable. Wikipedia links use
Wikipedia search-redirect so they always resolve.

Sources:
- U.S. News & World Report - Best Hospitals 2025-2026 Honor Roll (non-ordinal).
  https://health.usnews.com/health-care/best-hospitals/articles/best-hospitals-honor-roll-and-overview
- Newsweek / Statista - World's Best Hospitals 2026, United States.
  https://rankings.newsweek.com/worlds-best-hospitals-2026/united-states
"""

US_NEWS_EDITION = "2025-2026"
US_NEWS_SOURCE_URL = (
    "https://health.usnews.com/health-care/best-hospitals/articles/"
    "best-hospitals-honor-roll-and-overview"
)

US_NEWS_HONOR_ROLL = [
    {"hospital": "Mayo Clinic-Arizona", "city": "Phoenix", "state": "Arizona", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Mayo%20Clinic-Arizona&go=Go"},
    {"hospital": "Cedars-Sinai Medical Center", "city": "Los Angeles", "state": "California", "website": "https://www.cedars-sinai.org/", "facebook": "https://www.facebook.com/CedarsSinai", "instagram": "https://www.instagram.com/cedarssinai", "twitter": "https://x.com/CedarsSinai", "youtube": "https://www.youtube.com/user/CEDARSSINAI", "linkedin": "https://www.linkedin.com/company/cedars-sinai-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Cedars-Sinai%20Medical%20Center&go=Go"},
    {"hospital": "Stanford Health Care-Stanford Hospital", "city": "Palo Alto", "state": "California", "website": "https://www.stanfordhealthcare.org/", "facebook": "https://www.facebook.com/StanfordHealthCare", "instagram": "https://www.instagram.com/stanford.healthcare", "twitter": "https://x.com/StanfordHealth", "youtube": "https://www.youtube.com/@StanfordHospital", "linkedin": "https://www.linkedin.com/company/stanford-health-care", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Stanford%20Health%20Care-Stanford%20Hospital&go=Go"},
    {"hospital": "UCLA Medical Center", "city": "Los Angeles", "state": "California", "website": "https://www.uclahealth.org/", "facebook": "https://www.facebook.com/uclahealth", "instagram": "https://www.instagram.com/uclahealth", "twitter": "https://x.com/uclahealth", "youtube": "https://www.youtube.com/uclahealth", "linkedin": "https://www.linkedin.com/company/ucla-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UCLA%20Medical%20Center&go=Go"},
    {"hospital": "UCSF Health-UCSF Medical Center", "city": "San Francisco", "state": "California", "website": "https://www.ucsfhealth.org/", "facebook": "https://www.facebook.com/UCSFMedicalCenter", "instagram": "https://www.instagram.com/ucsfhealth", "twitter": "https://x.com/ucsfhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/ucsfhealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UCSF%20Health-UCSF%20Medical%20Center&go=Go"},
    {"hospital": "AdventHealth Orlando", "city": "Orlando", "state": "Florida", "website": "https://www.adventhealth.com/", "facebook": "https://www.facebook.com/AdventHealth", "instagram": "https://www.instagram.com/adventhealth", "twitter": "https://x.com/AdventHealth", "youtube": "https://www.youtube.com/@AdventHealth", "linkedin": "https://www.linkedin.com/company/adventhealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=AdventHealth%20Orlando&go=Go"},
    {"hospital": "Northwestern Medicine-Northwestern Memorial Hospital", "city": "Chicago", "state": "Illinois", "website": "https://www.nm.org/", "facebook": "https://www.facebook.com/northwesternmedicine", "instagram": "https://www.instagram.com/northwesternmedicine", "twitter": "https://x.com/NorthwesternMed", "youtube": "https://www.youtube.com/user/NMHChicago", "linkedin": "https://www.linkedin.com/company/northwestern-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Northwestern%20Medicine-Northwestern%20Memorial%20Hospital&go=Go"},
    {"hospital": "Rush University Medical Center", "city": "Chicago", "state": "Illinois", "website": "https://www.rush.edu/", "facebook": "https://www.facebook.com/RushUniversityMedicalCenter", "instagram": "https://www.instagram.com/rushmedical", "twitter": "", "youtube": "https://www.youtube.com/user/rushmedicalcenter", "linkedin": "https://www.linkedin.com/company/rush-university-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Rush%20University%20Medical%20Center&go=Go"},
    {"hospital": "Johns Hopkins Hospital", "city": "Baltimore", "state": "Maryland", "website": "https://www.hopkinsmedicine.org/", "facebook": "https://www.facebook.com/Johns.Hopkins.Medicine", "instagram": "https://www.instagram.com/hopkinsmedicine", "twitter": "https://x.com/HopkinsMedicine", "youtube": "https://www.youtube.com/user/JohnsHopkinsMedicine", "linkedin": "https://www.linkedin.com/company/johns-hopkins-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Johns%20Hopkins%20Hospital&go=Go"},
    {"hospital": "Brigham and Women's Hospital", "city": "Boston", "state": "Massachusetts", "website": "https://www.brighamandwomens.org/", "facebook": "https://www.facebook.com/BrighamandWomensHospital", "instagram": "https://www.instagram.com/brighamandwomens", "twitter": "https://x.com/BrighamWomens", "youtube": "https://www.youtube.com/brighamandwomens", "linkedin": "https://www.linkedin.com/company/brigham-and-womens-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Brigham%20and%20Women%27s%20Hospital&go=Go"},
    {"hospital": "Massachusetts General Hospital", "city": "Boston", "state": "Massachusetts", "website": "https://www.massgeneral.org/", "facebook": "https://www.facebook.com/massgeneral", "instagram": "https://www.instagram.com/massgeneral", "twitter": "https://x.com/MassGeneralNews", "youtube": "", "linkedin": "https://www.linkedin.com/company/massachusetts-general-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Massachusetts%20General%20Hospital&go=Go"},
    {"hospital": "University of Michigan Health", "city": "Ann Arbor", "state": "Michigan", "website": "https://www.uofmhealth.org/", "facebook": "https://www.facebook.com/MichiganMedicine", "instagram": "https://www.instagram.com/umichmedicine", "twitter": "https://x.com/umichmedicine", "youtube": "", "linkedin": "https://www.linkedin.com/company/michigan-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20Michigan%20Health&go=Go"},
    {"hospital": "Mayo Clinic-Rochester", "city": "Rochester", "state": "Minnesota", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Mayo%20Clinic-Rochester&go=Go"},
    {"hospital": "Hackensack University Medical Center at Hackensack Meridian Health", "city": "Hackensack", "state": "New Jersey", "website": "https://www.hackensackmeridianhealth.org/", "facebook": "https://www.facebook.com/HackensackMeridianHealth", "instagram": "https://www.instagram.com/hmhnewjersey", "twitter": "https://x.com/HMHNewJersey", "youtube": "https://www.youtube.com/channel/UCGNz3pc9coZmYxUuLFJSKtQ", "linkedin": "https://www.linkedin.com/company/hackensackmeridianhealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Hackensack%20University%20Medical%20Center%20at%20Hackensack%20Meridian%20Health&go=Go"},
    {"hospital": "Mount Sinai Hospital", "city": "New York City", "state": "New York", "website": "https://www.mountsinai.org/", "facebook": "https://www.facebook.com/MountSinaiNYC", "instagram": "https://www.instagram.com/mountsinainyc", "twitter": "https://x.com/MountSinaiNYC", "youtube": "https://www.youtube.com/user/MountSinaiNY", "linkedin": "https://www.linkedin.com/company/mountsinainyc", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Mount%20Sinai%20Hospital&go=Go"},
    {"hospital": "New York-Presbyterian Hospital-Columbia and Cornell", "city": "New York City", "state": "New York", "website": "https://www.nyp.org/", "facebook": "https://www.facebook.com/newyorkpresbyterian", "instagram": "https://www.instagram.com/nyphospital", "twitter": "https://x.com/nyphospital", "youtube": "https://www.youtube.com/user/newyorkpresbyterian", "linkedin": "https://www.linkedin.com/company/new-york-presbyterian-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=New%20York-Presbyterian%20Hospital-Columbia%20and%20Cornell&go=Go"},
    {"hospital": "NYU Langone Hospitals", "city": "New York City", "state": "New York", "website": "https://www.nyulangone.org/", "facebook": "https://www.facebook.com/NYULangone", "instagram": "https://www.instagram.com/nyulangone", "twitter": "https://x.com/nyulangone", "youtube": "https://www.youtube.com/c/NYULangoneHealth", "linkedin": "https://www.linkedin.com/company/nyulangonehealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=NYU%20Langone%20Hospitals&go=Go"},
    {"hospital": "Cleveland Clinic", "city": "Cleveland", "state": "Ohio", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Cleveland%20Clinic&go=Go"},
    {"hospital": "Hospitals of the University of Pennsylvania-Penn Presbyterian", "city": "Philadelphia", "state": "Pennsylvania", "website": "https://www.pennmedicine.org/", "facebook": "https://www.facebook.com/pennmed", "instagram": "https://www.instagram.com/pennmedicine", "twitter": "https://x.com/PennMedicine", "youtube": "https://www.youtube.com/pennmedicine", "linkedin": "https://www.linkedin.com/company/university-of-pennsylvania-health-system", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Hospitals%20of%20the%20University%20of%20Pennsylvania-Penn%20Presbyterian&go=Go"},
    {"hospital": "Houston Methodist Hospital", "city": "Houston", "state": "Texas", "website": "https://www.houstonmethodist.org/", "facebook": "https://www.facebook.com/houstonmethodist", "instagram": "https://www.instagram.com/houstonmethodist", "twitter": "https://x.com/hmethodistcares", "youtube": "https://www.youtube.com/@HoustonMethodist", "linkedin": "https://www.linkedin.com/company/houston-methodist", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Houston%20Methodist%20Hospital&go=Go"},
]

NEWSWEEK_EDITION = "2026"
NEWSWEEK_SOURCE_URL = "https://rankings.newsweek.com/worlds-best-hospitals-2026/united-states"

NEWSWEEK_US = [
    {"rank": 1, "hospital": "Mayo Clinic - Rochester", "city": "Rochester", "state": "Minnesota", "score": "96.28%", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Mayo%20Clinic%20-%20Rochester&go=Go"},
    {"rank": 2, "hospital": "Cleveland Clinic", "city": "Cleveland", "state": "Ohio", "score": "92.13%", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Cleveland%20Clinic&go=Go"},
    {"rank": 3, "hospital": "Massachusetts General Hospital", "city": "Boston", "state": "Massachusetts", "score": "91.96%", "website": "https://www.massgeneral.org/", "facebook": "https://www.facebook.com/massgeneral", "instagram": "https://www.instagram.com/massgeneral", "twitter": "https://x.com/MassGeneralNews", "youtube": "", "linkedin": "https://www.linkedin.com/company/massachusetts-general-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Massachusetts%20General%20Hospital&go=Go"},
    {"rank": 4, "hospital": "The Johns Hopkins Hospital", "city": "Baltimore", "state": "Maryland", "score": "89.77%", "website": "https://www.hopkinsmedicine.org/", "facebook": "https://www.facebook.com/Johns.Hopkins.Medicine", "instagram": "https://www.instagram.com/hopkinsmedicine", "twitter": "https://x.com/HopkinsMedicine", "youtube": "https://www.youtube.com/user/JohnsHopkinsMedicine", "linkedin": "https://www.linkedin.com/company/johns-hopkins-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Johns%20Hopkins%20Hospital&go=Go"},
    {"rank": 5, "hospital": "Ronald Reagan UCLA Medical Center", "city": "Los Angeles", "state": "California", "score": "89.68%", "website": "https://www.uclahealth.org/", "facebook": "https://www.facebook.com/uclahealth", "instagram": "https://www.instagram.com/uclahealth", "twitter": "https://x.com/uclahealth", "youtube": "https://www.youtube.com/uclahealth", "linkedin": "https://www.linkedin.com/company/ucla-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Ronald%20Reagan%20UCLA%20Medical%20Center&go=Go"},
    {"rank": 6, "hospital": "Brigham and Women's Hospital", "city": "Boston", "state": "Massachusetts", "score": "89.64%", "website": "https://www.brighamandwomens.org/", "facebook": "https://www.facebook.com/BrighamandWomensHospital", "instagram": "https://www.instagram.com/brighamandwomens", "twitter": "https://x.com/BrighamWomens", "youtube": "https://www.youtube.com/brighamandwomens", "linkedin": "https://www.linkedin.com/company/brigham-and-womens-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Brigham%20and%20Women%27s%20Hospital&go=Go"},
    {"rank": 7, "hospital": "The Mount Sinai Hospital", "city": "New York City", "state": "New York", "score": "88.37%", "website": "https://www.mountsinai.org/", "facebook": "https://www.facebook.com/MountSinaiNYC", "instagram": "https://www.instagram.com/mountsinainyc", "twitter": "https://x.com/MountSinaiNYC", "youtube": "https://www.youtube.com/user/MountSinaiNY", "linkedin": "https://www.linkedin.com/company/mountsinainyc", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=The%20Mount%20Sinai%20Hospital&go=Go"},
    {"rank": 8, "hospital": "Stanford Health Care - Stanford Hospital", "city": "Stanford", "state": "California", "score": "88.19%", "website": "https://www.stanfordhealthcare.org/", "facebook": "https://www.facebook.com/StanfordHealthCare", "instagram": "https://www.instagram.com/stanford.healthcare", "twitter": "https://x.com/StanfordHealth", "youtube": "https://www.youtube.com/@StanfordHospital", "linkedin": "https://www.linkedin.com/company/stanford-health-care", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Stanford%20Health%20Care%20-%20Stanford%20Hospital&go=Go"},
    {"rank": 9, "hospital": "UCSF Medical Center", "city": "San Francisco", "state": "California", "score": "86.77%", "website": "https://www.ucsfhealth.org/", "facebook": "https://www.facebook.com/UCSFMedicalCenter", "instagram": "https://www.instagram.com/ucsfhealth", "twitter": "https://x.com/ucsfhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/ucsfhealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UCSF%20Medical%20Center&go=Go"},
    {"rank": 10, "hospital": "Cedars-Sinai Medical Center", "city": "Los Angeles", "state": "California", "score": "86.73%", "website": "https://www.cedars-sinai.org/", "facebook": "https://www.facebook.com/CedarsSinai", "instagram": "https://www.instagram.com/cedarssinai", "twitter": "https://x.com/CedarsSinai", "youtube": "https://www.youtube.com/user/CEDARSSINAI", "linkedin": "https://www.linkedin.com/company/cedars-sinai-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Cedars-Sinai%20Medical%20Center&go=Go"},
    {"rank": 11, "hospital": "Mayo Clinic - Jacksonville", "city": "Jacksonville", "state": "Florida", "score": "86.69%", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Mayo%20Clinic%20-%20Jacksonville&go=Go"},
    {"rank": 12, "hospital": "University of Michigan Health - Ann Arbor", "city": "Ann Arbor", "state": "Michigan", "score": "86.59%", "website": "https://www.uofmhealth.org/", "facebook": "https://www.facebook.com/MichiganMedicine", "instagram": "https://www.instagram.com/umichmedicine", "twitter": "https://x.com/umichmedicine", "youtube": "", "linkedin": "https://www.linkedin.com/company/michigan-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20Michigan%20Health%20-%20Ann%20Arbor&go=Go"},
    {"rank": 13, "hospital": "Northwestern Memorial Hospital", "city": "Chicago", "state": "Illinois", "score": "86.33%", "website": "https://www.nm.org/", "facebook": "https://www.facebook.com/northwesternmedicine", "instagram": "https://www.instagram.com/northwesternmedicine", "twitter": "https://x.com/NorthwesternMed", "youtube": "https://www.youtube.com/user/NMHChicago", "linkedin": "https://www.linkedin.com/company/northwestern-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Northwestern%20Memorial%20Hospital&go=Go"},
    {"rank": 14, "hospital": "Duke University Hospital", "city": "Durham", "state": "North Carolina", "score": "86.13%", "website": "https://www.dukehealth.org/", "facebook": "https://www.facebook.com/dukehealth", "instagram": "https://www.instagram.com/dukehealth", "twitter": "https://x.com/DukeHealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/duke-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Duke%20University%20Hospital&go=Go"},
    {"rank": 15, "hospital": "Hospital of the University of Pennsylvania", "city": "Philadelphia", "state": "Pennsylvania", "score": "85.78%", "website": "https://www.pennmedicine.org/", "facebook": "https://www.facebook.com/pennmed", "instagram": "https://www.instagram.com/pennmedicine", "twitter": "https://x.com/PennMedicine", "youtube": "https://www.youtube.com/pennmedicine", "linkedin": "https://www.linkedin.com/company/university-of-pennsylvania-health-system", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Hospital%20of%20the%20University%20of%20Pennsylvania&go=Go"},
    {"rank": 16, "hospital": "Mayo Clinic - Phoenix", "city": "Phoenix", "state": "Arizona", "score": "84.71%", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Mayo%20Clinic%20-%20Phoenix&go=Go"},
    {"rank": 17, "hospital": "NewYork-Presbyterian Columbia University Irving Medical Center", "city": "New York City", "state": "New York", "score": "84.22%", "website": "https://www.nyp.org/", "facebook": "https://www.facebook.com/newyorkpresbyterian", "instagram": "https://www.instagram.com/nyphospital", "twitter": "https://x.com/nyphospital", "youtube": "https://www.youtube.com/user/newyorkpresbyterian", "linkedin": "https://www.linkedin.com/company/new-york-presbyterian-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=NewYork-Presbyterian%20Columbia%20University%20Irving%20Medical%20Center&go=Go"},
    {"rank": 18, "hospital": "Houston Methodist Hospital", "city": "Houston", "state": "Texas", "score": "84.21%", "website": "https://www.houstonmethodist.org/", "facebook": "https://www.facebook.com/houstonmethodist", "instagram": "https://www.instagram.com/houstonmethodist", "twitter": "https://x.com/hmethodistcares", "youtube": "https://www.youtube.com/@HoustonMethodist", "linkedin": "https://www.linkedin.com/company/houston-methodist", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Houston%20Methodist%20Hospital&go=Go"},
    {"rank": 19, "hospital": "NYU Langone Hospitals - Tisch Hospital", "city": "New York City", "state": "New York", "score": "83.14%", "website": "https://www.nyulangone.org/", "facebook": "https://www.facebook.com/NYULangone", "instagram": "https://www.instagram.com/nyulangone", "twitter": "https://x.com/nyulangone", "youtube": "https://www.youtube.com/c/NYULangoneHealth", "linkedin": "https://www.linkedin.com/company/nyulangonehealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=NYU%20Langone%20Hospitals%20-%20Tisch%20Hospital&go=Go"},
    {"rank": 20, "hospital": "Beth Israel Deaconess Medical Center", "city": "Boston", "state": "Massachusetts", "score": "81.65%", "website": "https://www.bidmc.org/", "facebook": "https://www.facebook.com/BIDMC", "instagram": "https://www.instagram.com/bidmchealth", "twitter": "https://x.com/BIDMChealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/beth-israel-deaconess-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Beth%20Israel%20Deaconess%20Medical%20Center&go=Go"},
    {"rank": 21, "hospital": "Vanderbilt University Medical Center", "city": "Nashville", "state": "Tennessee", "score": "81.19%", "website": "https://www.vanderbilthealth.com/", "facebook": "https://www.facebook.com/VanderbiltHealth", "instagram": "https://www.instagram.com/vanderbilthealth", "twitter": "https://x.com/VUMChealth", "youtube": "https://www.youtube.com/VanderbiltHealth", "linkedin": "https://www.linkedin.com/company/vanderbilt-university-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Vanderbilt%20University%20Medical%20Center&go=Go"},
    {"rank": 22, "hospital": "Rush University Medical Center", "city": "Chicago", "state": "Illinois", "score": "80.73%", "website": "https://www.rush.edu/", "facebook": "https://www.facebook.com/RushUniversityMedicalCenter", "instagram": "https://www.instagram.com/rushmedical", "twitter": "", "youtube": "https://www.youtube.com/user/rushmedicalcenter", "linkedin": "https://www.linkedin.com/company/rush-university-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Rush%20University%20Medical%20Center&go=Go"},
    {"rank": 23, "hospital": "University of Chicago Medical Center", "city": "Chicago", "state": "Illinois", "score": "80.23%", "website": "https://www.uchicagomedicine.org/", "facebook": "https://www.facebook.com/UChicagoMed", "instagram": "https://www.instagram.com/uchicagomed", "twitter": "https://x.com/uchicagomed", "youtube": "", "linkedin": "https://www.linkedin.com/company/university-of-chicago-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20Chicago%20Medical%20Center&go=Go"},
    {"rank": 24, "hospital": "UCLA Health - Santa Monica Medical Center", "city": "Santa Monica", "state": "California", "score": "79.69%", "website": "https://www.uclahealth.org/", "facebook": "https://www.facebook.com/uclahealth", "instagram": "https://www.instagram.com/uclahealth", "twitter": "https://x.com/uclahealth", "youtube": "https://www.youtube.com/uclahealth", "linkedin": "https://www.linkedin.com/company/ucla-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UCLA%20Health%20-%20Santa%20Monica%20Medical%20Center&go=Go"},
    {"rank": 25, "hospital": "Yale New Haven Hospital", "city": "New Haven", "state": "Connecticut", "score": "79.03%", "website": "https://www.ynhh.org/", "facebook": "https://www.facebook.com/ynhhs", "instagram": "https://www.instagram.com/yalenewhavenhealth", "twitter": "https://x.com/ynhhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/yale-new-haven-health-system", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Yale%20New%20Haven%20Hospital&go=Go"},
    {"rank": 26, "hospital": "NewYork-Presbyterian Weill Cornell Medical Center", "city": "New York City", "state": "New York", "score": "78.55%", "website": "https://www.nyp.org/", "facebook": "https://www.facebook.com/newyorkpresbyterian", "instagram": "https://www.instagram.com/nyphospital", "twitter": "https://x.com/nyphospital", "youtube": "https://www.youtube.com/user/newyorkpresbyterian", "linkedin": "https://www.linkedin.com/company/new-york-presbyterian-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=NewYork-Presbyterian%20Weill%20Cornell%20Medical%20Center&go=Go"},
    {"rank": 27, "hospital": "Barnes-Jewish Hospital", "city": "St. Louis", "state": "Missouri", "score": "78.09%", "website": "https://www.barnesjewish.org/", "facebook": "https://www.facebook.com/barnesjewishhospital", "instagram": "https://www.instagram.com/barnes_jewish", "twitter": "https://x.com/barnesjewish", "youtube": "", "linkedin": "https://www.linkedin.com/company/barnes-jewish-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Barnes-Jewish%20Hospital&go=Go"},
    {"rank": 28, "hospital": "Johns Hopkins Bayview Medical Center", "city": "Baltimore", "state": "Maryland", "score": "76.83%", "website": "https://www.hopkinsmedicine.org/", "facebook": "https://www.facebook.com/Johns.Hopkins.Medicine", "instagram": "https://www.instagram.com/hopkinsmedicine", "twitter": "https://x.com/HopkinsMedicine", "youtube": "https://www.youtube.com/user/JohnsHopkinsMedicine", "linkedin": "https://www.linkedin.com/company/johns-hopkins-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Johns%20Hopkins%20Bayview%20Medical%20Center&go=Go"},
    {"rank": 29, "hospital": "Emory University Hospital", "city": "Atlanta", "state": "Georgia", "score": "76.64%", "website": "https://www.emoryhealthcare.org/", "facebook": "https://www.facebook.com/EmoryHealthcare", "instagram": "https://www.instagram.com/emoryhealthcare", "twitter": "https://x.com/emoryhealthcare", "youtube": "https://www.youtube.com/@emoryhealthcare", "linkedin": "https://www.linkedin.com/company/emory-healthcare", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Emory%20University%20Hospital&go=Go"},
    {"rank": 30, "hospital": "Keck Hospital of USC", "city": "Los Angeles", "state": "California", "score": "76.53%", "website": "https://www.keckmedicine.org/", "facebook": "https://www.facebook.com/KeckMedUSC", "instagram": "https://www.instagram.com/keckmedicineusc", "twitter": "https://x.com/KeckMedicineUSC", "youtube": "https://www.youtube.com/user/KeckMedUSC", "linkedin": "https://www.linkedin.com/company/keck-medicine-of-usc", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Keck%20Hospital%20of%20USC&go=Go"},
    {"rank": 31, "hospital": "UW Health - University Hospital", "city": "Madison", "state": "Wisconsin", "score": "74.90%", "website": "https://www.uwhealth.org/", "facebook": "https://www.facebook.com/uwhealth", "instagram": "https://www.instagram.com/uw_health", "twitter": "https://x.com/uwhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/uw-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UW%20Health%20-%20University%20Hospital&go=Go"},
    {"rank": 32, "hospital": "University of Washington Medical Center", "city": "Seattle", "state": "Washington", "score": "73.46%", "website": "https://www.uwmedicine.org/", "facebook": "https://www.facebook.com/UWMedicine", "instagram": "https://www.instagram.com/uwmedicine", "twitter": "https://x.com/UWMedicine", "youtube": "https://www.youtube.com/uwmedicinehealth", "linkedin": "https://www.linkedin.com/company/uw-medicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20Washington%20Medical%20Center&go=Go"},
    {"rank": 33, "hospital": "Jacobs Medical Center at UC San Diego Health", "city": "San Diego", "state": "California", "score": "73.21%", "website": "https://health.ucsd.edu/", "facebook": "https://www.facebook.com/UCSDHealth", "instagram": "https://www.instagram.com/ucsdhealth", "twitter": "https://x.com/UCSDHealth", "youtube": "https://www.youtube.com/@UCSDHealth", "linkedin": "https://www.linkedin.com/company/ucsdhealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Jacobs%20Medical%20Center%20at%20UC%20San%20Diego%20Health&go=Go"},
    {"rank": 34, "hospital": "Virginia Mason Medical Center", "city": "Seattle", "state": "Washington", "score": "72.92%", "website": "https://www.vmfh.org/", "facebook": "https://www.facebook.com/VirginiaMasonFranciscanHealth", "instagram": "https://www.instagram.com/virginiamasonfranciscanhealth", "twitter": "https://x.com/VMFHealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/virginiamasonfranciscanhealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Virginia%20Mason%20Medical%20Center&go=Go"},
    {"rank": 35, "hospital": "University of California Davis Medical Center", "city": "Sacramento", "state": "California", "score": "72.72%", "website": "https://www.health.ucdavis.edu/", "facebook": "https://www.facebook.com/UCDavisHealth", "instagram": "https://www.instagram.com/ucdavishealth", "twitter": "https://x.com/UCDavisHealth", "youtube": "https://www.youtube.com/ucdavishealth", "linkedin": "https://www.linkedin.com/company/ucdavishealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20California%20Davis%20Medical%20Center&go=Go"},
    {"rank": 36, "hospital": "Cleveland Clinic - Fairview Hospital", "city": "Cleveland", "state": "Ohio", "score": "72.30%", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Cleveland%20Clinic%20-%20Fairview%20Hospital&go=Go"},
    {"rank": 37, "hospital": "Ohio State University - Wexner Medical Center", "city": "Columbus", "state": "Ohio", "score": "72.18%", "website": "https://www.wexnermedical.osu.edu/", "facebook": "https://www.facebook.com/OSUWexnerMedicalCenter", "instagram": "https://www.instagram.com/osuwexmed", "twitter": "https://x.com/OSUWexMed", "youtube": "https://www.youtube.com/@OSUWexMed", "linkedin": "https://www.linkedin.com/company/the-ohio-state-university-wexner-medical-center", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Ohio%20State%20University%20-%20Wexner%20Medical%20Center&go=Go"},
    {"rank": 38, "hospital": "UT Southwestern Medical Center", "city": "Dallas", "state": "Texas", "score": "72.17%", "website": "https://www.utsouthwestern.edu/", "facebook": "https://www.facebook.com/utswmed", "instagram": "https://www.instagram.com/utswmedcenter", "twitter": "https://x.com/UTSWMedCenter", "youtube": "https://www.youtube.com/utswmed", "linkedin": "", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UT%20Southwestern%20Medical%20Center&go=Go"},
    {"rank": 39, "hospital": "Thomas Jefferson University Hospital", "city": "Philadelphia", "state": "Pennsylvania", "score": "72.16%", "website": "https://www.jeffersonhealth.org/", "facebook": "https://www.facebook.com/jeffersonhealth", "instagram": "https://www.instagram.com/jeffersonhealth", "twitter": "https://x.com/JeffersonHealth", "youtube": "https://www.youtube.com/@jeffersonhealth", "linkedin": "https://www.linkedin.com/company/thomas-jefferson-university-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Thomas%20Jefferson%20University%20Hospital&go=Go"},
    {"rank": 40, "hospital": "Cleveland Clinic Weston Hospital", "city": "Weston", "state": "Florida", "score": "72.13%", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Cleveland%20Clinic%20Weston%20Hospital&go=Go"},
    {"rank": 41, "hospital": "Brigham and Women's Faulkner Hospital", "city": "Boston", "state": "Massachusetts", "score": "71.94%", "website": "https://www.brighamandwomensfaulkner.org/", "facebook": "https://www.facebook.com/BrighamandWomensHospital", "instagram": "https://www.instagram.com/brighamandwomens", "twitter": "https://x.com/BrighamWomens", "youtube": "https://www.youtube.com/brighamandwomens", "linkedin": "https://www.linkedin.com/company/brigham-and-womens-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Brigham%20and%20Women%27s%20Faulkner%20Hospital&go=Go"},
    {"rank": 42, "hospital": "University of Kansas Hospital", "city": "Kansas City", "state": "Kansas", "score": "71.77%", "website": "https://www.kansashealthsystem.com/", "facebook": "https://www.facebook.com/kuhospital", "instagram": "https://www.instagram.com/kuhospital", "twitter": "https://x.com/kuhospital", "youtube": "https://www.youtube.com/user/KUHospital", "linkedin": "https://www.linkedin.com/company/the-university-of-kansas-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20Kansas%20Hospital&go=Go"},
    {"rank": 43, "hospital": "UCHealth University of Colorado Hospital", "city": "Aurora", "state": "Colorado", "score": "71.71%", "website": "https://www.uchealth.org/", "facebook": "https://www.facebook.com/uchealthorg", "instagram": "https://www.instagram.com/uchealth", "twitter": "https://x.com/uchealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/uchealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=UCHealth%20University%20of%20Colorado%20Hospital&go=Go"},
    {"rank": 44, "hospital": "University Hospitals Cleveland Medical Center", "city": "Cleveland", "state": "Ohio", "score": "71.65%", "website": "https://www.uhhospitals.org/", "facebook": "https://www.facebook.com/UniversityHospitals", "instagram": "https://www.instagram.com/uhhospitals_cle", "twitter": "https://x.com/UHhospitals", "youtube": "https://www.youtube.com/UniversityHospitals", "linkedin": "https://www.linkedin.com/company/university-hospitals", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20Hospitals%20Cleveland%20Medical%20Center&go=Go"},
    {"rank": 45, "hospital": "Scripps Memorial Hospital La Jolla", "city": "La Jolla", "state": "California", "score": "71.63%", "website": "https://www.scripps.org/", "facebook": "https://www.facebook.com/scrippshealth", "instagram": "https://www.instagram.com/scrippshealth", "twitter": "https://x.com/ScrippsHealth", "youtube": "https://www.youtube.com/user/ScrippsHealth", "linkedin": "https://www.linkedin.com/company/scripps-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Scripps%20Memorial%20Hospital%20La%20Jolla&go=Go"},
    {"rank": 46, "hospital": "Baylor St. Luke's Medical Center", "city": "Houston", "state": "Texas", "score": "71.33%", "website": "https://www.stlukeshealth.org/", "facebook": "https://www.facebook.com/StLukesHealthTX", "instagram": "https://www.instagram.com/stlukeshealthtx", "twitter": "https://x.com/StLukesHealthTX", "youtube": "", "linkedin": "https://www.linkedin.com/company/st-lukes-health", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Baylor%20St.%20Luke%27s%20Medical%20Center&go=Go"},
    {"rank": 47, "hospital": "University of Utah Hospital", "city": "Salt Lake City", "state": "Utah", "score": "71.23%", "website": "https://www.healthcare.utah.edu/", "facebook": "https://www.facebook.com/UofUHealth", "instagram": "https://www.instagram.com/uofuhealth", "twitter": "https://x.com/UofUHealth", "youtube": "https://www.youtube.com/c/UofUHealthCare", "linkedin": "https://www.linkedin.com/company/university-of-utah-hospital", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=University%20of%20Utah%20Hospital&go=Go"},
    {"rank": 48, "hospital": "Penn State Health - Milton S. Hershey Medical Center", "city": "Hershey", "state": "Pennsylvania", "score": "71.14%", "website": "https://www.pennstatehealth.org/", "facebook": "https://www.facebook.com/pennstatehealth", "instagram": "https://www.instagram.com/pennstatehealth", "twitter": "https://x.com/pennstatehealth", "youtube": "https://www.youtube.com/c/PennStateHealth", "linkedin": "https://www.linkedin.com/company/pennstatehealth", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Penn%20State%20Health%20-%20Milton%20S.%20Hershey%20Medical%20Center&go=Go"},
    {"rank": 49, "hospital": "Tufts Medical Center", "city": "Boston", "state": "Massachusetts", "score": "71.07%", "website": "https://www.tuftsmedicine.org/", "facebook": "https://www.facebook.com/tuftsmedicine", "instagram": "https://www.instagram.com/tuftsmedicine", "twitter": "https://x.com/TuftsMedicine", "youtube": "https://www.youtube.com/@tuftsmedicine", "linkedin": "https://www.linkedin.com/company/tuftsmedicine", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Tufts%20Medical%20Center&go=Go"},
    {"rank": 50, "hospital": "Torrance Memorial Medical Center", "city": "Torrance", "state": "California", "score": "71.04%", "website": "https://www.torrancememorial.org/", "facebook": "https://www.facebook.com/torrancememorial", "instagram": "", "twitter": "https://x.com/TMHealthSystem", "youtube": "https://www.youtube.com/c/TorranceMemorialMedicalCenter", "linkedin": "https://www.linkedin.com/company/torrancememorial", "wikipedia": "https://en.wikipedia.org/wiki/Special:Search?search=Torrance%20Memorial%20Medical%20Center&go=Go"},
]
