"""
Baked-in best-hospital reference data (United States): website + official socials.

Versioned yearly snapshot served by the app (the ranking sites are JS-rendered,
so a hosted scrape is unreliable). Refresh by editing this file each year.
Social handles are official system-level accounts; blank where not verifiable.

Sources:
- U.S. News & World Report - Best Hospitals 2025-2026 Honor Roll (non-ordinal).
  https://health.usnews.com/health-care/best-hospitals/articles/best-hospitals-honor-roll-and-overview
- Newsweek / Statista - World's Best Hospitals 2026, United States.
  https://rankings.newsweek.com/worlds-best-hospitals-2026/united-states
"""

US_NEWS_EDITION = "2025-2026"
US_NEWS_SOURCE_URL = (
    "https://health.usnews.com/health-care/best-hospitals/articles/"
    "best-hospitals-honor-roll-and-overview"
)

US_NEWS_HONOR_ROLL = [
    {"hospital": "Mayo Clinic-Arizona", "city": "Phoenix", "state": "Arizona", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic"},
    {"hospital": "Cedars-Sinai Medical Center", "city": "Los Angeles", "state": "California", "website": "https://www.cedars-sinai.org/", "facebook": "https://www.facebook.com/CedarsSinai", "instagram": "https://www.instagram.com/cedarssinai", "twitter": "https://x.com/CedarsSinai", "youtube": "https://www.youtube.com/user/CEDARSSINAI", "linkedin": "https://www.linkedin.com/company/cedars-sinai-medical-center"},
    {"hospital": "Stanford Health Care-Stanford Hospital", "city": "Palo Alto", "state": "California", "website": "https://www.stanfordhealthcare.org/", "facebook": "https://www.facebook.com/StanfordHealthCare", "instagram": "https://www.instagram.com/stanford.healthcare", "twitter": "https://x.com/StanfordHealth", "youtube": "https://www.youtube.com/@StanfordHospital", "linkedin": "https://www.linkedin.com/company/stanford-health-care"},
    {"hospital": "UCLA Medical Center", "city": "Los Angeles", "state": "California", "website": "https://www.uclahealth.org/", "facebook": "https://www.facebook.com/uclahealth", "instagram": "https://www.instagram.com/uclahealth", "twitter": "https://x.com/uclahealth", "youtube": "https://www.youtube.com/uclahealth", "linkedin": "https://www.linkedin.com/company/ucla-health"},
    {"hospital": "UCSF Health-UCSF Medical Center", "city": "San Francisco", "state": "California", "website": "https://www.ucsfhealth.org/", "facebook": "https://www.facebook.com/UCSFMedicalCenter", "instagram": "https://www.instagram.com/ucsfhealth", "twitter": "https://x.com/ucsfhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/ucsfhealth"},
    {"hospital": "AdventHealth Orlando", "city": "Orlando", "state": "Florida", "website": "https://www.adventhealth.com/", "facebook": "https://www.facebook.com/AdventHealth", "instagram": "https://www.instagram.com/adventhealth", "twitter": "https://x.com/AdventHealth", "youtube": "https://www.youtube.com/@AdventHealth", "linkedin": "https://www.linkedin.com/company/adventhealth"},
    {"hospital": "Northwestern Medicine-Northwestern Memorial Hospital", "city": "Chicago", "state": "Illinois", "website": "https://www.nm.org/", "facebook": "https://www.facebook.com/northwesternmedicine", "instagram": "https://www.instagram.com/northwesternmedicine", "twitter": "https://x.com/NorthwesternMed", "youtube": "https://www.youtube.com/user/NMHChicago", "linkedin": "https://www.linkedin.com/company/northwestern-medicine"},
    {"hospital": "Rush University Medical Center", "city": "Chicago", "state": "Illinois", "website": "https://www.rush.edu/", "facebook": "https://www.facebook.com/RushUniversityMedicalCenter", "instagram": "https://www.instagram.com/rushmedical", "twitter": "", "youtube": "https://www.youtube.com/user/rushmedicalcenter", "linkedin": "https://www.linkedin.com/company/rush-university-medical-center"},
    {"hospital": "Johns Hopkins Hospital", "city": "Baltimore", "state": "Maryland", "website": "https://www.hopkinsmedicine.org/", "facebook": "https://www.facebook.com/Johns.Hopkins.Medicine", "instagram": "https://www.instagram.com/hopkinsmedicine", "twitter": "https://x.com/HopkinsMedicine", "youtube": "https://www.youtube.com/user/JohnsHopkinsMedicine", "linkedin": "https://www.linkedin.com/company/johns-hopkins-medicine"},
    {"hospital": "Brigham and Women's Hospital", "city": "Boston", "state": "Massachusetts", "website": "https://www.brighamandwomens.org/", "facebook": "https://www.facebook.com/BrighamandWomensHospital", "instagram": "https://www.instagram.com/brighamandwomens", "twitter": "https://x.com/BrighamWomens", "youtube": "https://www.youtube.com/brighamandwomens", "linkedin": "https://www.linkedin.com/company/brigham-and-womens-hospital"},
    {"hospital": "Massachusetts General Hospital", "city": "Boston", "state": "Massachusetts", "website": "https://www.massgeneral.org/", "facebook": "https://www.facebook.com/massgeneral", "instagram": "https://www.instagram.com/massgeneral", "twitter": "https://x.com/MassGeneralNews", "youtube": "", "linkedin": "https://www.linkedin.com/company/massachusetts-general-hospital"},
    {"hospital": "University of Michigan Health", "city": "Ann Arbor", "state": "Michigan", "website": "https://www.uofmhealth.org/", "facebook": "https://www.facebook.com/MichiganMedicine", "instagram": "https://www.instagram.com/umichmedicine", "twitter": "https://x.com/umichmedicine", "youtube": "", "linkedin": "https://www.linkedin.com/company/michigan-medicine"},
    {"hospital": "Mayo Clinic-Rochester", "city": "Rochester", "state": "Minnesota", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic"},
    {"hospital": "Hackensack University Medical Center at Hackensack Meridian Health", "city": "Hackensack", "state": "New Jersey", "website": "https://www.hackensackmeridianhealth.org/", "facebook": "https://www.facebook.com/HackensackMeridianHealth", "instagram": "https://www.instagram.com/hmhnewjersey", "twitter": "https://x.com/HMHNewJersey", "youtube": "https://www.youtube.com/channel/UCGNz3pc9coZmYxUuLFJSKtQ", "linkedin": "https://www.linkedin.com/company/hackensackmeridianhealth"},
    {"hospital": "Mount Sinai Hospital", "city": "New York City", "state": "New York", "website": "https://www.mountsinai.org/", "facebook": "https://www.facebook.com/MountSinaiNYC", "instagram": "https://www.instagram.com/mountsinainyc", "twitter": "https://x.com/MountSinaiNYC", "youtube": "https://www.youtube.com/user/MountSinaiNY", "linkedin": "https://www.linkedin.com/company/mountsinainyc"},
    {"hospital": "New York-Presbyterian Hospital-Columbia and Cornell", "city": "New York City", "state": "New York", "website": "https://www.nyp.org/", "facebook": "https://www.facebook.com/newyorkpresbyterian", "instagram": "https://www.instagram.com/nyphospital", "twitter": "https://x.com/nyphospital", "youtube": "https://www.youtube.com/user/newyorkpresbyterian", "linkedin": "https://www.linkedin.com/company/new-york-presbyterian-hospital"},
    {"hospital": "NYU Langone Hospitals", "city": "New York City", "state": "New York", "website": "https://www.nyulangone.org/", "facebook": "https://www.facebook.com/NYULangone", "instagram": "https://www.instagram.com/nyulangone", "twitter": "https://x.com/nyulangone", "youtube": "https://www.youtube.com/c/NYULangoneHealth", "linkedin": "https://www.linkedin.com/company/nyulangonehealth"},
    {"hospital": "Cleveland Clinic", "city": "Cleveland", "state": "Ohio", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic"},
    {"hospital": "Hospitals of the University of Pennsylvania-Penn Presbyterian", "city": "Philadelphia", "state": "Pennsylvania", "website": "https://www.pennmedicine.org/", "facebook": "https://www.facebook.com/pennmed", "instagram": "https://www.instagram.com/pennmedicine", "twitter": "https://x.com/PennMedicine", "youtube": "https://www.youtube.com/pennmedicine", "linkedin": "https://www.linkedin.com/company/university-of-pennsylvania-health-system"},
    {"hospital": "Houston Methodist Hospital", "city": "Houston", "state": "Texas", "website": "https://www.houstonmethodist.org/", "facebook": "https://www.facebook.com/houstonmethodist", "instagram": "https://www.instagram.com/houstonmethodist", "twitter": "https://x.com/hmethodistcares", "youtube": "https://www.youtube.com/@HoustonMethodist", "linkedin": "https://www.linkedin.com/company/houston-methodist"},
]

NEWSWEEK_EDITION = "2026"
NEWSWEEK_SOURCE_URL = "https://rankings.newsweek.com/worlds-best-hospitals-2026/united-states"

NEWSWEEK_US = [
    {"rank": 1, "hospital": "Mayo Clinic - Rochester", "city": "Rochester", "state": "Minnesota", "score": "96.28%", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic"},
    {"rank": 2, "hospital": "Cleveland Clinic", "city": "Cleveland", "state": "Ohio", "score": "92.13%", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic"},
    {"rank": 3, "hospital": "Massachusetts General Hospital", "city": "Boston", "state": "Massachusetts", "score": "91.96%", "website": "https://www.massgeneral.org/", "facebook": "https://www.facebook.com/massgeneral", "instagram": "https://www.instagram.com/massgeneral", "twitter": "https://x.com/MassGeneralNews", "youtube": "", "linkedin": "https://www.linkedin.com/company/massachusetts-general-hospital"},
    {"rank": 4, "hospital": "The Johns Hopkins Hospital", "city": "Baltimore", "state": "Maryland", "score": "89.77%", "website": "https://www.hopkinsmedicine.org/", "facebook": "https://www.facebook.com/Johns.Hopkins.Medicine", "instagram": "https://www.instagram.com/hopkinsmedicine", "twitter": "https://x.com/HopkinsMedicine", "youtube": "https://www.youtube.com/user/JohnsHopkinsMedicine", "linkedin": "https://www.linkedin.com/company/johns-hopkins-medicine"},
    {"rank": 5, "hospital": "Ronald Reagan UCLA Medical Center", "city": "Los Angeles", "state": "California", "score": "89.68%", "website": "https://www.uclahealth.org/", "facebook": "https://www.facebook.com/uclahealth", "instagram": "https://www.instagram.com/uclahealth", "twitter": "https://x.com/uclahealth", "youtube": "https://www.youtube.com/uclahealth", "linkedin": "https://www.linkedin.com/company/ucla-health"},
    {"rank": 6, "hospital": "Brigham and Women's Hospital", "city": "Boston", "state": "Massachusetts", "score": "89.64%", "website": "https://www.brighamandwomens.org/", "facebook": "https://www.facebook.com/BrighamandWomensHospital", "instagram": "https://www.instagram.com/brighamandwomens", "twitter": "https://x.com/BrighamWomens", "youtube": "https://www.youtube.com/brighamandwomens", "linkedin": "https://www.linkedin.com/company/brigham-and-womens-hospital"},
    {"rank": 7, "hospital": "The Mount Sinai Hospital", "city": "New York City", "state": "New York", "score": "88.37%", "website": "https://www.mountsinai.org/", "facebook": "https://www.facebook.com/MountSinaiNYC", "instagram": "https://www.instagram.com/mountsinainyc", "twitter": "https://x.com/MountSinaiNYC", "youtube": "https://www.youtube.com/user/MountSinaiNY", "linkedin": "https://www.linkedin.com/company/mountsinainyc"},
    {"rank": 8, "hospital": "Stanford Health Care - Stanford Hospital", "city": "Stanford", "state": "California", "score": "88.19%", "website": "https://www.stanfordhealthcare.org/", "facebook": "https://www.facebook.com/StanfordHealthCare", "instagram": "https://www.instagram.com/stanford.healthcare", "twitter": "https://x.com/StanfordHealth", "youtube": "https://www.youtube.com/@StanfordHospital", "linkedin": "https://www.linkedin.com/company/stanford-health-care"},
    {"rank": 9, "hospital": "UCSF Medical Center", "city": "San Francisco", "state": "California", "score": "86.77%", "website": "https://www.ucsfhealth.org/", "facebook": "https://www.facebook.com/UCSFMedicalCenter", "instagram": "https://www.instagram.com/ucsfhealth", "twitter": "https://x.com/ucsfhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/ucsfhealth"},
    {"rank": 10, "hospital": "Cedars-Sinai Medical Center", "city": "Los Angeles", "state": "California", "score": "86.73%", "website": "https://www.cedars-sinai.org/", "facebook": "https://www.facebook.com/CedarsSinai", "instagram": "https://www.instagram.com/cedarssinai", "twitter": "https://x.com/CedarsSinai", "youtube": "https://www.youtube.com/user/CEDARSSINAI", "linkedin": "https://www.linkedin.com/company/cedars-sinai-medical-center"},
    {"rank": 11, "hospital": "Mayo Clinic - Jacksonville", "city": "Jacksonville", "state": "Florida", "score": "86.69%", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic"},
    {"rank": 12, "hospital": "University of Michigan Health - Ann Arbor", "city": "Ann Arbor", "state": "Michigan", "score": "86.59%", "website": "https://www.uofmhealth.org/", "facebook": "https://www.facebook.com/MichiganMedicine", "instagram": "https://www.instagram.com/umichmedicine", "twitter": "https://x.com/umichmedicine", "youtube": "", "linkedin": "https://www.linkedin.com/company/michigan-medicine"},
    {"rank": 13, "hospital": "Northwestern Memorial Hospital", "city": "Chicago", "state": "Illinois", "score": "86.33%", "website": "https://www.nm.org/", "facebook": "https://www.facebook.com/northwesternmedicine", "instagram": "https://www.instagram.com/northwesternmedicine", "twitter": "https://x.com/NorthwesternMed", "youtube": "https://www.youtube.com/user/NMHChicago", "linkedin": "https://www.linkedin.com/company/northwestern-medicine"},
    {"rank": 14, "hospital": "Duke University Hospital", "city": "Durham", "state": "North Carolina", "score": "86.13%", "website": "https://www.dukehealth.org/", "facebook": "https://www.facebook.com/dukehealth", "instagram": "https://www.instagram.com/dukehealth", "twitter": "https://x.com/DukeHealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/duke-health"},
    {"rank": 15, "hospital": "Hospital of the University of Pennsylvania", "city": "Philadelphia", "state": "Pennsylvania", "score": "85.78%", "website": "https://www.pennmedicine.org/", "facebook": "https://www.facebook.com/pennmed", "instagram": "https://www.instagram.com/pennmedicine", "twitter": "https://x.com/PennMedicine", "youtube": "https://www.youtube.com/pennmedicine", "linkedin": "https://www.linkedin.com/company/university-of-pennsylvania-health-system"},
    {"rank": 16, "hospital": "Mayo Clinic - Phoenix", "city": "Phoenix", "state": "Arizona", "score": "84.71%", "website": "https://www.mayoclinic.org/", "facebook": "https://www.facebook.com/MayoClinic", "instagram": "https://www.instagram.com/mayoclinic", "twitter": "https://x.com/MayoClinic", "youtube": "https://www.youtube.com/user/mayoclinic", "linkedin": "https://www.linkedin.com/company/mayo-clinic"},
    {"rank": 17, "hospital": "NewYork-Presbyterian Columbia University Irving Medical Center", "city": "New York City", "state": "New York", "score": "84.22%", "website": "https://www.nyp.org/", "facebook": "https://www.facebook.com/newyorkpresbyterian", "instagram": "https://www.instagram.com/nyphospital", "twitter": "https://x.com/nyphospital", "youtube": "https://www.youtube.com/user/newyorkpresbyterian", "linkedin": "https://www.linkedin.com/company/new-york-presbyterian-hospital"},
    {"rank": 18, "hospital": "Houston Methodist Hospital", "city": "Houston", "state": "Texas", "score": "84.21%", "website": "https://www.houstonmethodist.org/", "facebook": "https://www.facebook.com/houstonmethodist", "instagram": "https://www.instagram.com/houstonmethodist", "twitter": "https://x.com/hmethodistcares", "youtube": "https://www.youtube.com/@HoustonMethodist", "linkedin": "https://www.linkedin.com/company/houston-methodist"},
    {"rank": 19, "hospital": "NYU Langone Hospitals - Tisch Hospital", "city": "New York City", "state": "New York", "score": "83.14%", "website": "https://www.nyulangone.org/", "facebook": "https://www.facebook.com/NYULangone", "instagram": "https://www.instagram.com/nyulangone", "twitter": "https://x.com/nyulangone", "youtube": "https://www.youtube.com/c/NYULangoneHealth", "linkedin": "https://www.linkedin.com/company/nyulangonehealth"},
    {"rank": 20, "hospital": "Beth Israel Deaconess Medical Center", "city": "Boston", "state": "Massachusetts", "score": "81.65%", "website": "https://www.bidmc.org/", "facebook": "https://www.facebook.com/BIDMC", "instagram": "https://www.instagram.com/bidmchealth", "twitter": "https://x.com/BIDMChealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/beth-israel-deaconess-medical-center"},
    {"rank": 21, "hospital": "Vanderbilt University Medical Center", "city": "Nashville", "state": "Tennessee", "score": "81.19%", "website": "https://www.vanderbilthealth.com/", "facebook": "https://www.facebook.com/VanderbiltHealth", "instagram": "https://www.instagram.com/vanderbilthealth", "twitter": "https://x.com/VUMChealth", "youtube": "https://www.youtube.com/VanderbiltHealth", "linkedin": "https://www.linkedin.com/company/vanderbilt-university-medical-center"},
    {"rank": 22, "hospital": "Rush University Medical Center", "city": "Chicago", "state": "Illinois", "score": "80.73%", "website": "https://www.rush.edu/", "facebook": "https://www.facebook.com/RushUniversityMedicalCenter", "instagram": "https://www.instagram.com/rushmedical", "twitter": "", "youtube": "https://www.youtube.com/user/rushmedicalcenter", "linkedin": "https://www.linkedin.com/company/rush-university-medical-center"},
    {"rank": 23, "hospital": "University of Chicago Medical Center", "city": "Chicago", "state": "Illinois", "score": "80.23%", "website": "https://www.uchicagomedicine.org/", "facebook": "https://www.facebook.com/UChicagoMed", "instagram": "https://www.instagram.com/uchicagomed", "twitter": "https://x.com/uchicagomed", "youtube": "", "linkedin": "https://www.linkedin.com/company/university-of-chicago-medicine"},
    {"rank": 24, "hospital": "UCLA Health - Santa Monica Medical Center", "city": "Santa Monica", "state": "California", "score": "79.69%", "website": "https://www.uclahealth.org/", "facebook": "https://www.facebook.com/uclahealth", "instagram": "https://www.instagram.com/uclahealth", "twitter": "https://x.com/uclahealth", "youtube": "https://www.youtube.com/uclahealth", "linkedin": "https://www.linkedin.com/company/ucla-health"},
    {"rank": 25, "hospital": "Yale New Haven Hospital", "city": "New Haven", "state": "Connecticut", "score": "79.03%", "website": "https://www.ynhh.org/", "facebook": "https://www.facebook.com/ynhhs", "instagram": "https://www.instagram.com/yalenewhavenhealth", "twitter": "https://x.com/ynhhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/yale-new-haven-health-system"},
    {"rank": 26, "hospital": "NewYork-Presbyterian Weill Cornell Medical Center", "city": "New York City", "state": "New York", "score": "78.55%", "website": "https://www.nyp.org/", "facebook": "https://www.facebook.com/newyorkpresbyterian", "instagram": "https://www.instagram.com/nyphospital", "twitter": "https://x.com/nyphospital", "youtube": "https://www.youtube.com/user/newyorkpresbyterian", "linkedin": "https://www.linkedin.com/company/new-york-presbyterian-hospital"},
    {"rank": 27, "hospital": "Barnes-Jewish Hospital", "city": "St. Louis", "state": "Missouri", "score": "78.09%", "website": "https://www.barnesjewish.org/", "facebook": "https://www.facebook.com/barnesjewishhospital", "instagram": "https://www.instagram.com/barnes_jewish", "twitter": "https://x.com/barnesjewish", "youtube": "", "linkedin": "https://www.linkedin.com/company/barnes-jewish-hospital"},
    {"rank": 28, "hospital": "Johns Hopkins Bayview Medical Center", "city": "Baltimore", "state": "Maryland", "score": "76.83%", "website": "https://www.hopkinsmedicine.org/", "facebook": "https://www.facebook.com/Johns.Hopkins.Medicine", "instagram": "https://www.instagram.com/hopkinsmedicine", "twitter": "https://x.com/HopkinsMedicine", "youtube": "https://www.youtube.com/user/JohnsHopkinsMedicine", "linkedin": "https://www.linkedin.com/company/johns-hopkins-medicine"},
    {"rank": 29, "hospital": "Emory University Hospital", "city": "Atlanta", "state": "Georgia", "score": "76.64%", "website": "https://www.emoryhealthcare.org/", "facebook": "https://www.facebook.com/EmoryHealthcare", "instagram": "https://www.instagram.com/emoryhealthcare", "twitter": "https://x.com/emoryhealthcare", "youtube": "https://www.youtube.com/@emoryhealthcare", "linkedin": "https://www.linkedin.com/company/emory-healthcare"},
    {"rank": 30, "hospital": "Keck Hospital of USC", "city": "Los Angeles", "state": "California", "score": "76.53%", "website": "https://www.keckmedicine.org/", "facebook": "https://www.facebook.com/KeckMedUSC", "instagram": "https://www.instagram.com/keckmedicineusc", "twitter": "https://x.com/KeckMedicineUSC", "youtube": "https://www.youtube.com/user/KeckMedUSC", "linkedin": "https://www.linkedin.com/company/keck-medicine-of-usc"},
    {"rank": 31, "hospital": "UW Health - University Hospital", "city": "Madison", "state": "Wisconsin", "score": "74.90%", "website": "https://www.uwhealth.org/", "facebook": "https://www.facebook.com/uwhealth", "instagram": "https://www.instagram.com/uw_health", "twitter": "https://x.com/uwhealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/uw-health"},
    {"rank": 32, "hospital": "University of Washington Medical Center", "city": "Seattle", "state": "Washington", "score": "73.46%", "website": "https://www.uwmedicine.org/", "facebook": "https://www.facebook.com/UWMedicine", "instagram": "https://www.instagram.com/uwmedicine", "twitter": "https://x.com/UWMedicine", "youtube": "https://www.youtube.com/uwmedicinehealth", "linkedin": "https://www.linkedin.com/company/uw-medicine"},
    {"rank": 33, "hospital": "Jacobs Medical Center at UC San Diego Health", "city": "San Diego", "state": "California", "score": "73.21%", "website": "https://health.ucsd.edu/", "facebook": "https://www.facebook.com/UCSDHealth", "instagram": "https://www.instagram.com/ucsdhealth", "twitter": "https://x.com/UCSDHealth", "youtube": "https://www.youtube.com/@UCSDHealth", "linkedin": "https://www.linkedin.com/company/ucsdhealth"},
    {"rank": 34, "hospital": "Virginia Mason Medical Center", "city": "Seattle", "state": "Washington", "score": "72.92%", "website": "https://www.vmfh.org/", "facebook": "https://www.facebook.com/VirginiaMasonFranciscanHealth", "instagram": "https://www.instagram.com/virginiamasonfranciscanhealth", "twitter": "https://x.com/VMFHealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/virginiamasonfranciscanhealth"},
    {"rank": 35, "hospital": "University of California Davis Medical Center", "city": "Sacramento", "state": "California", "score": "72.72%", "website": "https://www.health.ucdavis.edu/", "facebook": "https://www.facebook.com/UCDavisHealth", "instagram": "https://www.instagram.com/ucdavishealth", "twitter": "https://x.com/UCDavisHealth", "youtube": "https://www.youtube.com/ucdavishealth", "linkedin": "https://www.linkedin.com/company/ucdavishealth"},
    {"rank": 36, "hospital": "Cleveland Clinic - Fairview Hospital", "city": "Cleveland", "state": "Ohio", "score": "72.30%", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic"},
    {"rank": 37, "hospital": "Ohio State University - Wexner Medical Center", "city": "Columbus", "state": "Ohio", "score": "72.18%", "website": "https://www.wexnermedical.osu.edu/", "facebook": "https://www.facebook.com/OSUWexnerMedicalCenter", "instagram": "https://www.instagram.com/osuwexmed", "twitter": "https://x.com/OSUWexMed", "youtube": "https://www.youtube.com/@OSUWexMed", "linkedin": "https://www.linkedin.com/company/the-ohio-state-university-wexner-medical-center"},
    {"rank": 38, "hospital": "UT Southwestern Medical Center", "city": "Dallas", "state": "Texas", "score": "72.17%", "website": "https://www.utsouthwestern.edu/", "facebook": "https://www.facebook.com/utswmed", "instagram": "https://www.instagram.com/utswmedcenter", "twitter": "https://x.com/UTSWMedCenter", "youtube": "https://www.youtube.com/utswmed", "linkedin": ""},
    {"rank": 39, "hospital": "Thomas Jefferson University Hospital", "city": "Philadelphia", "state": "Pennsylvania", "score": "72.16%", "website": "https://www.jeffersonhealth.org/", "facebook": "https://www.facebook.com/jeffersonhealth", "instagram": "https://www.instagram.com/jeffersonhealth", "twitter": "https://x.com/JeffersonHealth", "youtube": "https://www.youtube.com/@jeffersonhealth", "linkedin": "https://www.linkedin.com/company/thomas-jefferson-university-hospital"},
    {"rank": 40, "hospital": "Cleveland Clinic Weston Hospital", "city": "Weston", "state": "Florida", "score": "72.13%", "website": "https://my.clevelandclinic.org/", "facebook": "https://www.facebook.com/clevelandclinic", "instagram": "https://www.instagram.com/clevelandclinic", "twitter": "https://x.com/ClevelandClinic", "youtube": "https://www.youtube.com/user/ClevelandClinic", "linkedin": "https://www.linkedin.com/company/cleveland-clinic"},
    {"rank": 41, "hospital": "Brigham and Women's Faulkner Hospital", "city": "Boston", "state": "Massachusetts", "score": "71.94%", "website": "https://www.brighamandwomensfaulkner.org/", "facebook": "https://www.facebook.com/BrighamandWomensHospital", "instagram": "https://www.instagram.com/brighamandwomens", "twitter": "https://x.com/BrighamWomens", "youtube": "https://www.youtube.com/brighamandwomens", "linkedin": "https://www.linkedin.com/company/brigham-and-womens-hospital"},
    {"rank": 42, "hospital": "University of Kansas Hospital", "city": "Kansas City", "state": "Kansas", "score": "71.77%", "website": "https://www.kansashealthsystem.com/", "facebook": "https://www.facebook.com/kuhospital", "instagram": "https://www.instagram.com/kuhospital", "twitter": "https://x.com/kuhospital", "youtube": "https://www.youtube.com/user/KUHospital", "linkedin": "https://www.linkedin.com/company/the-university-of-kansas-hospital"},
    {"rank": 43, "hospital": "UCHealth University of Colorado Hospital", "city": "Aurora", "state": "Colorado", "score": "71.71%", "website": "https://www.uchealth.org/", "facebook": "https://www.facebook.com/uchealthorg", "instagram": "https://www.instagram.com/uchealth", "twitter": "https://x.com/uchealth", "youtube": "", "linkedin": "https://www.linkedin.com/company/uchealth"},
    {"rank": 44, "hospital": "University Hospitals Cleveland Medical Center", "city": "Cleveland", "state": "Ohio", "score": "71.65%", "website": "https://www.uhhospitals.org/", "facebook": "https://www.facebook.com/UniversityHospitals", "instagram": "https://www.instagram.com/uhhospitals_cle", "twitter": "https://x.com/UHhospitals", "youtube": "https://www.youtube.com/UniversityHospitals", "linkedin": "https://www.linkedin.com/company/university-hospitals"},
    {"rank": 45, "hospital": "Scripps Memorial Hospital La Jolla", "city": "La Jolla", "state": "California", "score": "71.63%", "website": "https://www.scripps.org/", "facebook": "https://www.facebook.com/scrippshealth", "instagram": "https://www.instagram.com/scrippshealth", "twitter": "https://x.com/ScrippsHealth", "youtube": "https://www.youtube.com/user/ScrippsHealth", "linkedin": "https://www.linkedin.com/company/scripps-health"},
    {"rank": 46, "hospital": "Baylor St. Luke's Medical Center", "city": "Houston", "state": "Texas", "score": "71.33%", "website": "https://www.stlukeshealth.org/", "facebook": "https://www.facebook.com/StLukesHealthTX", "instagram": "https://www.instagram.com/stlukeshealthtx", "twitter": "https://x.com/StLukesHealthTX", "youtube": "", "linkedin": "https://www.linkedin.com/company/st-lukes-health"},
    {"rank": 47, "hospital": "University of Utah Hospital", "city": "Salt Lake City", "state": "Utah", "score": "71.23%", "website": "https://www.healthcare.utah.edu/", "facebook": "https://www.facebook.com/UofUHealth", "instagram": "https://www.instagram.com/uofuhealth", "twitter": "https://x.com/UofUHealth", "youtube": "https://www.youtube.com/c/UofUHealthCare", "linkedin": "https://www.linkedin.com/company/university-of-utah-hospital"},
    {"rank": 48, "hospital": "Penn State Health - Milton S. Hershey Medical Center", "city": "Hershey", "state": "Pennsylvania", "score": "71.14%", "website": "https://www.pennstatehealth.org/", "facebook": "https://www.facebook.com/pennstatehealth", "instagram": "https://www.instagram.com/pennstatehealth", "twitter": "https://x.com/pennstatehealth", "youtube": "https://www.youtube.com/c/PennStateHealth", "linkedin": "https://www.linkedin.com/company/pennstatehealth"},
    {"rank": 49, "hospital": "Tufts Medical Center", "city": "Boston", "state": "Massachusetts", "score": "71.07%", "website": "https://www.tuftsmedicine.org/", "facebook": "https://www.facebook.com/tuftsmedicine", "instagram": "https://www.instagram.com/tuftsmedicine", "twitter": "https://x.com/TuftsMedicine", "youtube": "https://www.youtube.com/@tuftsmedicine", "linkedin": "https://www.linkedin.com/company/tuftsmedicine"},
    {"rank": 50, "hospital": "Torrance Memorial Medical Center", "city": "Torrance", "state": "California", "score": "71.04%", "website": "https://www.torrancememorial.org/", "facebook": "https://www.facebook.com/torrancememorial", "instagram": "", "twitter": "https://x.com/TMHealthSystem", "youtube": "https://www.youtube.com/c/TorranceMemorialMedicalCenter", "linkedin": "https://www.linkedin.com/company/torrancememorial"},
]
