"""Professional sports leagues ranked by revenue. Source: Wikipedia
(List of professional sports leagues by revenue). Rank reflects the revenue
ordering on that page. Social links auto-generated from the league name;
Wikipedia links mapped where known, derived otherwise.

Source: https://en.wikipedia.org/wiki/List_of_professional_sports_leagues_by_revenue
"""

LEAGUEREV_EDITION = "Ranked by annual revenue"
LEAGUEREV_SOURCE_URL = "https://en.wikipedia.org/wiki/List_of_professional_sports_leagues_by_revenue"

LEAGUES_BY_REVENUE = [
    {"rank": 1, "league": "National Football League (NFL)", "sport": "American football", "country": "United States", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/National_Football_League"},
    {"rank": 2, "league": "Major League Baseball (MLB)", "sport": "Baseball", "country": "United States, Canada", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Major_League_Baseball"},
    {"rank": 4, "league": "Premier League (PL)", "sport": "Association football", "country": "England, Wales", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Premier_League"},
    {"rank": 5, "league": "National Hockey League (NHL)", "sport": "Ice hockey", "country": "Canada, United States", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/National_Hockey_League"},
    {"rank": 6, "league": "Campeonato Nacional de Liga de Primera División (La Liga)", "sport": "Association football", "country": "Spain", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/La_Liga"},
    {"rank": 11, "league": "Indian Premier League (IPL)", "sport": "Twenty20 cricket", "country": "India", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Indian_Premier_League"},
    {"rank": 12, "league": "Campeonato Brasileiro Série A (Brasileirão)", "sport": "Association football", "country": "Brazil", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Campeonato_Brasileiro_Série_A"},
    {"rank": 13, "league": "Nippon Professional Baseball (NPB)", "sport": "Baseball", "country": "Japan", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Nippon_Professional_Baseball"},
    {"rank": 14, "league": "English Football League Championship (EFL Championship)", "sport": "Association football", "country": "England, Wales", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/English_Football_League_Championship"},
    {"rank": 16, "league": "Australian Football League (AFL)", "sport": "Australian rules football", "country": "Australia", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Australian_Football_League"},
    {"rank": 17, "league": "2. Fußball-Bundesliga (2. Bundesliga)", "sport": "Association football", "country": "Germany", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/2._Fußball-Bundesliga"},
    {"rank": 18, "league": "Minor League Baseball (MiLB)", "sport": "Baseball", "country": "United States, Canada", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Minor_League_Baseball"},
    {"rank": 19, "league": "EuroLeague", "sport": "Basketball", "country": "Europe", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/EuroLeague"},
    {"rank": 20, "league": "Eredivisie", "sport": "Association football", "country": "Netherlands", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Eredivisie"},
    {"rank": 21, "league": "Chinese Basketball Association (CBA)", "sport": "Basketball", "country": "China", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Chinese_Basketball_Association"},
    {"rank": 22, "league": "J1 League", "sport": "Association football", "country": "Japan", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/J1_League"},
    {"rank": 30, "league": "Korea Baseball Organization League (KBO League)", "sport": "Baseball", "country": "South Korea", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Korea_Baseball_Organization_League"},
    {"rank": 31, "league": "National Rugby League (NRL)", "sport": "Rugby league football", "country": "Australia, New Zealand", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/National_Rugby_League"},
    {"rank": 32, "league": "Kontinental Hockey League (KHL)", "sport": "Ice hockey", "country": "Russia, Belarus, China, Kazakhstan", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Kontinental_Hockey_League"},
    {"rank": 33, "league": "Championnat de France de football de Ligue 2 (Ligue 2)", "sport": "Association football", "country": "France", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Championnat_de_France_de_football_de_Ligue_2"},
    {"rank": 34, "league": "Championnat de France de rugby à XV (Top 14)", "sport": "Rugby union football", "country": "France", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Championnat_de_France_de_rugby_à_XV"},
    {"rank": 35, "league": "Scottish Premiership (SPFL)", "sport": "Association football", "country": "Scotland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Scottish_Premiership"},
    {"rank": 43, "league": "B1 League", "sport": "Basketball", "country": "Japan", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/B1_League"},
    {"rank": 44, "league": "Premiership Rugby", "sport": "Rugby union football", "country": "England", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Premiership_Rugby"},
    {"rank": 45, "league": "Lega Italiana Calcio Professionistico (Serie C)", "sport": "Association football", "country": "Italy", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Lega_Italiana_Calcio_Professionistico"},
    {"rank": 49, "league": "Big Bash League (BBL)", "sport": "Twenty20 cricket", "country": "Australia", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Big_Bash_League"},
    {"rank": 50, "league": "English Football League Two (EFL League Two)", "sport": "Association football", "country": "England, Wales", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/English_Football_League_Two"},
    {"rank": 51, "league": "National League (NL)", "sport": "Ice hockey", "country": "Switzerland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/National_League"},
    {"rank": 52, "league": "Eliteserien", "sport": "Association football", "country": "Norway", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Eliteserien"},
    {"rank": 53, "league": "Swedish Hockey League (SHL)", "sport": "Ice hockey", "country": "Sweden", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Swedish_Hockey_League"},
    {"rank": 54, "league": "Super League Greece", "sport": "Association football", "country": "Greece", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Super_League_Greece"},
    {"rank": 56, "league": "Deutsche Eishockey Liga (DEL)", "sport": "Ice hockey", "country": "Germany", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Deutsche_Eishockey_Liga"},
    {"rank": 57, "league": "United Rugby Championship", "sport": "Rugby union football", "country": "Ireland, Italy, Scotland, South Africa, Wales", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/United_Rugby_Championship"},
    {"rank": 58, "league": "Women's National Basketball Association (WNBA)", "sport": "Basketball", "country": "United States", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Women's_National_Basketball_Association"},
    {"rank": 59, "league": "Championnat de France de rugby à XV de 2e division (Rugby Pro D2)", "sport": "Rugby union football", "country": "France", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Championnat_de_France_de_rugby_à_XV_de_2e_division"},
    {"rank": 60, "league": "Canadian Football League (CFL)", "sport": "Canadian football", "country": "Canada", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Canadian_Football_League"},
    {"rank": 61, "league": "Israeli Premier League", "sport": "Association football", "country": "Israel", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Israeli_Premier_League"},
    {"rank": 62, "league": "Liga de la Asociación de Clubs de Baloncesto (Liga ACB)", "sport": "Basketball", "country": "Spain, Andorra", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Liga_de_la_Asociación_de_Clubs_de_Baloncesto"},
    {"rank": 63, "league": "Caribbean Premier League (CPL)", "sport": "Twenty20 cricket", "country": "West Indies", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Caribbean_Premier_League"},
    {"rank": 64, "league": "Super Rugby", "sport": "Rugby union football", "country": "Australia, New Zealand, Fiji", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Super_Rugby"},
    {"rank": 65, "league": "Ukrainian Premier League (UPL)", "sport": "Association football", "country": "Ukraine", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Ukrainian_Premier_League"},
    {"rank": 66, "league": "Liiga", "sport": "Ice hockey", "country": "Finland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Liiga"},
    {"rank": 67, "league": "Saudi Professional League (SPL)", "sport": "Association football", "country": "Saudi Arabia", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Saudi_Professional_League"},
    {"rank": 68, "league": "Basketball Bundesliga (BBL)", "sport": "Basketball", "country": "Germany", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Basketball_Bundesliga"},
    {"rank": 69, "league": "Handball-Bundesliga (HBL)", "sport": "Handball", "country": "Germany", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Handball-Bundesliga"},
    {"rank": 70, "league": "Categoría Primera A", "sport": "Association football", "country": "Colombia", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Categoría_Primera_A"},
    {"rank": 75, "league": "Ligue Nationale de Basket Pro A (LNB Pro A)", "sport": "Basketball", "country": "France, Monaco", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Ligue_Nationale_de_Basket_Pro_A"},
    {"rank": 76, "league": "Mexican Baseball League (Liga Mexicana de Béisbol; LMB)", "sport": "Baseball", "country": "Mexico", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Mexican_Baseball_League"},
    {"rank": 77, "league": "Liga I", "sport": "Association football", "country": "Romania", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Liga_I"},
    {"rank": 79, "league": "Chinese Professional Baseball League (CPBL)", "sport": "Baseball", "country": "Taiwan", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Chinese_Professional_Baseball_League"},
    {"rank": 80, "league": "Campeonato Brasileiro Série B (Série B)", "sport": "Association football", "country": "Brazil", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Campeonato_Brasileiro_Série_B"},
    {"rank": 82, "league": "Mexican Pacific League (Liga Mexicana del Pacífico; LMP)", "sport": "Baseball", "country": "Mexico", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Mexican_Pacific_League"},
    {"rank": 83, "league": "Women's Premier League (cricket) (WPL)", "sport": "Twenty20 cricket", "country": "India", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Women's_Premier_League_(cricket)"},
    {"rank": 84, "league": "Kazakhstan Premier League", "sport": "Association football", "country": "Kazakhstan", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Kazakhstan_Premier_League"},
    {"rank": 91, "league": "Super League", "sport": "Rugby league football", "country": "England, France", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Super_League"},
    {"rank": 92, "league": "Championnat National", "sport": "Association football", "country": "France", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Championnat_National"},
    {"rank": 93, "league": "Women's Super League (WSL)", "sport": "Association football", "country": "England", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Women's_Super_League"},
    {"rank": 94, "league": "Chilean Primera División", "sport": "Association football", "country": "Chile", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Chilean_Primera_División"},
    {"rank": 95, "league": "Bangladesh Premier League (BPL)", "sport": "Twenty20 cricket", "country": "Bangladesh", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Bangladesh_Premier_League"},
    {"rank": 96, "league": "South African Premiership", "sport": "Association football", "country": "South Africa", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/South_African_Premiership"},
    {"rank": 99, "league": "LNB Pro B", "sport": "Basketball", "country": "France", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/LNB_Pro_B"},
    {"rank": 100, "league": "I liga polska", "sport": "Association football", "country": "Poland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/I_liga_polska"},
    {"rank": 101, "league": "National Basketball League (NBL)", "sport": "Basketball", "country": "Australia, New Zealand", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/National_Basketball_League"},
    {"rank": 102, "league": "Belarusian Premier League (Vyšejšaja Liha)", "sport": "Association football", "country": "Belarus", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Belarusian_Premier_League"},
    {"rank": 104, "league": "Deutsche Eishockey Liga 2 (DEL2)", "sport": "Ice hockey", "country": "Germany", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Deutsche_Eishockey_Liga_2"},
    {"rank": 105, "league": "Superettan", "sport": "Association football", "country": "Sweden", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Superettan"},
    {"rank": 107, "league": "Lietuvos krepšinio lyga (LKL)", "sport": "Basketball", "country": "Lithuania", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Lietuvos_krepšinio_lyga"},
    {"rank": 108, "league": "Veikkausliiga", "sport": "Association football", "country": "Finland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Veikkausliiga"},
    {"rank": 109, "league": "Pro Kabaddi League (PKL)", "sport": "Kabaddi", "country": "India", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Pro_Kabaddi_League"},
    {"rank": 110, "league": "Latvian Higher League", "sport": "Association football", "country": "Latvia", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Latvian_Higher_League"},
    {"rank": 114, "league": "Ekstraliga", "sport": "Speedway", "country": "Poland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/Ekstraliga"},
    {"rank": 115, "league": "League of Ireland Premier Division", "sport": "Association football", "country": "Ireland, Northern Ireland", "website": "", "wikipedia": "https://en.wikipedia.org/wiki/League_of_Ireland_Premier_Division"},
]
