"""
Baked-in National Football League reference data: all 32 NFL teams, grouped by
conference and division, with home city, stadium, official website, social
handles (X/Twitter, Instagram) and Wikipedia page. Team list, conferences,
divisions, cities and stadiums are from the NFL's Wikipedia article; official
websites and social handles are verified club accounts.

Source: https://en.wikipedia.org/wiki/National_Football_League
"""

NFL_EDITION = "32 teams (by conference & division)"
NFL_SOURCE_URL = "https://en.wikipedia.org/wiki/National_Football_League"

NFL_TEAMS = [
    {"rank": 1,  "team": "Buffalo Bills", "conference": "AFC", "division": "East", "city": "Orchard Park, NY", "stadium": "Highmark Stadium", "website": "https://www.buffalobills.com/", "twitter": "https://x.com/BuffaloBills", "instagram": "https://www.instagram.com/buffalobills", "wikipedia": "https://en.wikipedia.org/wiki/Buffalo_Bills"},
    {"rank": 2,  "team": "Miami Dolphins", "conference": "AFC", "division": "East", "city": "Miami Gardens, FL", "stadium": "Hard Rock Stadium", "website": "https://www.miamidolphins.com/", "twitter": "https://x.com/MiamiDolphins", "instagram": "https://www.instagram.com/miamidolphins", "wikipedia": "https://en.wikipedia.org/wiki/Miami_Dolphins"},
    {"rank": 3,  "team": "New England Patriots", "conference": "AFC", "division": "East", "city": "Foxborough, MA", "stadium": "Gillette Stadium", "website": "https://www.patriots.com/", "twitter": "https://x.com/Patriots", "instagram": "https://www.instagram.com/patriots", "wikipedia": "https://en.wikipedia.org/wiki/New_England_Patriots"},
    {"rank": 4,  "team": "New York Jets", "conference": "AFC", "division": "East", "city": "East Rutherford, NJ", "stadium": "MetLife Stadium", "website": "https://www.newyorkjets.com/", "twitter": "https://x.com/nyjets", "instagram": "https://www.instagram.com/nyjets", "wikipedia": "https://en.wikipedia.org/wiki/New_York_Jets"},
    {"rank": 5,  "team": "Baltimore Ravens", "conference": "AFC", "division": "North", "city": "Baltimore, MD", "stadium": "M&T Bank Stadium", "website": "https://www.baltimoreravens.com/", "twitter": "https://x.com/Ravens", "instagram": "https://www.instagram.com/ravens", "wikipedia": "https://en.wikipedia.org/wiki/Baltimore_Ravens"},
    {"rank": 6,  "team": "Cincinnati Bengals", "conference": "AFC", "division": "North", "city": "Cincinnati, OH", "stadium": "Paycor Stadium", "website": "https://www.bengals.com/", "twitter": "https://x.com/Bengals", "instagram": "https://www.instagram.com/bengals", "wikipedia": "https://en.wikipedia.org/wiki/Cincinnati_Bengals"},
    {"rank": 7,  "team": "Cleveland Browns", "conference": "AFC", "division": "North", "city": "Cleveland, OH", "stadium": "Huntington Bank Field", "website": "https://www.clevelandbrowns.com/", "twitter": "https://x.com/Browns", "instagram": "https://www.instagram.com/clevelandbrowns", "wikipedia": "https://en.wikipedia.org/wiki/Cleveland_Browns"},
    {"rank": 8,  "team": "Pittsburgh Steelers", "conference": "AFC", "division": "North", "city": "Pittsburgh, PA", "stadium": "Acrisure Stadium", "website": "https://www.steelers.com/", "twitter": "https://x.com/steelers", "instagram": "https://www.instagram.com/steelers", "wikipedia": "https://en.wikipedia.org/wiki/Pittsburgh_Steelers"},
    {"rank": 9,  "team": "Houston Texans", "conference": "AFC", "division": "South", "city": "Houston, TX", "stadium": "NRG Stadium", "website": "https://www.houstontexans.com/", "twitter": "https://x.com/HoustonTexans", "instagram": "https://www.instagram.com/houstontexans", "wikipedia": "https://en.wikipedia.org/wiki/Houston_Texans"},
    {"rank": 10, "team": "Indianapolis Colts", "conference": "AFC", "division": "South", "city": "Indianapolis, IN", "stadium": "Lucas Oil Stadium", "website": "https://www.colts.com/", "twitter": "https://x.com/Colts", "instagram": "https://www.instagram.com/colts", "wikipedia": "https://en.wikipedia.org/wiki/Indianapolis_Colts"},
    {"rank": 11, "team": "Jacksonville Jaguars", "conference": "AFC", "division": "South", "city": "Jacksonville, FL", "stadium": "EverBank Stadium", "website": "https://www.jaguars.com/", "twitter": "https://x.com/Jaguars", "instagram": "https://www.instagram.com/jaguars", "wikipedia": "https://en.wikipedia.org/wiki/Jacksonville_Jaguars"},
    {"rank": 12, "team": "Tennessee Titans", "conference": "AFC", "division": "South", "city": "Nashville, TN", "stadium": "Nissan Stadium", "website": "https://www.tennesseetitans.com/", "twitter": "https://x.com/Titans", "instagram": "https://www.instagram.com/titans", "wikipedia": "https://en.wikipedia.org/wiki/Tennessee_Titans"},
    {"rank": 13, "team": "Denver Broncos", "conference": "AFC", "division": "West", "city": "Denver, CO", "stadium": "Empower Field at Mile High", "website": "https://www.denverbroncos.com/", "twitter": "https://x.com/Broncos", "instagram": "https://www.instagram.com/broncos", "wikipedia": "https://en.wikipedia.org/wiki/Denver_Broncos"},
    {"rank": 14, "team": "Kansas City Chiefs", "conference": "AFC", "division": "West", "city": "Kansas City, MO", "stadium": "GEHA Field at Arrowhead Stadium", "website": "https://www.chiefs.com/", "twitter": "https://x.com/Chiefs", "instagram": "https://www.instagram.com/chiefs", "wikipedia": "https://en.wikipedia.org/wiki/Kansas_City_Chiefs"},
    {"rank": 15, "team": "Las Vegas Raiders", "conference": "AFC", "division": "West", "city": "Paradise, NV", "stadium": "Allegiant Stadium", "website": "https://www.raiders.com/", "twitter": "https://x.com/Raiders", "instagram": "https://www.instagram.com/raiders", "wikipedia": "https://en.wikipedia.org/wiki/Las_Vegas_Raiders"},
    {"rank": 16, "team": "Los Angeles Chargers", "conference": "AFC", "division": "West", "city": "Inglewood, CA", "stadium": "SoFi Stadium", "website": "https://www.chargers.com/", "twitter": "https://x.com/chargers", "instagram": "https://www.instagram.com/chargers", "wikipedia": "https://en.wikipedia.org/wiki/Los_Angeles_Chargers"},
    {"rank": 17, "team": "Dallas Cowboys", "conference": "NFC", "division": "East", "city": "Arlington, TX", "stadium": "AT&T Stadium", "website": "https://www.dallascowboys.com/", "twitter": "https://x.com/dallascowboys", "instagram": "https://www.instagram.com/dallascowboys", "wikipedia": "https://en.wikipedia.org/wiki/Dallas_Cowboys"},
    {"rank": 18, "team": "New York Giants", "conference": "NFC", "division": "East", "city": "East Rutherford, NJ", "stadium": "MetLife Stadium", "website": "https://www.giants.com/", "twitter": "https://x.com/Giants", "instagram": "https://www.instagram.com/nygiants", "wikipedia": "https://en.wikipedia.org/wiki/New_York_Giants"},
    {"rank": 19, "team": "Philadelphia Eagles", "conference": "NFC", "division": "East", "city": "Philadelphia, PA", "stadium": "Lincoln Financial Field", "website": "https://www.philadelphiaeagles.com/", "twitter": "https://x.com/Eagles", "instagram": "https://www.instagram.com/philadelphiaeagles", "wikipedia": "https://en.wikipedia.org/wiki/Philadelphia_Eagles"},
    {"rank": 20, "team": "Washington Commanders", "conference": "NFC", "division": "East", "city": "Landover, MD", "stadium": "Northwest Stadium", "website": "https://www.commanders.com/", "twitter": "https://x.com/Commanders", "instagram": "https://www.instagram.com/commanders", "wikipedia": "https://en.wikipedia.org/wiki/Washington_Commanders"},
    {"rank": 21, "team": "Chicago Bears", "conference": "NFC", "division": "North", "city": "Chicago, IL", "stadium": "Soldier Field", "website": "https://www.chicagobears.com/", "twitter": "https://x.com/ChicagoBears", "instagram": "https://www.instagram.com/chicagobears", "wikipedia": "https://en.wikipedia.org/wiki/Chicago_Bears"},
    {"rank": 22, "team": "Detroit Lions", "conference": "NFC", "division": "North", "city": "Detroit, MI", "stadium": "Ford Field", "website": "https://www.detroitlions.com/", "twitter": "https://x.com/Lions", "instagram": "https://www.instagram.com/detroitlionsnfl", "wikipedia": "https://en.wikipedia.org/wiki/Detroit_Lions"},
    {"rank": 23, "team": "Green Bay Packers", "conference": "NFC", "division": "North", "city": "Green Bay, WI", "stadium": "Lambeau Field", "website": "https://www.packers.com/", "twitter": "https://x.com/packers", "instagram": "https://www.instagram.com/packers", "wikipedia": "https://en.wikipedia.org/wiki/Green_Bay_Packers"},
    {"rank": 24, "team": "Minnesota Vikings", "conference": "NFC", "division": "North", "city": "Minneapolis, MN", "stadium": "U.S. Bank Stadium", "website": "https://www.vikings.com/", "twitter": "https://x.com/Vikings", "instagram": "https://www.instagram.com/vikings", "wikipedia": "https://en.wikipedia.org/wiki/Minnesota_Vikings"},
    {"rank": 25, "team": "Atlanta Falcons", "conference": "NFC", "division": "South", "city": "Atlanta, GA", "stadium": "Mercedes-Benz Stadium", "website": "https://www.atlantafalcons.com/", "twitter": "https://x.com/AtlantaFalcons", "instagram": "https://www.instagram.com/atlantafalcons", "wikipedia": "https://en.wikipedia.org/wiki/Atlanta_Falcons"},
    {"rank": 26, "team": "Carolina Panthers", "conference": "NFC", "division": "South", "city": "Charlotte, NC", "stadium": "Bank of America Stadium", "website": "https://www.panthers.com/", "twitter": "https://x.com/Panthers", "instagram": "https://www.instagram.com/panthers", "wikipedia": "https://en.wikipedia.org/wiki/Carolina_Panthers"},
    {"rank": 27, "team": "New Orleans Saints", "conference": "NFC", "division": "South", "city": "New Orleans, LA", "stadium": "Caesars Superdome", "website": "https://www.neworleanssaints.com/", "twitter": "https://x.com/Saints", "instagram": "https://www.instagram.com/saints", "wikipedia": "https://en.wikipedia.org/wiki/New_Orleans_Saints"},
    {"rank": 28, "team": "Tampa Bay Buccaneers", "conference": "NFC", "division": "South", "city": "Tampa, FL", "stadium": "Raymond James Stadium", "website": "https://www.buccaneers.com/", "twitter": "https://x.com/Buccaneers", "instagram": "https://www.instagram.com/buccaneers", "wikipedia": "https://en.wikipedia.org/wiki/Tampa_Bay_Buccaneers"},
    {"rank": 29, "team": "Arizona Cardinals", "conference": "NFC", "division": "West", "city": "Glendale, AZ", "stadium": "State Farm Stadium", "website": "https://www.azcardinals.com/", "twitter": "https://x.com/AZCardinals", "instagram": "https://www.instagram.com/azcardinals", "wikipedia": "https://en.wikipedia.org/wiki/Arizona_Cardinals"},
    {"rank": 30, "team": "Los Angeles Rams", "conference": "NFC", "division": "West", "city": "Inglewood, CA", "stadium": "SoFi Stadium", "website": "https://www.therams.com/", "twitter": "https://x.com/RamsNFL", "instagram": "https://www.instagram.com/rams", "wikipedia": "https://en.wikipedia.org/wiki/Los_Angeles_Rams"},
    {"rank": 31, "team": "San Francisco 49ers", "conference": "NFC", "division": "West", "city": "Santa Clara, CA", "stadium": "Levi's Stadium", "website": "https://www.49ers.com/", "twitter": "https://x.com/49ers", "instagram": "https://www.instagram.com/49ers", "wikipedia": "https://en.wikipedia.org/wiki/San_Francisco_49ers"},
    {"rank": 32, "team": "Seattle Seahawks", "conference": "NFC", "division": "West", "city": "Seattle, WA", "stadium": "Lumen Field", "website": "https://www.seahawks.com/", "twitter": "https://x.com/Seahawks", "instagram": "https://www.instagram.com/seahawks", "wikipedia": "https://en.wikipedia.org/wiki/Seattle_Seahawks"},
]
