"""
Baked-in English Premier League reference data: the 20 clubs of the
2025/26 Premier League season, ordered by final league position, with each
club's home city, stadium, points, official website, social handles
(X/Twitter, Instagram, Facebook, YouTube) and Wikipedia page.

Versioned yearly snapshot. The official Premier League site
(https://www.premierleague.com/en) is JavaScript-rendered, so the club list and
final standings are stored here and refreshed each season. Social accounts are
official club handles; blank where not verifiable. Wikipedia links are direct
article URLs.

Source: https://www.premierleague.com/en
"""

PL_EDITION = "2025/26"
PL_SOURCE_URL = "https://www.premierleague.com/en"

PREMIER_LEAGUE_CLUBS = [
    {"position": 1, "club": "Arsenal", "city": "London", "stadium": "Emirates Stadium", "points": 85, "website": "https://www.arsenal.com/", "twitter": "https://x.com/Arsenal", "instagram": "https://www.instagram.com/arsenal", "facebook": "https://www.facebook.com/Arsenal", "youtube": "https://www.youtube.com/arsenal", "wikipedia": "https://en.wikipedia.org/wiki/Arsenal_F.C."},
    {"position": 2, "club": "Manchester City", "city": "Manchester", "stadium": "Etihad Stadium", "points": 78, "website": "https://www.mancity.com/", "twitter": "https://x.com/ManCity", "instagram": "https://www.instagram.com/mancity", "facebook": "https://www.facebook.com/mancity", "youtube": "https://www.youtube.com/mancity", "wikipedia": "https://en.wikipedia.org/wiki/Manchester_City_F.C."},
    {"position": 3, "club": "Manchester United", "city": "Manchester", "stadium": "Old Trafford", "points": 71, "website": "https://www.manutd.com/", "twitter": "https://x.com/ManUtd", "instagram": "https://www.instagram.com/manchesterunited", "facebook": "https://www.facebook.com/manchesterunited", "youtube": "https://www.youtube.com/manutd", "wikipedia": "https://en.wikipedia.org/wiki/Manchester_United_F.C."},
    {"position": 4, "club": "Aston Villa", "city": "Birmingham", "stadium": "Villa Park", "points": 65, "website": "https://www.avfc.co.uk/", "twitter": "https://x.com/AVFCOfficial", "instagram": "https://www.instagram.com/avfcofficial", "facebook": "https://www.facebook.com/avfcofficial", "youtube": "https://www.youtube.com/avfcofficial", "wikipedia": "https://en.wikipedia.org/wiki/Aston_Villa_F.C."},
    {"position": 5, "club": "Liverpool", "city": "Liverpool", "stadium": "Anfield", "points": 60, "website": "https://www.liverpoolfc.com/", "twitter": "https://x.com/LFC", "instagram": "https://www.instagram.com/liverpoolfc", "facebook": "https://www.facebook.com/LiverpoolFC", "youtube": "https://www.youtube.com/liverpoolfc", "wikipedia": "https://en.wikipedia.org/wiki/Liverpool_F.C."},
    {"position": 6, "club": "AFC Bournemouth", "city": "Bournemouth", "stadium": "Vitality Stadium", "points": 57, "website": "https://www.afcb.co.uk/", "twitter": "https://x.com/afcbournemouth", "instagram": "https://www.instagram.com/afcb", "facebook": "https://www.facebook.com/afcbournemouth", "youtube": "https://www.youtube.com/afcbournemouth", "wikipedia": "https://en.wikipedia.org/wiki/AFC_Bournemouth"},
    {"position": 7, "club": "Sunderland", "city": "Sunderland", "stadium": "Stadium of Light", "points": 54, "website": "https://www.safc.com/", "twitter": "https://x.com/SunderlandAFC", "instagram": "https://www.instagram.com/sunderlandafcofficial", "facebook": "https://www.facebook.com/SunderlandAFC", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Sunderland_A.F.C."},
    {"position": 8, "club": "Brighton & Hove Albion", "city": "Brighton", "stadium": "Amex Stadium", "points": 53, "website": "https://www.brightonandhovealbion.com/", "twitter": "https://x.com/OfficialBHAFC", "instagram": "https://www.instagram.com/officialbhafc", "facebook": "https://www.facebook.com/officialbhafc", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Brighton_%26_Hove_Albion_F.C."},
    {"position": 9, "club": "Brentford", "city": "London", "stadium": "Gtech Community Stadium", "points": 53, "website": "https://www.brentfordfc.com/", "twitter": "https://x.com/BrentfordFC", "instagram": "https://www.instagram.com/brentfordfc", "facebook": "https://www.facebook.com/brentfordfc", "youtube": "https://www.youtube.com/brentfordfc", "wikipedia": "https://en.wikipedia.org/wiki/Brentford_F.C."},
    {"position": 10, "club": "Chelsea", "city": "London", "stadium": "Stamford Bridge", "points": 52, "website": "https://www.chelseafc.com/", "twitter": "https://x.com/ChelseaFC", "instagram": "https://www.instagram.com/chelseafc", "facebook": "https://www.facebook.com/chelseafc", "youtube": "https://www.youtube.com/chelseafc", "wikipedia": "https://en.wikipedia.org/wiki/Chelsea_F.C."},
    {"position": 11, "club": "Fulham", "city": "London", "stadium": "Craven Cottage", "points": 52, "website": "https://www.fulhamfc.com/", "twitter": "https://x.com/FulhamFC", "instagram": "https://www.instagram.com/fulhamfc", "facebook": "https://www.facebook.com/fulhamfc", "youtube": "https://www.youtube.com/fulhamfc", "wikipedia": "https://en.wikipedia.org/wiki/Fulham_F.C."},
    {"position": 12, "club": "Newcastle United", "city": "Newcastle upon Tyne", "stadium": "St James' Park", "points": 49, "website": "https://www.newcastleunited.com/", "twitter": "https://x.com/NUFC", "instagram": "https://www.instagram.com/nufc", "facebook": "https://www.facebook.com/newcastleunited", "youtube": "https://www.youtube.com/nufc", "wikipedia": "https://en.wikipedia.org/wiki/Newcastle_United_F.C."},
    {"position": 13, "club": "Everton", "city": "Liverpool", "stadium": "Hill Dickinson Stadium", "points": 49, "website": "https://www.evertonfc.com/", "twitter": "https://x.com/Everton", "instagram": "https://www.instagram.com/everton", "facebook": "https://www.facebook.com/everton", "youtube": "https://www.youtube.com/everton", "wikipedia": "https://en.wikipedia.org/wiki/Everton_F.C."},
    {"position": 14, "club": "Leeds United", "city": "Leeds", "stadium": "Elland Road", "points": 47, "website": "https://www.leedsunited.com/", "twitter": "https://x.com/LUFC", "instagram": "https://www.instagram.com/leedsunited", "facebook": "https://www.facebook.com/leedsunited", "youtube": "https://www.youtube.com/leedsunited", "wikipedia": "https://en.wikipedia.org/wiki/Leeds_United_F.C."},
    {"position": 15, "club": "Crystal Palace", "city": "London", "stadium": "Selhurst Park", "points": 45, "website": "https://www.cpfc.co.uk/", "twitter": "https://x.com/CPFC", "instagram": "https://www.instagram.com/cpfc", "facebook": "https://www.facebook.com/cpfc", "youtube": "https://www.youtube.com/cpfc", "wikipedia": "https://en.wikipedia.org/wiki/Crystal_Palace_F.C."},
    {"position": 16, "club": "Nottingham Forest", "city": "Nottingham", "stadium": "City Ground", "points": 44, "website": "https://www.nottinghamforest.co.uk/", "twitter": "https://x.com/NFFC", "instagram": "https://www.instagram.com/officialnffc", "facebook": "https://www.facebook.com/officialnffc", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Nottingham_Forest_F.C."},
    {"position": 17, "club": "Tottenham Hotspur", "city": "London", "stadium": "Tottenham Hotspur Stadium", "points": 41, "website": "https://www.tottenhamhotspur.com/", "twitter": "https://x.com/SpursOfficial", "instagram": "https://www.instagram.com/spursofficial", "facebook": "https://www.facebook.com/TottenhamHotspur", "youtube": "https://www.youtube.com/tottenham", "wikipedia": "https://en.wikipedia.org/wiki/Tottenham_Hotspur_F.C."},
    {"position": 18, "club": "West Ham United", "city": "London", "stadium": "London Stadium", "points": 39, "website": "https://www.whufc.com/", "twitter": "https://x.com/WestHam", "instagram": "https://www.instagram.com/westham", "facebook": "https://www.facebook.com/westham", "youtube": "https://www.youtube.com/westhamunited", "wikipedia": "https://en.wikipedia.org/wiki/West_Ham_United_F.C."},
    {"position": 19, "club": "Burnley", "city": "Burnley", "stadium": "Turf Moor", "points": 22, "website": "https://www.burnleyfootballclub.com/", "twitter": "https://x.com/burnleyofficial", "instagram": "https://www.instagram.com/burnleyofficial", "facebook": "https://www.facebook.com/officialburnleyfootballclub", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Burnley_F.C."},
    {"position": 20, "club": "Wolverhampton Wanderers", "city": "Wolverhampton", "stadium": "Molineux Stadium", "points": 20, "website": "https://www.wolves.co.uk/", "twitter": "https://x.com/Wolves", "instagram": "https://www.instagram.com/wolves", "facebook": "https://www.facebook.com/wolves", "youtube": "https://www.youtube.com/wolves", "wikipedia": "https://en.wikipedia.org/wiki/Wolverhampton_Wanderers_F.C."},
]
