"""
Baked-in Sephora brand directory, sourced from sephora.com/brands-list.

The list is Sephora's full A-Z brand directory. Each brand links to its
Sephora brand page (slug auto-derived from the name). Social handles are
auto-generated from the brand name and UNVERIFIED, except a small set of
prominent brands with verified Instagram/X handles baked in below.

Sources: https://www.sephora.com/brands-list
"""

SEPHORA_EDITION = "sephora.com brands A-Z (socials auto-generated; select brands verified)"
SEPHORA_SOURCE_URL = "https://www.sephora.com/brands-list"

SEPHORA_BRANDS = [
    {"rank": 1, "brand": "5 SENS", "sephora_url": "https://www.sephora.com/brand/5-sens", "wikipedia": ""},
    {"rank": 2, "brand": "54 Thrones", "sephora_url": "https://www.sephora.com/brand/54-thrones", "wikipedia": ""},
    {"rank": 3, "brand": "AAVRANI", "sephora_url": "https://www.sephora.com/brand/aavrani", "wikipedia": ""},
    {"rank": 4, "brand": "Act+Acre", "sephora_url": "https://www.sephora.com/brand/act-plus-acre", "wikipedia": ""},
    {"rank": 5, "brand": "adwoa beauty", "sephora_url": "https://www.sephora.com/brand/adwoa-beauty", "wikipedia": ""},
    {"rank": 6, "brand": "AESTURA", "sephora_url": "https://www.sephora.com/brand/aestura", "wikipedia": ""},
    {"rank": 7, "brand": "AKT London", "sephora_url": "https://www.sephora.com/brand/akt-london", "wikipedia": ""},
    {"rank": 8, "brand": "ALPYN", "sephora_url": "https://www.sephora.com/brand/alpyn", "wikipedia": ""},
    {"rank": 9, "brand": "ALTERNA Haircare", "sephora_url": "https://www.sephora.com/brand/alterna-haircare", "wikipedia": ""},
    {"rank": 10, "brand": "Ami Colé", "sephora_url": "https://www.sephora.com/brand/ami-cole", "wikipedia": ""},
    {"rank": 11, "brand": "amika", "sephora_url": "https://www.sephora.com/brand/amika", "wikipedia": ""},
    {"rank": 12, "brand": "Anastasia Beverly Hills", "sephora_url": "https://www.sephora.com/brand/anastasia-beverly-hills", "wikipedia": ""},
    {"rank": 13, "brand": "AORA México", "sephora_url": "https://www.sephora.com/brand/aora-mexico", "wikipedia": ""},
    {"rank": 14, "brand": "Arencia", "sephora_url": "https://www.sephora.com/brand/arencia", "wikipedia": ""},
    {"rank": 15, "brand": "Ariana Grande", "sephora_url": "https://www.sephora.com/brand/ariana-grande", "wikipedia": ""},
    {"rank": 16, "brand": "Armani Beauty", "sephora_url": "https://www.sephora.com/brand/armani-beauty", "wikipedia": ""},
    {"rank": 17, "brand": "Augustinus Bader", "sephora_url": "https://www.sephora.com/brand/augustinus-bader", "wikipedia": ""},
    {"rank": 18, "brand": "Azzaro", "sephora_url": "https://www.sephora.com/brand/azzaro", "wikipedia": ""},
    {"rank": 19, "brand": "BaBylissPRO", "sephora_url": "https://www.sephora.com/brand/babylisspro", "wikipedia": ""},
    {"rank": 20, "brand": "banu", "sephora_url": "https://www.sephora.com/brand/banu", "wikipedia": ""},
    {"rank": 21, "brand": "bareMinerals", "sephora_url": "https://www.sephora.com/brand/bareminerals", "wikipedia": ""},
    {"rank": 22, "brand": "BASMA", "sephora_url": "https://www.sephora.com/brand/basma", "wikipedia": ""},
    {"rank": 23, "brand": "Beauty of Joseon", "sephora_url": "https://www.sephora.com/brand/beauty-of-joseon", "wikipedia": ""},
    {"rank": 24, "brand": "BeautyBio", "sephora_url": "https://www.sephora.com/brand/beautybio", "wikipedia": ""},
    {"rank": 25, "brand": "Beautyblender", "sephora_url": "https://www.sephora.com/brand/beautyblender", "wikipedia": ""},
    {"rank": 26, "brand": "belif", "sephora_url": "https://www.sephora.com/brand/belif", "wikipedia": ""},
    {"rank": 27, "brand": "Benefit Cosmetics", "sephora_url": "https://www.sephora.com/brand/benefit-cosmetics", "wikipedia": "", "instagram": "https://www.instagram.com/benefitcosmetics", "twitter": "https://x.com/BenefitBeauty"},
    {"rank": 28, "brand": "Bio Ionic", "sephora_url": "https://www.sephora.com/brand/bio-ionic", "wikipedia": ""},
    {"rank": 29, "brand": "Biodance", "sephora_url": "https://www.sephora.com/brand/biodance", "wikipedia": ""},
    {"rank": 30, "brand": "Biossance", "sephora_url": "https://www.sephora.com/brand/biossance", "wikipedia": ""},
    {"rank": 31, "brand": "Bobbi Brown", "sephora_url": "https://www.sephora.com/brand/bobbi-brown", "wikipedia": ""},
    {"rank": 32, "brand": "BondiBoost", "sephora_url": "https://www.sephora.com/brand/bondiboost", "wikipedia": ""},
    {"rank": 33, "brand": "BORNTOSTANDOUT", "sephora_url": "https://www.sephora.com/brand/borntostandout", "wikipedia": ""},
    {"rank": 34, "brand": "Bounce Curl", "sephora_url": "https://www.sephora.com/brand/bounce-curl", "wikipedia": ""},
    {"rank": 35, "brand": "Boy Smells", "sephora_url": "https://www.sephora.com/brand/boy-smells", "wikipedia": ""},
    {"rank": 36, "brand": "BREAD BEAUTY SUPPLY", "sephora_url": "https://www.sephora.com/brand/bread-beauty-supply", "wikipedia": ""},
    {"rank": 37, "brand": "Briogeo", "sephora_url": "https://www.sephora.com/brand/briogeo", "wikipedia": ""},
    {"rank": 38, "brand": "BROWN GIRL Jane", "sephora_url": "https://www.sephora.com/brand/brown-girl-jane", "wikipedia": ""},
    {"rank": 39, "brand": "Bumble and bumble", "sephora_url": "https://www.sephora.com/brand/bumble-and-bumble", "wikipedia": ""},
    {"rank": 40, "brand": "BURBERRY", "sephora_url": "https://www.sephora.com/brand/burberry", "wikipedia": ""},
    {"rank": 41, "brand": "By Rosie Jane", "sephora_url": "https://www.sephora.com/brand/by-rosie-jane", "wikipedia": ""},
    {"rank": 42, "brand": "caliray", "sephora_url": "https://www.sephora.com/brand/caliray", "wikipedia": ""},
    {"rank": 43, "brand": "CANOPY", "sephora_url": "https://www.sephora.com/brand/canopy", "wikipedia": ""},
    {"rank": 44, "brand": "Carolina Herrera", "sephora_url": "https://www.sephora.com/brand/carolina-herrera", "wikipedia": ""},
    {"rank": 45, "brand": "Caudalie", "sephora_url": "https://www.sephora.com/brand/caudalie", "wikipedia": ""},
    {"rank": 46, "brand": "CAY SKIN", "sephora_url": "https://www.sephora.com/brand/cay-skin", "wikipedia": ""},
    {"rank": 47, "brand": "Ceremonia", "sephora_url": "https://www.sephora.com/brand/ceremonia", "wikipedia": ""},
    {"rank": 48, "brand": "CHANEL", "sephora_url": "https://www.sephora.com/brand/chanel", "wikipedia": "", "instagram": "https://www.instagram.com/chanel.beauty", "twitter": "https://x.com/CHANEL"},
    {"rank": 49, "brand": "Charlotte Tilbury", "sephora_url": "https://www.sephora.com/brand/charlotte-tilbury", "wikipedia": "", "instagram": "https://www.instagram.com/charlottetilbury", "twitter": "https://x.com/CTilburyMakeup"},
    {"rank": 50, "brand": "Chloé", "sephora_url": "https://www.sephora.com/brand/chloe", "wikipedia": ""},
    {"rank": 51, "brand": "Chris McMillan", "sephora_url": "https://www.sephora.com/brand/chris-mcmillan", "wikipedia": ""},
    {"rank": 52, "brand": "Chunks", "sephora_url": "https://www.sephora.com/brand/chunks", "wikipedia": ""},
    {"rank": 53, "brand": "ciele", "sephora_url": "https://www.sephora.com/brand/ciele", "wikipedia": ""},
    {"rank": 54, "brand": "Cinema Secrets", "sephora_url": "https://www.sephora.com/brand/cinema-secrets", "wikipedia": ""},
    {"rank": 55, "brand": "Clarins", "sephora_url": "https://www.sephora.com/brand/clarins", "wikipedia": ""},
    {"rank": 56, "brand": "CLEAN RESERVE", "sephora_url": "https://www.sephora.com/brand/clean-reserve", "wikipedia": ""},
    {"rank": 57, "brand": "CLINIQUE", "sephora_url": "https://www.sephora.com/brand/clinique", "wikipedia": ""},
    {"rank": 58, "brand": "COACH", "sephora_url": "https://www.sephora.com/brand/coach", "wikipedia": ""},
    {"rank": 59, "brand": "COLOR WOW", "sephora_url": "https://www.sephora.com/brand/color-wow", "wikipedia": ""},
    {"rank": 60, "brand": "Commodity", "sephora_url": "https://www.sephora.com/brand/commodity", "wikipedia": ""},
    {"rank": 61, "brand": "Community Sixty-Six", "sephora_url": "https://www.sephora.com/brand/community-sixty-six", "wikipedia": ""},
    {"rank": 62, "brand": "COOLA", "sephora_url": "https://www.sephora.com/brand/coola", "wikipedia": ""},
    {"rank": 63, "brand": "Crown Affair", "sephora_url": "https://www.sephora.com/brand/crown-affair", "wikipedia": ""},
    {"rank": 64, "brand": "Curlsmith", "sephora_url": "https://www.sephora.com/brand/curlsmith", "wikipedia": ""},
    {"rank": 65, "brand": "CYKLAR", "sephora_url": "https://www.sephora.com/brand/cyklar", "wikipedia": ""},
    {"rank": 66, "brand": "dae", "sephora_url": "https://www.sephora.com/brand/dae", "wikipedia": ""},
    {"rank": 67, "brand": "DAMDAM", "sephora_url": "https://www.sephora.com/brand/damdam", "wikipedia": ""},
    {"rank": 68, "brand": "Danessa Myricks Beauty", "sephora_url": "https://www.sephora.com/brand/danessa-myricks-beauty", "wikipedia": ""},
    {"rank": 69, "brand": "Davines", "sephora_url": "https://www.sephora.com/brand/davines", "wikipedia": ""},
    {"rank": 70, "brand": "DedCool", "sephora_url": "https://www.sephora.com/brand/dedcool", "wikipedia": ""},
    {"rank": 71, "brand": "DEREK LAM 10 CROSBY", "sephora_url": "https://www.sephora.com/brand/derek-lam-10-crosby", "wikipedia": ""},
    {"rank": 72, "brand": "DERMAFLASH", "sephora_url": "https://www.sephora.com/brand/dermaflash", "wikipedia": ""},
    {"rank": 73, "brand": "Dermalogica", "sephora_url": "https://www.sephora.com/brand/dermalogica", "wikipedia": ""},
    {"rank": 74, "brand": "Dezi Skin", "sephora_url": "https://www.sephora.com/brand/dezi-skin", "wikipedia": ""},
    {"rank": 75, "brand": "Dieux", "sephora_url": "https://www.sephora.com/brand/dieux", "wikipedia": ""},
    {"rank": 76, "brand": "DIOR", "sephora_url": "https://www.sephora.com/brand/dior", "wikipedia": "", "instagram": "https://www.instagram.com/diormakeup", "twitter": "https://x.com/Dior"},
    {"rank": 77, "brand": "Dolce Glow", "sephora_url": "https://www.sephora.com/brand/dolce-glow", "wikipedia": ""},
    {"rank": 78, "brand": "Dolce&Gabbana", "sephora_url": "https://www.sephora.com/brand/dolce-and-gabbana", "wikipedia": ""},
    {"rank": 79, "brand": "DOMINIQUE COSMETICS", "sephora_url": "https://www.sephora.com/brand/dominique-cosmetics", "wikipedia": ""},
    {"rank": 80, "brand": "Donna Karan", "sephora_url": "https://www.sephora.com/brand/donna-karan", "wikipedia": ""},
    {"rank": 81, "brand": "Dr. Barbara Sturm", "sephora_url": "https://www.sephora.com/brand/dr-barbara-sturm", "wikipedia": ""},
    {"rank": 82, "brand": "Dr. Dennis Gross Skincare", "sephora_url": "https://www.sephora.com/brand/dr-dennis-gross-skincare", "wikipedia": ""},
    {"rank": 83, "brand": "Dr. Groot", "sephora_url": "https://www.sephora.com/brand/dr-groot", "wikipedia": ""},
    {"rank": 84, "brand": "Dr. Idriss", "sephora_url": "https://www.sephora.com/brand/dr-idriss", "wikipedia": ""},
    {"rank": 85, "brand": "Dr. Jart+", "sephora_url": "https://www.sephora.com/brand/dr-jart-plus", "wikipedia": ""},
    {"rank": 86, "brand": "Dr.FORHAIR", "sephora_url": "https://www.sephora.com/brand/dr-forhair", "wikipedia": ""},
    {"rank": 87, "brand": "Drunk Elephant", "sephora_url": "https://www.sephora.com/brand/drunk-elephant", "wikipedia": "", "instagram": "https://www.instagram.com/drunkelephant", "twitter": "https://x.com/drunkelephant"},
    {"rank": 88, "brand": "Drybar", "sephora_url": "https://www.sephora.com/brand/drybar", "wikipedia": ""},
    {"rank": 89, "brand": "DUO", "sephora_url": "https://www.sephora.com/brand/duo", "wikipedia": ""},
    {"rank": 90, "brand": "Dyson", "sephora_url": "https://www.sephora.com/brand/dyson", "wikipedia": ""},
    {"rank": 91, "brand": "EADEM", "sephora_url": "https://www.sephora.com/brand/eadem", "wikipedia": ""},
    {"rank": 92, "brand": "Ebb Ocean Club", "sephora_url": "https://www.sephora.com/brand/ebb-ocean-club", "wikipedia": ""},
    {"rank": 93, "brand": "EILISH FRAGRANCES", "sephora_url": "https://www.sephora.com/brand/eilish-fragrances", "wikipedia": ""},
    {"rank": 94, "brand": "Element Eight", "sephora_url": "https://www.sephora.com/brand/element-eight", "wikipedia": ""},
    {"rank": 95, "brand": "Elemis", "sephora_url": "https://www.sephora.com/brand/elemis", "wikipedia": ""},
    {"rank": 96, "brand": "Ellis Brooklyn", "sephora_url": "https://www.sephora.com/brand/ellis-brooklyn", "wikipedia": ""},
    {"rank": 97, "brand": "Emi Jay", "sephora_url": "https://www.sephora.com/brand/emi-jay", "wikipedia": ""},
    {"rank": 98, "brand": "Erborian", "sephora_url": "https://www.sephora.com/brand/erborian", "wikipedia": ""},
    {"rank": 99, "brand": "Estée Lauder", "sephora_url": "https://www.sephora.com/brand/estee-lauder", "wikipedia": "", "instagram": "https://www.instagram.com/esteelauder", "twitter": "https://x.com/EsteeLauder"},
    {"rank": 100, "brand": "Evereden", "sephora_url": "https://www.sephora.com/brand/evereden", "wikipedia": ""},
    {"rank": 101, "brand": "Experiment", "sephora_url": "https://www.sephora.com/brand/experiment", "wikipedia": ""},
    {"rank": 102, "brand": "Fable & Mane", "sephora_url": "https://www.sephora.com/brand/fable-and-mane", "wikipedia": ""},
    {"rank": 103, "brand": "Facile", "sephora_url": "https://www.sephora.com/brand/facile", "wikipedia": ""},
    {"rank": 104, "brand": "Fara Homidi", "sephora_url": "https://www.sephora.com/brand/fara-homidi", "wikipedia": ""},
    {"rank": 105, "brand": "Farmacy", "sephora_url": "https://www.sephora.com/brand/farmacy", "wikipedia": ""},
    {"rank": 106, "brand": "fel beauty", "sephora_url": "https://www.sephora.com/brand/fel-beauty", "wikipedia": ""},
    {"rank": 107, "brand": "Fenty Beauty by Rihanna", "sephora_url": "https://www.sephora.com/brand/fenty-beauty-by-rihanna", "wikipedia": "", "instagram": "https://www.instagram.com/fentybeauty", "twitter": "https://x.com/fentybeauty"},
    {"rank": 108, "brand": "Fig.1", "sephora_url": "https://www.sephora.com/brand/fig-1", "wikipedia": ""},
    {"rank": 109, "brand": "First Aid Beauty", "sephora_url": "https://www.sephora.com/brand/first-aid-beauty", "wikipedia": ""},
    {"rank": 110, "brand": "Flora + Bast", "sephora_url": "https://www.sephora.com/brand/flora-plus-bast", "wikipedia": ""},
    {"rank": 111, "brand": "FlutterHabit", "sephora_url": "https://www.sephora.com/brand/flutterhabit", "wikipedia": ""},
    {"rank": 112, "brand": "FOREO", "sephora_url": "https://www.sephora.com/brand/foreo", "wikipedia": ""},
    {"rank": 113, "brand": "FORVR MOOD", "sephora_url": "https://www.sephora.com/brand/forvr-mood", "wikipedia": ""},
    {"rank": 114, "brand": "Freck Beauty", "sephora_url": "https://www.sephora.com/brand/freck-beauty", "wikipedia": ""},
    {"rank": 115, "brand": "fresh", "sephora_url": "https://www.sephora.com/brand/fresh", "wikipedia": ""},
    {"rank": 116, "brand": "FROMLABS", "sephora_url": "https://www.sephora.com/brand/fromlabs", "wikipedia": ""},
    {"rank": 117, "brand": "FUGAZZI", "sephora_url": "https://www.sephora.com/brand/fugazzi", "wikipedia": ""},
    {"rank": 118, "brand": "ghd", "sephora_url": "https://www.sephora.com/brand/ghd", "wikipedia": ""},
    {"rank": 119, "brand": "Gisou", "sephora_url": "https://www.sephora.com/brand/gisou", "wikipedia": ""},
    {"rank": 120, "brand": "Givenchy", "sephora_url": "https://www.sephora.com/brand/givenchy", "wikipedia": ""},
    {"rank": 121, "brand": "Glamnetic", "sephora_url": "https://www.sephora.com/brand/glamnetic", "wikipedia": ""},
    {"rank": 122, "brand": "Glossier", "sephora_url": "https://www.sephora.com/brand/glossier", "wikipedia": ""},
    {"rank": 123, "brand": "Glow Recipe", "sephora_url": "https://www.sephora.com/brand/glow-recipe", "wikipedia": ""},
    {"rank": 124, "brand": "Grande Cosmetics", "sephora_url": "https://www.sephora.com/brand/grande-cosmetics", "wikipedia": ""},
    {"rank": 125, "brand": "Gucci", "sephora_url": "https://www.sephora.com/brand/gucci", "wikipedia": ""},
    {"rank": 126, "brand": "GUERLAIN", "sephora_url": "https://www.sephora.com/brand/guerlain", "wikipedia": ""},
    {"rank": 127, "brand": "Hanni", "sephora_url": "https://www.sephora.com/brand/hanni", "wikipedia": ""},
    {"rank": 128, "brand": "Hanyul", "sephora_url": "https://www.sephora.com/brand/hanyul", "wikipedia": ""},
    {"rank": 129, "brand": "Harlem Perfume Co.", "sephora_url": "https://www.sephora.com/brand/harlem-perfume-co", "wikipedia": ""},
    {"rank": 130, "brand": "HAUS LABS BY LADY GAGA", "sephora_url": "https://www.sephora.com/brand/haus-labs-by-lady-gaga", "wikipedia": ""},
    {"rank": 131, "brand": "Hello Sunday", "sephora_url": "https://www.sephora.com/brand/hello-sunday", "wikipedia": ""},
    {"rank": 132, "brand": "Henry Rose", "sephora_url": "https://www.sephora.com/brand/henry-rose", "wikipedia": ""},
    {"rank": 133, "brand": "HERMÈS", "sephora_url": "https://www.sephora.com/brand/hermes", "wikipedia": ""},
    {"rank": 134, "brand": "HigherDOSE", "sephora_url": "https://www.sephora.com/brand/higherdose", "wikipedia": ""},
    {"rank": 135, "brand": "Hourglass", "sephora_url": "https://www.sephora.com/brand/hourglass", "wikipedia": ""},
    {"rank": 136, "brand": "House of Lashes", "sephora_url": "https://www.sephora.com/brand/house-of-lashes", "wikipedia": ""},
    {"rank": 137, "brand": "HUDA BEAUTY", "sephora_url": "https://www.sephora.com/brand/huda-beauty", "wikipedia": "", "instagram": "https://www.instagram.com/hudabeauty", "twitter": "https://x.com/hudabeauty"},
    {"rank": 138, "brand": "Hugo Boss", "sephora_url": "https://www.sephora.com/brand/hugo-boss", "wikipedia": ""},
    {"rank": 139, "brand": "HUNG VANNGO BEAUTY", "sephora_url": "https://www.sephora.com/brand/hung-vanngo-beauty", "wikipedia": ""},
    {"rank": 140, "brand": "Hyper Skin", "sephora_url": "https://www.sephora.com/brand/hyper-skin", "wikipedia": ""},
    {"rank": 141, "brand": "Iconic London", "sephora_url": "https://www.sephora.com/brand/iconic-london", "wikipedia": ""},
    {"rank": 142, "brand": "IGK", "sephora_url": "https://www.sephora.com/brand/igk", "wikipedia": ""},
    {"rank": 143, "brand": "ILIA", "sephora_url": "https://www.sephora.com/brand/ilia", "wikipedia": ""},
    {"rank": 144, "brand": "indē wild", "sephora_url": "https://www.sephora.com/brand/inde-wild", "wikipedia": ""},
    {"rank": 145, "brand": "INFLUXIOUS", "sephora_url": "https://www.sephora.com/brand/influxious", "wikipedia": ""},
    {"rank": 146, "brand": "INNBEAUTY PROJECT", "sephora_url": "https://www.sephora.com/brand/innbeauty-project", "wikipedia": ""},
    {"rank": 147, "brand": "innisfree", "sephora_url": "https://www.sephora.com/brand/innisfree", "wikipedia": ""},
    {"rank": 148, "brand": "IOPE", "sephora_url": "https://www.sephora.com/brand/iope", "wikipedia": ""},
    {"rank": 149, "brand": "Iris&Romeo", "sephora_url": "https://www.sephora.com/brand/iris-and-romeo", "wikipedia": ""},
    {"rank": 150, "brand": "ISAMAYA", "sephora_url": "https://www.sephora.com/brand/isamaya", "wikipedia": ""},
    {"rank": 151, "brand": "ISDIN", "sephora_url": "https://www.sephora.com/brand/isdin", "wikipedia": ""},
    {"rank": 152, "brand": "Isle of Paradise", "sephora_url": "https://www.sephora.com/brand/isle-of-paradise", "wikipedia": ""},
    {"rank": 153, "brand": "IT Cosmetics", "sephora_url": "https://www.sephora.com/brand/it-cosmetics", "wikipedia": ""},
    {"rank": 154, "brand": "Jack Black", "sephora_url": "https://www.sephora.com/brand/jack-black", "wikipedia": ""},
    {"rank": 155, "brand": "Jean Paul Gaultier", "sephora_url": "https://www.sephora.com/brand/jean-paul-gaultier", "wikipedia": ""},
    {"rank": 156, "brand": "JIMMY CHOO", "sephora_url": "https://www.sephora.com/brand/jimmy-choo", "wikipedia": ""},
    {"rank": 157, "brand": "Jo Malone London", "sephora_url": "https://www.sephora.com/brand/jo-malone-london", "wikipedia": ""},
    {"rank": 158, "brand": "JOSIE MARAN", "sephora_url": "https://www.sephora.com/brand/josie-maran", "wikipedia": ""},
    {"rank": 159, "brand": "Juicy Couture", "sephora_url": "https://www.sephora.com/brand/juicy-couture", "wikipedia": ""},
    {"rank": 160, "brand": "Juliette Has a Gun", "sephora_url": "https://www.sephora.com/brand/juliette-has-a-gun", "wikipedia": ""},
    {"rank": 161, "brand": "JVN", "sephora_url": "https://www.sephora.com/brand/jvn", "wikipedia": ""},
    {"rank": 162, "brand": "K18 Biomimetic Hairscience", "sephora_url": "https://www.sephora.com/brand/k18-biomimetic-hairscience", "wikipedia": ""},
    {"rank": 163, "brand": "Kaja", "sephora_url": "https://www.sephora.com/brand/kaja", "wikipedia": ""},
    {"rank": 164, "brand": "Kate McLeod", "sephora_url": "https://www.sephora.com/brand/kate-mcleod", "wikipedia": ""},
    {"rank": 165, "brand": "Kate Somerville", "sephora_url": "https://www.sephora.com/brand/kate-somerville", "wikipedia": ""},
    {"rank": 166, "brand": "Katini Skin", "sephora_url": "https://www.sephora.com/brand/katini-skin", "wikipedia": ""},
    {"rank": 167, "brand": "KAYALI", "sephora_url": "https://www.sephora.com/brand/kayali", "wikipedia": ""},
    {"rank": 168, "brand": "Kenra Professional", "sephora_url": "https://www.sephora.com/brand/kenra-professional", "wikipedia": ""},
    {"rank": 169, "brand": "Kérastase", "sephora_url": "https://www.sephora.com/brand/kerastase", "wikipedia": "", "instagram": "https://www.instagram.com/kerastase_official", "twitter": "https://x.com/Kerastase_"},
    {"rank": 170, "brand": "Kiehl's Since 1851", "sephora_url": "https://www.sephora.com/brand/kiehl-s-since-1851", "wikipedia": ""},
    {"rank": 171, "brand": "KILIAN Paris", "sephora_url": "https://www.sephora.com/brand/kilian-paris", "wikipedia": ""},
    {"rank": 172, "brand": "KORA Organics", "sephora_url": "https://www.sephora.com/brand/kora-organics", "wikipedia": ""},
    {"rank": 173, "brand": "KORRES", "sephora_url": "https://www.sephora.com/brand/korres", "wikipedia": ""},
    {"rank": 174, "brand": "Kosas", "sephora_url": "https://www.sephora.com/brand/kosas", "wikipedia": ""},
    {"rank": 175, "brand": "Kulfi", "sephora_url": "https://www.sephora.com/brand/kulfi", "wikipedia": ""},
    {"rank": 176, "brand": "KVD Beauty", "sephora_url": "https://www.sephora.com/brand/kvd-beauty", "wikipedia": ""},
    {"rank": 177, "brand": "L'Occitane", "sephora_url": "https://www.sephora.com/brand/l-occitane", "wikipedia": ""},
    {"rank": 178, "brand": "L'Oréal Professionnel", "sephora_url": "https://www.sephora.com/brand/l-oreal-professionnel", "wikipedia": ""},
    {"rank": 179, "brand": "L'Oréal Professionnel Steampod", "sephora_url": "https://www.sephora.com/brand/l-oreal-professionnel-steampod", "wikipedia": ""},
    {"rank": 180, "brand": "La Mer", "sephora_url": "https://www.sephora.com/brand/la-mer", "wikipedia": ""},
    {"rank": 181, "brand": "Laka", "sephora_url": "https://www.sephora.com/brand/laka", "wikipedia": ""},
    {"rank": 182, "brand": "Lancôme", "sephora_url": "https://www.sephora.com/brand/lancome", "wikipedia": ""},
    {"rank": 183, "brand": "LANEIGE", "sephora_url": "https://www.sephora.com/brand/laneige", "wikipedia": ""},
    {"rank": 184, "brand": "Laura Geller", "sephora_url": "https://www.sephora.com/brand/laura-geller", "wikipedia": ""},
    {"rank": 185, "brand": "Laura Mercier", "sephora_url": "https://www.sephora.com/brand/laura-mercier", "wikipedia": ""},
    {"rank": 186, "brand": "LAWLESS", "sephora_url": "https://www.sephora.com/brand/lawless", "wikipedia": ""},
    {"rank": 187, "brand": "Lilly Lashes", "sephora_url": "https://www.sephora.com/brand/lilly-lashes", "wikipedia": ""},
    {"rank": 188, "brand": "Lion Pose", "sephora_url": "https://www.sephora.com/brand/lion-pose", "wikipedia": ""},
    {"rank": 189, "brand": "Living Proof", "sephora_url": "https://www.sephora.com/brand/living-proof", "wikipedia": ""},
    {"rank": 190, "brand": "LIXR Beauty", "sephora_url": "https://www.sephora.com/brand/lixr-beauty", "wikipedia": ""},
    {"rank": 191, "brand": "LORE", "sephora_url": "https://www.sephora.com/brand/lore", "wikipedia": ""},
    {"rank": 192, "brand": "LoveShackFancy", "sephora_url": "https://www.sephora.com/brand/loveshackfancy", "wikipedia": ""},
    {"rank": 193, "brand": "Luna Daily", "sephora_url": "https://www.sephora.com/brand/luna-daily", "wikipedia": ""},
    {"rank": 194, "brand": "Lux Unfiltered", "sephora_url": "https://www.sephora.com/brand/lux-unfiltered", "wikipedia": ""},
    {"rank": 195, "brand": "LYS Beauty", "sephora_url": "https://www.sephora.com/brand/lys-beauty", "wikipedia": ""},
    {"rank": 196, "brand": "m.ph by Mary Phillips", "sephora_url": "https://www.sephora.com/brand/m-ph-by-mary-phillips", "wikipedia": ""},
    {"rank": 197, "brand": "MAC Cosmetics", "sephora_url": "https://www.sephora.com/brand/mac-cosmetics", "wikipedia": "", "instagram": "https://www.instagram.com/maccosmetics", "twitter": "https://x.com/MACcosmetics"},
    {"rank": 198, "brand": "MAED", "sephora_url": "https://www.sephora.com/brand/maed", "wikipedia": ""},
    {"rank": 199, "brand": "Maison Louis Marie", "sephora_url": "https://www.sephora.com/brand/maison-louis-marie", "wikipedia": ""},
    {"rank": 200, "brand": "Maison Margiela", "sephora_url": "https://www.sephora.com/brand/maison-margiela", "wikipedia": ""},
    {"rank": 201, "brand": "MAKE UP FOR EVER", "sephora_url": "https://www.sephora.com/brand/make-up-for-ever", "wikipedia": "", "instagram": "https://www.instagram.com/makeupforeverofficial", "twitter": "https://x.com/makeupforever"},
    {"rank": 202, "brand": "MAKEUP BY MARIO", "sephora_url": "https://www.sephora.com/brand/makeup-by-mario", "wikipedia": ""},
    {"rank": 203, "brand": "Mane", "sephora_url": "https://www.sephora.com/brand/mane", "wikipedia": ""},
    {"rank": 204, "brand": "Mango People", "sephora_url": "https://www.sephora.com/brand/mango-people", "wikipedia": ""},
    {"rank": 205, "brand": "manucurist", "sephora_url": "https://www.sephora.com/brand/manucurist", "wikipedia": ""},
    {"rank": 206, "brand": "MARA", "sephora_url": "https://www.sephora.com/brand/mara", "wikipedia": ""},
    {"rank": 207, "brand": "Marc Jacobs Beauty", "sephora_url": "https://www.sephora.com/brand/marc-jacobs-beauty", "wikipedia": ""},
    {"rank": 208, "brand": "Mario Badescu", "sephora_url": "https://www.sephora.com/brand/mario-badescu", "wikipedia": ""},
    {"rank": 209, "brand": "MATTER OF FACT", "sephora_url": "https://www.sephora.com/brand/matter-of-fact", "wikipedia": ""},
    {"rank": 210, "brand": "maude", "sephora_url": "https://www.sephora.com/brand/maude", "wikipedia": ""},
    {"rank": 211, "brand": "Medik8", "sephora_url": "https://www.sephora.com/brand/medik8", "wikipedia": ""},
    {"rank": 212, "brand": "Melanin Haircare", "sephora_url": "https://www.sephora.com/brand/melanin-haircare", "wikipedia": ""},
    {"rank": 213, "brand": "Melt Cosmetics", "sephora_url": "https://www.sephora.com/brand/melt-cosmetics", "wikipedia": ""},
    {"rank": 214, "brand": "MERIT", "sephora_url": "https://www.sephora.com/brand/merit", "wikipedia": ""},
    {"rank": 215, "brand": "Messy by Alli Webb", "sephora_url": "https://www.sephora.com/brand/messy-by-alli-webb", "wikipedia": ""},
    {"rank": 216, "brand": "Milk Makeup", "sephora_url": "https://www.sephora.com/brand/milk-makeup", "wikipedia": ""},
    {"rank": 217, "brand": "Miu Miu", "sephora_url": "https://www.sephora.com/brand/miu-miu", "wikipedia": ""},
    {"rank": 218, "brand": "Mizani", "sephora_url": "https://www.sephora.com/brand/mizani", "wikipedia": ""},
    {"rank": 219, "brand": "Montale", "sephora_url": "https://www.sephora.com/brand/montale", "wikipedia": ""},
    {"rank": 220, "brand": "Montblanc", "sephora_url": "https://www.sephora.com/brand/montblanc", "wikipedia": ""},
    {"rank": 221, "brand": "Moon Juice", "sephora_url": "https://www.sephora.com/brand/moon-juice", "wikipedia": ""},
    {"rank": 222, "brand": "Moroccanoil", "sephora_url": "https://www.sephora.com/brand/moroccanoil", "wikipedia": ""},
    {"rank": 223, "brand": "Mother Science", "sephora_url": "https://www.sephora.com/brand/mother-science", "wikipedia": ""},
    {"rank": 224, "brand": "Mugler", "sephora_url": "https://www.sephora.com/brand/mugler", "wikipedia": ""},
    {"rank": 225, "brand": "Murad", "sephora_url": "https://www.sephora.com/brand/murad", "wikipedia": ""},
    {"rank": 226, "brand": "NARS", "sephora_url": "https://www.sephora.com/brand/nars", "wikipedia": "", "instagram": "https://www.instagram.com/narsissist", "twitter": "https://x.com/NARSissist"},
    {"rank": 227, "brand": "NATASHA DENONA", "sephora_url": "https://www.sephora.com/brand/natasha-denona", "wikipedia": ""},
    {"rank": 228, "brand": "Naturally Serious", "sephora_url": "https://www.sephora.com/brand/naturally-serious", "wikipedia": ""},
    {"rank": 229, "brand": "Nécessaire", "sephora_url": "https://www.sephora.com/brand/necessaire", "wikipedia": ""},
    {"rank": 230, "brand": "NEST New York", "sephora_url": "https://www.sephora.com/brand/nest-new-york", "wikipedia": ""},
    {"rank": 231, "brand": "Nette", "sephora_url": "https://www.sephora.com/brand/nette", "wikipedia": ""},
    {"rank": 232, "brand": "NUDESTIX", "sephora_url": "https://www.sephora.com/brand/nudestix", "wikipedia": ""},
    {"rank": 233, "brand": "NuFACE", "sephora_url": "https://www.sephora.com/brand/nuface", "wikipedia": ""},
    {"rank": 234, "brand": "Ogee", "sephora_url": "https://www.sephora.com/brand/ogee", "wikipedia": ""},
    {"rank": 235, "brand": "Olaplex", "sephora_url": "https://www.sephora.com/brand/olaplex", "wikipedia": ""},
    {"rank": 236, "brand": "OLEHENRIKSEN", "sephora_url": "https://www.sephora.com/brand/olehenriksen", "wikipedia": ""},
    {"rank": 237, "brand": "OLIVIAUMMA", "sephora_url": "https://www.sephora.com/brand/oliviaumma", "wikipedia": ""},
    {"rank": 238, "brand": "ONE/SIZE by Patrick Starrr", "sephora_url": "https://www.sephora.com/brand/one-size-by-patrick-starrr", "wikipedia": "", "instagram": "https://www.instagram.com/onesizebeauty", "twitter": "https://x.com/onesizebeauty"},
    {"rank": 239, "brand": "Oribe", "sephora_url": "https://www.sephora.com/brand/oribe", "wikipedia": ""},
    {"rank": 240, "brand": "Origins", "sephora_url": "https://www.sephora.com/brand/origins", "wikipedia": ""},
    {"rank": 241, "brand": "OUAI", "sephora_url": "https://www.sephora.com/brand/ouai", "wikipedia": ""},
    {"rank": 242, "brand": "OUI the People", "sephora_url": "https://www.sephora.com/brand/oui-the-people", "wikipedia": ""},
    {"rank": 243, "brand": "Ouidad", "sephora_url": "https://www.sephora.com/brand/ouidad", "wikipedia": ""},
    {"rank": 244, "brand": "PAT McGRATH LABS", "sephora_url": "https://www.sephora.com/brand/pat-mcgrath-labs", "wikipedia": ""},
    {"rank": 245, "brand": "PATRICK TA", "sephora_url": "https://www.sephora.com/brand/patrick-ta", "wikipedia": ""},
    {"rank": 246, "brand": "PATTERN by Tracee Ellis Ross", "sephora_url": "https://www.sephora.com/brand/pattern-by-tracee-ellis-ross", "wikipedia": ""},
    {"rank": 247, "brand": "Paul Mitchell", "sephora_url": "https://www.sephora.com/brand/paul-mitchell", "wikipedia": ""},
    {"rank": 248, "brand": "Paula's Choice", "sephora_url": "https://www.sephora.com/brand/paula-s-choice", "wikipedia": ""},
    {"rank": 249, "brand": "Peace Out", "sephora_url": "https://www.sephora.com/brand/peace-out", "wikipedia": ""},
    {"rank": 250, "brand": "Peter Thomas Roth", "sephora_url": "https://www.sephora.com/brand/peter-thomas-roth", "wikipedia": ""},
    {"rank": 251, "brand": "PHLUR", "sephora_url": "https://www.sephora.com/brand/phlur", "wikipedia": ""},
    {"rank": 252, "brand": "PHYLA", "sephora_url": "https://www.sephora.com/brand/phyla", "wikipedia": ""},
    {"rank": 253, "brand": "Prada", "sephora_url": "https://www.sephora.com/brand/prada", "wikipedia": ""},
    {"rank": 254, "brand": "Pureology", "sephora_url": "https://www.sephora.com/brand/pureology", "wikipedia": ""},
    {"rank": 255, "brand": "Rabanne", "sephora_url": "https://www.sephora.com/brand/rabanne", "wikipedia": ""},
    {"rank": 256, "brand": "Rahua", "sephora_url": "https://www.sephora.com/brand/rahua", "wikipedia": ""},
    {"rank": 257, "brand": "Ralph Lauren", "sephora_url": "https://www.sephora.com/brand/ralph-lauren", "wikipedia": ""},
    {"rank": 258, "brand": "RANAVAT", "sephora_url": "https://www.sephora.com/brand/ranavat", "wikipedia": ""},
    {"rank": 259, "brand": "Range Beauty", "sephora_url": "https://www.sephora.com/brand/range-beauty", "wikipedia": ""},
    {"rank": 260, "brand": "Rare Beauty by Selena Gomez", "sephora_url": "https://www.sephora.com/brand/rare-beauty-by-selena-gomez", "wikipedia": "", "instagram": "https://www.instagram.com/rarebeauty", "twitter": "https://x.com/rarebeauty"},
    {"rank": 261, "brand": "REFY", "sephora_url": "https://www.sephora.com/brand/refy", "wikipedia": ""},
    {"rank": 262, "brand": "Rejuran", "sephora_url": "https://www.sephora.com/brand/rejuran", "wikipedia": ""},
    {"rank": 263, "brand": "rhode", "sephora_url": "https://www.sephora.com/brand/rhode", "wikipedia": "", "instagram": "https://www.instagram.com/rhode", "twitter": "https://x.com/rhode"},
    {"rank": 264, "brand": "RIES", "sephora_url": "https://www.sephora.com/brand/ries", "wikipedia": ""},
    {"rank": 265, "brand": "ROSE Ingleton MD", "sephora_url": "https://www.sephora.com/brand/rose-ingleton-md", "wikipedia": ""},
    {"rank": 266, "brand": "Rosebud Perfume Co.", "sephora_url": "https://www.sephora.com/brand/rosebud-perfume-co", "wikipedia": ""},
    {"rank": 267, "brand": "Rossano Ferretti Parma", "sephora_url": "https://www.sephora.com/brand/rossano-ferretti-parma", "wikipedia": ""},
    {"rank": 268, "brand": "RŌZ", "sephora_url": "https://www.sephora.com/brand/roz", "wikipedia": ""},
    {"rank": 269, "brand": "RUHVEDA", "sephora_url": "https://www.sephora.com/brand/ruhveda", "wikipedia": ""},
    {"rank": 270, "brand": "Ruka Hair", "sephora_url": "https://www.sephora.com/brand/ruka-hair", "wikipedia": ""},
    {"rank": 271, "brand": "Saie", "sephora_url": "https://www.sephora.com/brand/saie", "wikipedia": ""},
    {"rank": 272, "brand": "Saint Jane", "sephora_url": "https://www.sephora.com/brand/saint-jane", "wikipedia": ""},
    {"rank": 273, "brand": "Salt & Stone", "sephora_url": "https://www.sephora.com/brand/salt-and-stone", "wikipedia": ""},
    {"rank": 274, "brand": "Sarah Creal", "sephora_url": "https://www.sephora.com/brand/sarah-creal", "wikipedia": ""},
    {"rank": 275, "brand": "SEPHORA COLLECTION", "sephora_url": "https://www.sephora.com/brand/sephora-collection", "wikipedia": ""},
    {"rank": 276, "brand": "Sephora Favorites", "sephora_url": "https://www.sephora.com/brand/sephora-favorites", "wikipedia": ""},
    {"rank": 277, "brand": "SEPHORA The Merch Shop", "sephora_url": "https://www.sephora.com/brand/sephora-the-merch-shop", "wikipedia": ""},
    {"rank": 278, "brand": "Shani Darden Skin Care", "sephora_url": "https://www.sephora.com/brand/shani-darden-skin-care", "wikipedia": ""},
    {"rank": 279, "brand": "Shark Beauty", "sephora_url": "https://www.sephora.com/brand/shark-beauty", "wikipedia": ""},
    {"rank": 280, "brand": "SHAZ & KIKS", "sephora_url": "https://www.sephora.com/brand/shaz-and-kiks", "wikipedia": ""},
    {"rank": 281, "brand": "Shiseido", "sephora_url": "https://www.sephora.com/brand/shiseido", "wikipedia": ""},
    {"rank": 282, "brand": "shu uemura", "sephora_url": "https://www.sephora.com/brand/shu-uemura", "wikipedia": ""},
    {"rank": 283, "brand": "Sienna Naturals", "sephora_url": "https://www.sephora.com/brand/sienna-naturals", "wikipedia": ""},
    {"rank": 284, "brand": "SIMIHAZE BEAUTY", "sephora_url": "https://www.sephora.com/brand/simihaze-beauty", "wikipedia": ""},
    {"rank": 285, "brand": "Sincerely Yours", "sephora_url": "https://www.sephora.com/brand/sincerely-yours", "wikipedia": ""},
    {"rank": 286, "brand": "SK-II", "sephora_url": "https://www.sephora.com/brand/sk-ii", "wikipedia": ""},
    {"rank": 287, "brand": "Skinfix", "sephora_url": "https://www.sephora.com/brand/skinfix", "wikipedia": ""},
    {"rank": 288, "brand": "Skylar", "sephora_url": "https://www.sephora.com/brand/skylar", "wikipedia": ""},
    {"rank": 289, "brand": "Slip", "sephora_url": "https://www.sephora.com/brand/slip", "wikipedia": ""},
    {"rank": 290, "brand": "Smile Makers", "sephora_url": "https://www.sephora.com/brand/smile-makers", "wikipedia": ""},
    {"rank": 291, "brand": "SOFIE PAVITT FACE", "sephora_url": "https://www.sephora.com/brand/sofie-pavitt-face", "wikipedia": ""},
    {"rank": 292, "brand": "Soft Services", "sephora_url": "https://www.sephora.com/brand/soft-services", "wikipedia": ""},
    {"rank": 293, "brand": "Sol de Janeiro", "sephora_url": "https://www.sephora.com/brand/sol-de-janeiro", "wikipedia": "", "instagram": "https://www.instagram.com/soldejaneiro", "twitter": "https://x.com/soldejaneiro"},
    {"rank": 294, "brand": "St. Tropez", "sephora_url": "https://www.sephora.com/brand/st-tropez", "wikipedia": ""},
    {"rank": 295, "brand": "stila", "sephora_url": "https://www.sephora.com/brand/stila", "wikipedia": ""},
    {"rank": 296, "brand": "Stripes", "sephora_url": "https://www.sephora.com/brand/stripes", "wikipedia": ""},
    {"rank": 297, "brand": "StriVectin", "sephora_url": "https://www.sephora.com/brand/strivectin", "wikipedia": ""},
    {"rank": 298, "brand": "Sulwhasoo", "sephora_url": "https://www.sephora.com/brand/sulwhasoo", "wikipedia": ""},
    {"rank": 299, "brand": "Summer Fridays", "sephora_url": "https://www.sephora.com/brand/summer-fridays", "wikipedia": ""},
    {"rank": 300, "brand": "SUNDAY II SUNDAY", "sephora_url": "https://www.sephora.com/brand/sunday-ii-sunday", "wikipedia": ""},
    {"rank": 301, "brand": "Sunday Riley", "sephora_url": "https://www.sephora.com/brand/sunday-riley", "wikipedia": ""},
    {"rank": 302, "brand": "Supergoop!", "sephora_url": "https://www.sephora.com/brand/supergoop", "wikipedia": ""},
    {"rank": 303, "brand": "superzero", "sephora_url": "https://www.sephora.com/brand/superzero", "wikipedia": ""},
    {"rank": 304, "brand": "T3", "sephora_url": "https://www.sephora.com/brand/t3", "wikipedia": ""},
    {"rank": 305, "brand": "Tabu", "sephora_url": "https://www.sephora.com/brand/tabu", "wikipedia": ""},
    {"rank": 306, "brand": "tarte", "sephora_url": "https://www.sephora.com/brand/tarte", "wikipedia": "", "instagram": "https://www.instagram.com/tartecosmetics", "twitter": "https://x.com/tartecosmetics"},
    {"rank": 307, "brand": "Tata Harper", "sephora_url": "https://www.sephora.com/brand/tata-harper", "wikipedia": ""},
    {"rank": 308, "brand": "Tatcha", "sephora_url": "https://www.sephora.com/brand/tatcha", "wikipedia": ""},
    {"rank": 309, "brand": "The 7 Virtues", "sephora_url": "https://www.sephora.com/brand/the-7-virtues", "wikipedia": ""},
    {"rank": 310, "brand": "The INKEY List", "sephora_url": "https://www.sephora.com/brand/the-inkey-list", "wikipedia": ""},
    {"rank": 311, "brand": "The Maker", "sephora_url": "https://www.sephora.com/brand/the-maker", "wikipedia": ""},
    {"rank": 312, "brand": "The Ordinary", "sephora_url": "https://www.sephora.com/brand/the-ordinary", "wikipedia": ""},
    {"rank": 313, "brand": "The Original MakeUp Eraser", "sephora_url": "https://www.sephora.com/brand/the-original-makeup-eraser", "wikipedia": ""},
    {"rank": 314, "brand": "THE STEAM BAR", "sephora_url": "https://www.sephora.com/brand/the-steam-bar", "wikipedia": ""},
    {"rank": 315, "brand": "Then I Met You", "sephora_url": "https://www.sephora.com/brand/then-i-met-you", "wikipedia": ""},
    {"rank": 316, "brand": "Therabody", "sephora_url": "https://www.sephora.com/brand/therabody", "wikipedia": ""},
    {"rank": 317, "brand": "TOM FORD", "sephora_url": "https://www.sephora.com/brand/tom-ford", "wikipedia": "", "instagram": "https://www.instagram.com/tomfordbeauty", "twitter": "https://x.com/TOMFORD"},
    {"rank": 318, "brand": "Too Faced", "sephora_url": "https://www.sephora.com/brand/too-faced", "wikipedia": "", "instagram": "https://www.instagram.com/toofaced", "twitter": "https://x.com/toofaced"},
    {"rank": 319, "brand": "Topicals", "sephora_url": "https://www.sephora.com/brand/topicals", "wikipedia": ""},
    {"rank": 320, "brand": "Torriden", "sephora_url": "https://www.sephora.com/brand/torriden", "wikipedia": ""},
    {"rank": 321, "brand": "Touchland", "sephora_url": "https://www.sephora.com/brand/touchland", "wikipedia": ""},
    {"rank": 322, "brand": "Tower 28 Beauty", "sephora_url": "https://www.sephora.com/brand/tower-28-beauty", "wikipedia": ""},
    {"rank": 323, "brand": "TWEEZERMAN", "sephora_url": "https://www.sephora.com/brand/tweezerman", "wikipedia": ""},
    {"rank": 324, "brand": "U Beauty", "sephora_url": "https://www.sephora.com/brand/u-beauty", "wikipedia": ""},
    {"rank": 325, "brand": "Ultra Violette", "sephora_url": "https://www.sephora.com/brand/ultra-violette", "wikipedia": ""},
    {"rank": 326, "brand": "UNITE Hair", "sephora_url": "https://www.sephora.com/brand/unite-hair", "wikipedia": ""},
    {"rank": 327, "brand": "UNOVE", "sephora_url": "https://www.sephora.com/brand/unove", "wikipedia": ""},
    {"rank": 328, "brand": "Urban Decay", "sephora_url": "https://www.sephora.com/brand/urban-decay", "wikipedia": "", "instagram": "https://www.instagram.com/urbandecaycosmetics", "twitter": "https://x.com/UrbanDecay"},
    {"rank": 329, "brand": "Vacation", "sephora_url": "https://www.sephora.com/brand/vacation", "wikipedia": ""},
    {"rank": 330, "brand": "Valentino", "sephora_url": "https://www.sephora.com/brand/valentino", "wikipedia": ""},
    {"rank": 331, "brand": "Vegamour", "sephora_url": "https://www.sephora.com/brand/vegamour", "wikipedia": ""},
    {"rank": 332, "brand": "Velour Lashes", "sephora_url": "https://www.sephora.com/brand/velour-lashes", "wikipedia": ""},
    {"rank": 333, "brand": "Verb", "sephora_url": "https://www.sephora.com/brand/verb", "wikipedia": ""},
    {"rank": 334, "brand": "Versace", "sephora_url": "https://www.sephora.com/brand/versace", "wikipedia": ""},
    {"rank": 335, "brand": "Viktor&Rolf", "sephora_url": "https://www.sephora.com/brand/viktor-and-rolf", "wikipedia": ""},
    {"rank": 336, "brand": "VIOLETTE_FR", "sephora_url": "https://www.sephora.com/brand/violette-fr", "wikipedia": ""},
    {"rank": 337, "brand": "Viori", "sephora_url": "https://www.sephora.com/brand/viori", "wikipedia": ""},
    {"rank": 338, "brand": "Virtue", "sephora_url": "https://www.sephora.com/brand/virtue", "wikipedia": ""},
    {"rank": 339, "brand": "VOLUSPA", "sephora_url": "https://www.sephora.com/brand/voluspa", "wikipedia": ""},
    {"rank": 340, "brand": "Wander Beauty", "sephora_url": "https://www.sephora.com/brand/wander-beauty", "wikipedia": ""},
    {"rank": 341, "brand": "Westman Atelier", "sephora_url": "https://www.sephora.com/brand/westman-atelier", "wikipedia": ""},
    {"rank": 342, "brand": "Whipped", "sephora_url": "https://www.sephora.com/brand/whipped", "wikipedia": ""},
    {"rank": 343, "brand": "Wonderskin", "sephora_url": "https://www.sephora.com/brand/wonderskin", "wikipedia": ""},
    {"rank": 344, "brand": "World of Chris Collins", "sephora_url": "https://www.sephora.com/brand/world-of-chris-collins", "wikipedia": ""},
    {"rank": 345, "brand": "YISE Beauty", "sephora_url": "https://www.sephora.com/brand/yise-beauty", "wikipedia": ""},
    {"rank": 346, "brand": "Youth To The People", "sephora_url": "https://www.sephora.com/brand/youth-to-the-people", "wikipedia": ""},
    {"rank": 347, "brand": "Yves Saint Laurent", "sephora_url": "https://www.sephora.com/brand/yves-saint-laurent", "wikipedia": "", "instagram": "https://www.instagram.com/yslbeauty", "twitter": "https://x.com/YSLBeauty"},
]
