"""Notable streaming media services. Source: Wikipedia (List of streaming media services)."""
STREAMING_EDITION = "Notable streaming services"
STREAMING_SOURCE_URL = "https://en.wikipedia.org/wiki/List_of_streaming_media_services"
W="https://en.wikipedia.org/wiki/"
def _t(rank,name,typ,website,wiki):
    return {"rank":rank,"service":name,"type":typ,"website":website,"wikipedia":W+wiki}
STREAMING_SERVICES=[
 _t(1,"Netflix","Video (SVOD)","https://www.netflix.com/","Netflix"),
 _t(2,"Disney+","Video (SVOD)","https://www.disneyplus.com/","Disney+"),
 _t(3,"Amazon Prime Video","Video (SVOD)","https://www.primevideo.com/","Prime_Video"),
 _t(4,"Max","Video (SVOD)","https://www.max.com/","Max_(streaming_service)"),
 _t(5,"Hulu","Video (SVOD)","https://www.hulu.com/","Hulu"),
 _t(6,"Apple TV+","Video (SVOD)","https://tv.apple.com/","Apple_TV+"),
 _t(7,"Paramount+","Video (SVOD)","https://www.paramountplus.com/","Paramount+"),
 _t(8,"Peacock","Video (SVOD)","https://www.peacocktv.com/","Peacock_(streaming_service)"),
 _t(9,"YouTube","Video","https://www.youtube.com/","YouTube"),
 _t(10,"YouTube TV","Live TV","https://tv.youtube.com/","YouTube_TV"),
 _t(11,"Crunchyroll","Video (anime)","https://www.crunchyroll.com/","Crunchyroll"),
 _t(12,"Tubi","Video (AVOD)","https://tubitv.com/","Tubi"),
 _t(13,"Pluto TV","FAST","https://pluto.tv/","Pluto_TV"),
 _t(14,"The Roku Channel","FAST","https://therokuchannel.roku.com/","The_Roku_Channel"),
 _t(15,"Sling TV","Live TV","https://www.sling.com/","Sling_TV"),
 _t(16,"Fubo","Live TV","https://www.fubo.tv/","FuboTV"),
 _t(17,"Starz","Video (SVOD)","https://www.starz.com/","Starz"),
 _t(18,"BritBox","Video (SVOD)","https://www.britbox.com/","BritBox"),
 _t(19,"Discovery+","Video (SVOD)","https://www.discoveryplus.com/","Discovery+"),
 _t(20,"ESPN+","Sports","https://plus.espn.com/","ESPN+"),
 _t(21,"DAZN","Sports","https://www.dazn.com/","DAZN"),
 _t(22,"Mubi","Video (film)","https://mubi.com/","Mubi"),
 _t(23,"BBC iPlayer","Video","https://www.bbc.co.uk/iplayer","BBC_iPlayer"),
 _t(24,"ITVX","Video","https://www.itv.com/","ITVX"),
 _t(25,"JioHotstar","Video (SVOD)","https://www.hotstar.com/","JioHotstar"),
 _t(26,"Bilibili","Video","https://www.bilibili.com/","Bilibili"),
 _t(27,"iQIYI","Video (SVOD)","https://www.iq.com/","IQIYI"),
 _t(28,"Tencent Video","Video (SVOD)","https://v.qq.com/","Tencent_Video"),
 _t(29,"Youku","Video","https://www.youku.com/","Youku"),
 _t(30,"Rakuten Viki","Video","https://www.viki.com/","Viki"),
 _t(31,"Dailymotion","Video","https://www.dailymotion.com/","Dailymotion"),
 _t(32,"Vimeo","Video","https://vimeo.com/","Vimeo"),
 _t(33,"Twitch","Live streaming","https://www.twitch.tv/","Twitch_(service)"),
 _t(34,"Kick","Live streaming","https://kick.com/","Kick_(service)"),
 _t(35,"Rumble","Video","https://rumble.com/","Rumble_(website)"),
 _t(36,"Spotify","Music","https://www.spotify.com/","Spotify"),
 _t(37,"Apple Music","Music","https://music.apple.com/","Apple_Music"),
 _t(38,"Amazon Music","Music","https://music.amazon.com/","Amazon_Music"),
 _t(39,"YouTube Music","Music","https://music.youtube.com/","YouTube_Music"),
 _t(40,"Tidal","Music","https://tidal.com/","Tidal_(service)"),
 _t(41,"Deezer","Music","https://www.deezer.com/","Deezer"),
 _t(42,"SoundCloud","Music","https://soundcloud.com/","SoundCloud"),
 _t(43,"Pandora","Music","https://www.pandora.com/","Pandora_(service)"),
 _t(44,"Audible","Audio (audiobooks)","https://www.audible.com/","Audible_(service)"),
 _t(45,"Patreon","Membership","https://www.patreon.com/","Patreon"),
]
