"""
Baked-in Top Twitch Streamers reference data: the top channels from
TwitchTracker's overall ranking, with each channel's 30-day average viewers,
all-time peak viewers, hours watched, Twitch channel link, social handles
(X/Twitter, YouTube, etc.) and Wikipedia page (where one exists).

TwitchTracker's "Overall Rank" blends average concurrent viewers, followers,
views and stream time over the trailing 30 days. The page is JavaScript-rendered
and the figures move daily, so this is a curated snapshot stored here and
refreshed periodically. Snapshot window: July 2026.

Notes:
  - avg_viewers and peak_viewers are exact figures from the source table.
  - hours_watched is rounded (the source lists it abbreviated, e.g. "10.9M"),
    so treat it as approximate to 3 significant figures.
  - Social accounts are official channels where verified; the rest are
    auto-generated best-guesses by tools/socials.py and may not all resolve.
  - Wikipedia links are direct article URLs.

Source: https://twitchtracker.com/channels/ranking
"""

TWITCH_EDITION = "30-day overall rank"
TWITCH_SOURCE_URL = "https://twitchtracker.com/channels/ranking"

TOP_TWITCH_STREAMERS = [
    {"position": 1, "channel": "KaiCenat", "avg_viewers": 393387, "peak_viewers": 1005331, "hours_watched": 10900000, "twitch": "https://www.twitch.tv/kaicenat", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Kai_Cenat"},
    {"position": 2, "channel": "Caedrel", "avg_viewers": 73163, "peak_viewers": 422292, "hours_watched": 15100000, "twitch": "https://www.twitch.tv/caedrel", "twitter": "https://x.com/Caedrel", "youtube": "https://www.youtube.com/caedrel", "wikipedia": "https://en.wikipedia.org/wiki/Caedrel"},
    {"position": 3, "channel": "Jynxzi", "avg_viewers": 49023, "peak_viewers": 500919, "hours_watched": 12300000, "twitch": "https://www.twitch.tv/jynxzi", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Jynxzi"},
    {"position": 4, "channel": "stableronaldo", "avg_viewers": 46900, "peak_viewers": 168044, "hours_watched": 9850000, "twitch": "https://www.twitch.tv/stableronaldo", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 5, "channel": "TheBurntPeanut", "avg_viewers": 34711, "peak_viewers": 352502, "hours_watched": 8110000, "twitch": "https://www.twitch.tv/theburntpeanut", "youtube": "https://www.youtube.com/@TheBurntPeanut", "twitter": "", "wikipedia": ""},
    {"position": 6, "channel": "Lacy", "avg_viewers": 31534, "peak_viewers": 151465, "hours_watched": 7560000, "twitch": "https://www.twitch.tv/lacy", "twitter": "https://x.com/LacyHimself", "tiktok": "https://www.tiktok.com/@lacy", "youtube": "", "wikipedia": ""},
    {"position": 7, "channel": "加藤純一うん〇ちゃん", "avg_viewers": 35599, "peak_viewers": 292323, "hours_watched": 6300000, "twitch": "https://www.twitch.tv/kato_junichi0817", "twitter": "https://x.com/unkochan1234567", "youtube": "https://www.youtube.com/channel/UCZetZElUvdElPrcstRjl9DA", "wikipedia": "https://en.wikipedia.org/wiki/Junichi_Kato_(streamer)"},
    {"position": 8, "channel": "Warframe", "avg_viewers": 186253, "peak_viewers": 457282, "hours_watched": 3070000, "twitch": "https://www.twitch.tv/warframe", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Warframe"},
    {"position": 9, "channel": "Inoxtag", "avg_viewers": 46862, "peak_viewers": 436418, "hours_watched": 5540000, "twitch": "https://www.twitch.tv/inoxtag", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 10, "channel": "HasanAbi", "avg_viewers": 26271, "peak_viewers": 357084, "hours_watched": 5840000, "twitch": "https://www.twitch.tv/hasanabi", "youtube": "https://www.youtube.com/channel/UCtoaZpBnrd0lhycxYJ4MNOQ", "twitter": "", "wikipedia": "https://en.wikipedia.org/wiki/Hasan_Piker"},
    {"position": 11, "channel": "zackrawrr", "avg_viewers": 33582, "peak_viewers": 346836, "hours_watched": 5660000, "twitch": "https://www.twitch.tv/zackrawrr", "twitter": "https://x.com/asmongold", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Asmongold"},
    {"position": 12, "channel": "caseoh_", "avg_viewers": 59278, "peak_viewers": 299903, "hours_watched": 5150000, "twitch": "https://www.twitch.tv/caseoh_", "youtube": "https://www.youtube.com/channel/UC63anZxfVGHUEmfBAf5w7pw", "twitter": "", "wikipedia": ""},
    {"position": 13, "channel": "Suburbbaby", "avg_viewers": 27290, "peak_viewers": 195356, "hours_watched": 5680000, "twitch": "https://www.twitch.tv/suburbbaby", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 14, "channel": "GamesDoneQuick", "avg_viewers": 11363, "peak_viewers": 247432, "hours_watched": 5670000, "twitch": "https://www.twitch.tv/gamesdonequick", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Games_Done_Quick"},
    {"position": 15, "channel": "eliasn97", "avg_viewers": 34010, "peak_viewers": 232503, "hours_watched": 5080000, "twitch": "https://www.twitch.tv/eliasn97", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 16, "channel": "StRoGo", "avg_viewers": 44480, "peak_viewers": 322154, "hours_watched": 4820000, "twitch": "https://www.twitch.tv/strogo", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 17, "channel": "jasontheween", "avg_viewers": 22709, "peak_viewers": 161863, "hours_watched": 4960000, "twitch": "https://www.twitch.tv/jasontheween", "instagram": "https://www.instagram.com/jasontheween", "twitter": "https://x.com/jasontheween", "youtube": "https://www.youtube.com/@jasontheween", "tiktok": "https://www.tiktok.com/@jasontheween", "wikipedia": "https://en.wikipedia.org/wiki/Jason_Nguyen"},
    {"position": 18, "channel": "fps_shaka", "avg_viewers": 15856, "peak_viewers": 125341, "hours_watched": 4720000, "twitch": "https://www.twitch.tv/fps_shaka", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 19, "channel": "stylishnoob4", "avg_viewers": 16953, "peak_viewers": 112628, "hours_watched": 4640000, "twitch": "https://www.twitch.tv/stylishnoob4", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 20, "channel": "2xRaKai", "avg_viewers": 51990, "peak_viewers": 233463, "hours_watched": 3520000, "twitch": "https://www.twitch.tv/2xrakai", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 21, "channel": "PlaqueBoyMax", "avg_viewers": 25947, "peak_viewers": 196138, "hours_watched": 3900000, "twitch": "https://www.twitch.tv/plaqueboymax", "instagram": "https://www.instagram.com/plaqueboymax", "twitter": "https://x.com/plaqueboymax", "youtube": "https://www.youtube.com/@plaqueboymax", "wikipedia": "https://en.wikipedia.org/wiki/PlaqueBoyMax"},
    {"position": 22, "channel": "Tumblurr", "avg_viewers": 33425, "peak_viewers": 346842, "hours_watched": 3520000, "twitch": "https://www.twitch.tv/tumblurr", "twitter": "https://x.com/sdrogoblur", "youtube": "", "wikipedia": ""},
    {"position": 23, "channel": "xQc", "avg_viewers": 21323, "peak_viewers": 336323, "hours_watched": 3700000, "twitch": "https://www.twitch.tv/xqc", "twitter": "https://x.com/xQc", "youtube": "https://www.youtube.com/channel/UCmDTrq0LNgPodDOFZiSbsww", "wikipedia": "https://en.wikipedia.org/wiki/XQc"},
    {"position": 24, "channel": "布団ちゃんと申します", "avg_viewers": 15382, "peak_viewers": 42637, "hours_watched": 3680000, "twitch": "", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 25, "channel": "Gotaga", "avg_viewers": 22461, "peak_viewers": 405271, "hours_watched": 3360000, "twitch": "https://www.twitch.tv/gotaga", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 26, "channel": "summit1g", "avg_viewers": 10184, "peak_viewers": 310998, "hours_watched": 3570000, "twitch": "https://www.twitch.tv/summit1g", "twitter": "https://x.com/summit1g", "youtube": "https://www.youtube.com/summit1g", "wikipedia": "https://en.wikipedia.org/wiki/Summit1g"},
    {"position": 27, "channel": "ohnePixel", "avg_viewers": 109514, "peak_viewers": 298362, "hours_watched": 1520000, "twitch": "https://www.twitch.tv/ohnepixel", "twitter": "https://x.com/ohnePixel", "youtube": "https://www.youtube.com/@ohnepixel", "wikipedia": "https://en.wikipedia.org/wiki/OhnePixel"},
    {"position": 28, "channel": "KanelJoseph", "avg_viewers": 31331, "peak_viewers": 56681, "hours_watched": 2830000, "twitch": "https://www.twitch.tv/kaneljoseph", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 29, "channel": "Rainbow6", "avg_viewers": 11337, "peak_viewers": 191703, "hours_watched": 3150000, "twitch": "https://www.twitch.tv/rainbow6", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 30, "channel": "Riot Games", "avg_viewers": 29607, "peak_viewers": 854781, "hours_watched": 2440000, "twitch": "https://www.twitch.tv/riotgames", "twitter": "https://x.com/riotgames", "youtube": "https://www.youtube.com/riotgames", "wikipedia": "https://en.wikipedia.org/wiki/Riot_Games"},
    {"position": 31, "channel": "Solo", "avg_viewers": 16962, "peak_viewers": 70039, "hours_watched": 2640000, "twitch": "https://www.twitch.tv/solo", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 32, "channel": "Rubius", "avg_viewers": 27324, "peak_viewers": 383747, "hours_watched": 2440000, "twitch": "https://www.twitch.tv/rubius", "twitter": "https://x.com/Rubiu5", "youtube": "https://www.youtube.com/user/elrubiusOMG", "wikipedia": "https://en.wikipedia.org/wiki/El_Rubius"},
    {"position": 33, "channel": "Kamet0", "avg_viewers": 24496, "peak_viewers": 419458, "hours_watched": 2480000, "twitch": "https://www.twitch.tv/kamet0", "facebook": "https://www.facebook.com/Kamet0", "instagram": "https://www.instagram.com/kametolol", "twitter": "https://x.com/Kammeto", "youtube": "https://www.youtube.com/channel/UC-bQgl7oy_rEk05rNWYXafA", "wikipedia": ""},
    {"position": 34, "channel": "ESLCS", "avg_viewers": 3848, "peak_viewers": 562080, "hours_watched": 2770000, "twitch": "https://www.twitch.tv/eslcs", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 35, "channel": "chche999", "avg_viewers": 106439, "peak_viewers": 374671, "hours_watched": 718000, "twitch": "https://www.twitch.tv/chche999", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 36, "channel": "anarabdullaev", "avg_viewers": 28887, "peak_viewers": 110077, "hours_watched": 2190000, "twitch": "https://www.twitch.tv/anarabdullaev", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 37, "channel": "JLTomy", "avg_viewers": 12150, "peak_viewers": 261719, "hours_watched": 2490000, "twitch": "https://www.twitch.tv/jltomy", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 38, "channel": "yourragegaming", "avg_viewers": 21918, "peak_viewers": 264495, "hours_watched": 2300000, "twitch": "https://www.twitch.tv/yourragegaming", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 39, "channel": "cs2_paragon_ru", "avg_viewers": 78162, "peak_viewers": 136360, "hours_watched": 1180000, "twitch": "https://www.twitch.tv/cs2_paragon_ru", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 40, "channel": "ow_esports", "avg_viewers": 36001, "peak_viewers": 373393, "hours_watched": 1920000, "twitch": "https://www.twitch.tv/ow_esports", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 41, "channel": "otplol_", "avg_viewers": 3498, "peak_viewers": 204072, "hours_watched": 2490000, "twitch": "https://www.twitch.tv/otplol_", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 42, "channel": "zarbex", "avg_viewers": 17403, "peak_viewers": 58722, "hours_watched": 2150000, "twitch": "https://www.twitch.tv/zarbex", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 43, "channel": "ibai", "avg_viewers": 17178, "peak_viewers": 9189762, "hours_watched": 2050000, "twitch": "https://www.twitch.tv/ibai", "twitter": "https://x.com/IbaiLlanos", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Ibai_Llanos"},
    {"position": 44, "channel": "MOONMOON", "avg_viewers": 12400, "peak_viewers": 42066, "hours_watched": 2070000, "twitch": "https://www.twitch.tv/moonmoon", "twitter": "https://x.com/MOONMOON_OW", "youtube": "", "wikipedia": ""},
    {"position": 45, "channel": "wardrobewinter", "avg_viewers": 16012, "peak_viewers": 54000, "hours_watched": 1920000, "twitch": "https://www.twitch.tv/wardrobewinter", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 46, "channel": "k4sen", "avg_viewers": 19329, "peak_viewers": 148289, "hours_watched": 1830000, "twitch": "https://www.twitch.tv/k4sen", "twitter": "https://x.com/thek4sen", "youtube": "", "wikipedia": ""},
    {"position": 47, "channel": "YonnaJay", "avg_viewers": 15070, "peak_viewers": 55440, "hours_watched": 1900000, "twitch": "https://www.twitch.tv/yonnajay", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 48, "channel": "LIRIK", "avg_viewers": 12431, "peak_viewers": 89170, "hours_watched": 1920000, "twitch": "https://www.twitch.tv/lirik", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 49, "channel": "dota2_paragon_ru", "avg_viewers": 18464, "peak_viewers": 263498, "hours_watched": 1760000, "twitch": "https://www.twitch.tv/dota2_paragon_ru", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 50, "channel": "Marlon", "avg_viewers": 12130, "peak_viewers": 97174, "hours_watched": 1860000, "twitch": "https://www.twitch.tv/marlon", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 51, "channel": "Trymacs", "avg_viewers": 11696, "peak_viewers": 365000, "hours_watched": 1870000, "twitch": "https://www.twitch.tv/trymacs", "instagram": "https://www.instagram.com/trymacs", "twitter": "https://x.com/Trymacs", "youtube": "https://www.youtube.com/@Trymacs", "wikipedia": ""},
    {"position": 52, "channel": "buster", "avg_viewers": 32727, "peak_viewers": 758101, "hours_watched": 1460000, "twitch": "https://www.twitch.tv/buster", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 53, "channel": "gon_vl", "avg_viewers": 15466, "peak_viewers": 71271, "hours_watched": 1750000, "twitch": "https://www.twitch.tv/gon_vl", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 54, "channel": "HutchMF", "avg_viewers": 7763, "peak_viewers": 23467, "hours_watched": 1880000, "twitch": "https://www.twitch.tv/hutchmf", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 55, "channel": "Recrent", "avg_viewers": 7782, "peak_viewers": 119109, "hours_watched": 1870000, "twitch": "https://www.twitch.tv/recrent", "instagram": "https://www.instagram.com/recrent.twitch", "twitter": "https://x.com/Recrent_", "youtube": "https://www.youtube.com/channel/UCw_09chvmXy_zZJz2Tj2-mg", "wikipedia": ""},
    {"position": 56, "channel": "DDG", "avg_viewers": 16153, "peak_viewers": 205741, "hours_watched": 1690000, "twitch": "https://www.twitch.tv/ddg", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 57, "channel": "alanzoka", "avg_viewers": 13071, "peak_viewers": 147051, "hours_watched": 1740000, "twitch": "https://www.twitch.tv/alanzoka", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 58, "channel": "NoWay4u_Sir", "avg_viewers": 10356, "peak_viewers": 49218, "hours_watched": 1780000, "twitch": "https://www.twitch.tv/noway4u_sir", "instagram": "https://www.instagram.com/sir_noway4u", "twitter": "https://x.com/noway4u_sir", "youtube": "https://www.youtube.com/@Noway4u", "tiktok": "https://www.tiktok.com/@NoWay4U", "wikipedia": ""},
    {"position": 59, "channel": "TheBurntPeanut_247", "avg_viewers": 2645, "peak_viewers": 19977, "hours_watched": 1900000, "twitch": "https://www.twitch.tv/theburntpeanut_247", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 60, "channel": "Fanum", "avg_viewers": 39423, "peak_viewers": 190987, "hours_watched": 1170000, "twitch": "https://www.twitch.tv/fanum", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Fanum_(streamer)"},
    {"position": 61, "channel": "OW_ESPORTS_JP", "avg_viewers": 17732, "peak_viewers": 55487, "hours_watched": 1530000, "twitch": "https://www.twitch.tv/ow_esports_jp", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 62, "channel": "Cinna", "avg_viewers": 10950, "peak_viewers": 67502, "hours_watched": 1660000, "twitch": "https://www.twitch.tv/cinna", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 63, "channel": "GOFNS", "avg_viewers": 21271, "peak_viewers": 89325, "hours_watched": 1460000, "twitch": "https://www.twitch.tv/gofns", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 64, "channel": "evelone2004", "avg_viewers": 52766, "peak_viewers": 484552, "hours_watched": 811000, "twitch": "https://www.twitch.tv/evelone2004", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 65, "channel": "sasavot", "avg_viewers": 13613, "peak_viewers": 99873, "hours_watched": 1560000, "twitch": "https://www.twitch.tv/sasavot", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 66, "channel": "funnymike", "avg_viewers": 14571, "peak_viewers": 212864, "hours_watched": 1540000, "twitch": "https://www.twitch.tv/funnymike", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 67, "channel": "Ludwig", "avg_viewers": 14964, "peak_viewers": 165293, "hours_watched": 1530000, "twitch": "https://www.twitch.tv/ludwig", "twitter": "https://x.com/LudwigAhgren", "youtube": "https://www.youtube.com/@ludwig", "wikipedia": "https://en.wikipedia.org/wiki/Ludwig_Ahgren"},
    {"position": 68, "channel": "Elajjaz", "avg_viewers": 7822, "peak_viewers": 24097, "hours_watched": 1620000, "twitch": "https://www.twitch.tv/elajjaz", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 69, "channel": "deepins02", "avg_viewers": 16581, "peak_viewers": 126995, "hours_watched": 1450000, "twitch": "https://www.twitch.tv/deepins02", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 70, "channel": "sasatikk", "avg_viewers": 8490, "peak_viewers": 41391, "hours_watched": 1610000, "twitch": "https://www.twitch.tv/sasatikk", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 71, "channel": "Agent00", "avg_viewers": 10498, "peak_viewers": 128313, "hours_watched": 1520000, "twitch": "https://www.twitch.tv/agent00", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 72, "channel": "Peereira7", "avg_viewers": 11202, "peak_viewers": 145627, "hours_watched": 1500000, "twitch": "https://www.twitch.tv/peereira7", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 73, "channel": "Joe_Bartolozzi", "avg_viewers": 16921, "peak_viewers": 39081, "hours_watched": 1390000, "twitch": "https://www.twitch.tv/joe_bartolozzi", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 74, "channel": "betboom_dota_ru", "avg_viewers": 5684, "peak_viewers": 33016, "hours_watched": 1580000, "twitch": "https://www.twitch.tv/betboom_dota_ru", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 75, "channel": "MontanaBlack88", "avg_viewers": 25079, "peak_viewers": 371076, "hours_watched": 1190000, "twitch": "https://www.twitch.tv/montanablack88", "instagram": "https://www.instagram.com/montanablack88", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 76, "channel": "EWROON", "avg_viewers": 10978, "peak_viewers": 34314, "hours_watched": 1450000, "twitch": "https://www.twitch.tv/ewroon", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 77, "channel": "OldSchoolRS", "avg_viewers": 53811, "peak_viewers": 88493, "hours_watched": 613000, "twitch": "https://www.twitch.tv/oldschoolrs", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 78, "channel": "バトラ", "avg_viewers": 8327, "peak_viewers": 43032, "hours_watched": 1450000, "twitch": "https://www.twitch.tv/batora324", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 79, "channel": "GRONKH", "avg_viewers": 14209, "peak_viewers": 115784, "hours_watched": 1330000, "twitch": "https://www.twitch.tv/gronkh", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 80, "channel": "Quin69", "avg_viewers": 7179, "peak_viewers": 44153, "hours_watched": 1450000, "twitch": "https://www.twitch.tv/quin69", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 81, "channel": "bratishkinoff", "avg_viewers": 11636, "peak_viewers": 146916, "hours_watched": 1340000, "twitch": "https://www.twitch.tv/bratishkinoff", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 82, "channel": "CohhCarnage", "avg_viewers": 7568, "peak_viewers": 70985, "hours_watched": 1410000, "twitch": "https://www.twitch.tv/cohhcarnage", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 83, "channel": "Aspen", "avg_viewers": 6163, "peak_viewers": 28543, "hours_watched": 1430000, "twitch": "https://www.twitch.tv/aspen", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 84, "channel": "coldified", "avg_viewers": 12528, "peak_viewers": 74034, "hours_watched": 1300000, "twitch": "https://www.twitch.tv/coldified", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 85, "channel": "たいじ_たいちゃんねる", "avg_viewers": 9042, "peak_viewers": 91335, "hours_watched": 1370000, "twitch": "https://www.twitch.tv/yaritaiji", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 86, "channel": "auronplay", "avg_viewers": 35121, "peak_viewers": 602038, "hours_watched": 862000, "twitch": "https://www.twitch.tv/auronplay", "twitter": "https://x.com/auronplay", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/AuronPlay"},
    {"position": 87, "channel": "EWC_LegionGauntlet_EN", "avg_viewers": 7796, "peak_viewers": 74181, "hours_watched": 1380000, "twitch": "https://www.twitch.tv/ewc_legiongauntlet_en", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 88, "channel": "Emongg", "avg_viewers": 6168, "peak_viewers": 78947, "hours_watched": 1410000, "twitch": "https://www.twitch.tv/emongg", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 89, "channel": "lolesportstw", "avg_viewers": 16142, "peak_viewers": 165491, "hours_watched": 1210000, "twitch": "https://www.twitch.tv/lolesportstw", "instagram": "https://www.instagram.com/lolesportstw", "twitter": "https://x.com/lolesportstw", "youtube": "", "wikipedia": ""},
    {"position": 90, "channel": "aslanshukasha", "avg_viewers": 8071, "peak_viewers": 21922, "hours_watched": 1340000, "twitch": "https://www.twitch.tv/aslanshukasha", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 91, "channel": "AlveusSanctuary", "avg_viewers": 2019, "peak_viewers": 14693, "hours_watched": 1450000, "twitch": "https://www.twitch.tv/alveussanctuary", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 92, "channel": "bySL4M", "avg_viewers": 43727, "peak_viewers": 106769, "hours_watched": 654000, "twitch": "https://www.twitch.tv/bysl4m", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 93, "channel": "T2x2", "avg_viewers": 11730, "peak_viewers": 46612, "hours_watched": 1270000, "twitch": "https://www.twitch.tv/t2x2", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 94, "channel": "Emiru", "avg_viewers": 11217, "peak_viewers": 61031, "hours_watched": 1270000, "twitch": "https://www.twitch.tv/emiru", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 95, "channel": "forsen", "avg_viewers": 7533, "peak_viewers": 85620, "hours_watched": 1290000, "twitch": "https://www.twitch.tv/forsen", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Forsen"},
    {"position": 96, "channel": "NeVeR_LosEs", "avg_viewers": 6683, "peak_viewers": 31336, "hours_watched": 1300000, "twitch": "https://www.twitch.tv/never_loses", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 97, "channel": "Caedrel247", "avg_viewers": 1920, "peak_viewers": 32802, "hours_watched": 1380000, "twitch": "https://www.twitch.tv/caedrel247", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 98, "channel": "angryginge13", "avg_viewers": 8721, "peak_viewers": 84126, "hours_watched": 1240000, "twitch": "https://www.twitch.tv/angryginge13", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 99, "channel": "Jinnytty", "avg_viewers": 3730, "peak_viewers": 26902, "hours_watched": 1330000, "twitch": "https://www.twitch.tv/jinnytty", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 100, "channel": "Stray228", "avg_viewers": 7816, "peak_viewers": 52950, "hours_watched": 1240000, "twitch": "https://www.twitch.tv/stray228", "twitter": "", "youtube": "", "wikipedia": ""},
]
