"""
Baked-in Top Twitch Streamers reference data: the top channels from
TwitchTracker's overall ranking, with each channel's 30-day average viewers,
all-time peak viewers, hours watched, Twitch channel link, social handles
(X/Twitter, YouTube) and Wikipedia page (where one exists).

TwitchTracker's "Overall Rank" blends average concurrent viewers, followers,
views and stream time over the trailing 30 days. The page is JavaScript-rendered
and the figures move daily, so this is a curated snapshot stored here and
refreshed periodically. Social accounts are official channels; blank where not
verifiable. Wikipedia links are direct article URLs.

Source: https://twitchtracker.com/channels/ranking
"""

TWITCH_EDITION = "30-day overall rank"
TWITCH_SOURCE_URL = "https://twitchtracker.com/channels/ranking"

TOP_TWITCH_STREAMERS = [
    {"position": 1, "channel": "Caedrel", "avg_viewers": 107082, "peak_viewers": 422292, "hours_watched": 7440422, "twitch": "https://www.twitch.tv/caedrel", "twitter": "https://x.com/Caedrel", "youtube": "https://www.youtube.com/caedrel", "wikipedia": "https://en.wikipedia.org/wiki/Caedrel"},
    {"position": 2, "channel": "LVNDMARK", "avg_viewers": 33201, "peak_viewers": 165048, "hours_watched": 9573493, "twitch": "https://www.twitch.tv/lvndmark", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 3, "channel": "Pestily", "avg_viewers": 25597, "peak_viewers": 244422, "hours_watched": 8581828, "twitch": "https://www.twitch.tv/pestily", "twitter": "", "youtube": "https://www.youtube.com/c/pestily", "wikipedia": ""},
    {"position": 4, "channel": "加藤純一うん〇ちゃん", "avg_viewers": 34182, "peak_viewers": 292323, "hours_watched": 7490404, "twitch": "https://www.twitch.tv/kato_junichi0817", "twitter": "https://x.com/unkochan1234567", "youtube": "https://www.youtube.com/channel/UCZetZElUvdElPrcstRjl9DA", "wikipedia": "https://en.wikipedia.org/wiki/Junichi_Kato_(streamer)"},
    {"position": 5, "channel": "eliasn97", "avg_viewers": 32734, "peak_viewers": 207475, "hours_watched": 7351503, "twitch": "https://www.twitch.tv/eliasn97", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 6, "channel": "zackrawrr", "avg_viewers": 38662, "peak_viewers": 309124, "hours_watched": 6779423, "twitch": "https://www.twitch.tv/zackrawrr", "twitter": "https://x.com/asmongold", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Asmongold"},
    {"position": 7, "channel": "BastiGHG", "avg_viewers": 23059, "peak_viewers": 81048, "hours_watched": 6993867, "twitch": "https://www.twitch.tv/bastighg", "twitter": "", "youtube": "https://www.youtube.com/channel/UCgZpwegd4AdDlZNrIamIgRw", "wikipedia": ""},
    {"position": 8, "channel": "Papaplatte", "avg_viewers": 30724, "peak_viewers": 120011, "hours_watched": 5996717, "twitch": "https://www.twitch.tv/papaplatte", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Papaplatte"},
    {"position": 9, "channel": "caseoh_", "avg_viewers": 52284, "peak_viewers": 110574, "hours_watched": 4970454, "twitch": "https://www.twitch.tv/caseoh_", "twitter": "", "youtube": "https://www.youtube.com/channel/UC63anZxfVGHUEmfBAf5w7pw", "wikipedia": ""},
    {"position": 10, "channel": "shroud", "avg_viewers": 22160, "peak_viewers": 516289, "hours_watched": 6309992, "twitch": "https://www.twitch.tv/shroud", "twitter": "https://x.com/shroud", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Shroud_(gamer)"},
    {"position": 11, "channel": "TheBurntPeanut", "avg_viewers": 25255, "peak_viewers": 93043, "hours_watched": 5929120, "twitch": "https://www.twitch.tv/theburntpeanut", "twitter": "", "youtube": "https://www.youtube.com/@TheBurntPeanut", "wikipedia": ""},
    {"position": 12, "channel": "Jynxzi", "avg_viewers": 33053, "peak_viewers": 208375, "hours_watched": 5563945, "twitch": "https://www.twitch.tv/jynxzi", "twitter": "", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Jynxzi"},
    {"position": 13, "channel": "HasanAbi", "avg_viewers": 28766, "peak_viewers": 312431, "hours_watched": 5375477, "twitch": "https://www.twitch.tv/hasanabi", "twitter": "", "youtube": "https://www.youtube.com/channel/UCtoaZpBnrd0lhycxYJ4MNOQ", "wikipedia": "https://en.wikipedia.org/wiki/Hasan_Piker"},
    {"position": 14, "channel": "aminematue", "avg_viewers": 49943, "peak_viewers": 1155060, "hours_watched": 4301715, "twitch": "https://www.twitch.tv/aminematue", "twitter": "", "youtube": "https://www.youtube.com/channel/UCNigJTVnMU8F3n08pYz0UYw", "wikipedia": ""},
    {"position": 15, "channel": "k4sen", "avg_viewers": 23644, "peak_viewers": 148289, "hours_watched": 5096914, "twitch": "https://www.twitch.tv/k4sen", "twitter": "https://x.com/thek4sen", "youtube": "", "wikipedia": ""},
    {"position": 16, "channel": "Riot Games", "avg_viewers": 74195, "peak_viewers": 854781, "hours_watched": 2805805, "twitch": "https://www.twitch.tv/riotgames", "twitter": "https://x.com/riotgames", "youtube": "https://www.youtube.com/riotgames", "wikipedia": "https://en.wikipedia.org/wiki/Riot_Games"},
    {"position": 17, "channel": "ibai", "avg_viewers": 76251, "peak_viewers": 9189762, "hours_watched": 2493398, "twitch": "https://www.twitch.tv/ibai", "twitter": "https://x.com/IbaiLlanos", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/Ibai_Llanos"},
    {"position": 18, "channel": "summit1g", "avg_viewers": 13518, "peak_viewers": 310998, "hours_watched": 5011503, "twitch": "https://www.twitch.tv/summit1g", "twitter": "https://x.com/summit1g", "youtube": "https://www.youtube.com/summit1g", "wikipedia": "https://en.wikipedia.org/wiki/Summit1g"},
    {"position": 19, "channel": "fps_shaka", "avg_viewers": 17009, "peak_viewers": 125341, "hours_watched": 4584970, "twitch": "https://www.twitch.tv/fps_shaka", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 20, "channel": "Rubius", "avg_viewers": 34709, "peak_viewers": 383747, "hours_watched": 3735235, "twitch": "https://www.twitch.tv/rubius", "twitter": "https://x.com/Rubiu5", "youtube": "https://www.youtube.com/user/elrubiusOMG", "wikipedia": "https://en.wikipedia.org/wiki/El_Rubius"},
    {"position": 21, "channel": "xQc", "avg_viewers": 19301, "peak_viewers": 278176, "hours_watched": 4201259, "twitch": "https://www.twitch.tv/xqc", "twitter": "https://x.com/xQc", "youtube": "https://www.youtube.com/channel/UCmDTrq0LNgPodDOFZiSbsww", "wikipedia": "https://en.wikipedia.org/wiki/XQc"},
    {"position": 22, "channel": "sasavot", "avg_viewers": 24685, "peak_viewers": 99873, "hours_watched": 3634011, "twitch": "https://www.twitch.tv/sasavot", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 23, "channel": "auronplay", "avg_viewers": 41635, "peak_viewers": 602038, "hours_watched": 2872843, "twitch": "https://www.twitch.tv/auronplay", "twitter": "https://x.com/auronplay", "youtube": "", "wikipedia": "https://en.wikipedia.org/wiki/AuronPlay"},
    {"position": 24, "channel": "ohnePixel", "avg_viewers": 32463, "peak_viewers": 298362, "hours_watched": 2782580, "twitch": "https://www.twitch.tv/ohnepixel", "twitter": "https://x.com/ohnePixel", "youtube": "https://www.youtube.com/@ohnepixel", "wikipedia": "https://en.wikipedia.org/wiki/OhnePixel"},
    {"position": 25, "channel": "Tumblurr", "avg_viewers": 37904, "peak_viewers": 346842, "hours_watched": 2444148, "twitch": "https://www.twitch.tv/tumblurr", "twitter": "https://x.com/sdrogoblur", "youtube": "", "wikipedia": ""},
    # ---- Added 2026-07: ranks 26-50 (TwitchTracker overall ranking snapshot) ----
    {"position": 26, "channel": "Recrent", "avg_viewers": 11576, "peak_viewers": 119109, "hours_watched": 3605809, "twitch": "https://www.twitch.tv/recrent", "twitter": "https://x.com/Recrent_", "instagram": "https://www.instagram.com/recrent.twitch", "youtube": "https://www.youtube.com/channel/UCw_09chvmXy_zZJz2Tj2-mg", "wikipedia": ""},
    {"position": 27, "channel": "ramzes", "avg_viewers": 19472, "peak_viewers": 88423, "hours_watched": 3108768, "twitch": "https://www.twitch.tv/ramzes", "twitter": "https://x.com/ramzes", "instagram": "https://www.instagram.com/ramzes", "youtube": "https://www.youtube.com/@Ramzes666YouTube", "wikipedia": "https://en.wikipedia.org/wiki/RAMZES666"},
    {"position": 28, "channel": "HandOfBlood", "avg_viewers": 17614, "peak_viewers": 82504, "hours_watched": 3173221, "twitch": "https://www.twitch.tv/handofblood", "twitter": "https://x.com/HandOfBlood", "facebook": "https://www.facebook.com/HandOfBlood", "youtube": "https://www.youtube.com/@HandOfBlood", "tiktok": "https://www.tiktok.com/@handofblood", "wikipedia": ""},
    {"position": 29, "channel": "PrimeVideo", "avg_viewers": 56975, "peak_viewers": 148841, "hours_watched": 1274344, "twitch": "https://www.twitch.tv/primevideo", "twitter": "https://x.com/PrimeVideo", "instagram": "https://www.instagram.com/primevideo", "youtube": "https://www.youtube.com/@PrimeVideo", "wikipedia": "https://en.wikipedia.org/wiki/Prime_Video"},
    {"position": 30, "channel": "nooreax", "avg_viewers": 4952, "peak_viewers": 17526, "hours_watched": 3565417, "twitch": "https://www.twitch.tv/nooreax", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 31, "channel": "plaqueboymax", "avg_viewers": 24875, "peak_viewers": 196138, "hours_watched": 2560455, "twitch": "https://www.twitch.tv/plaqueboymax", "twitter": "https://x.com/plaqueboymax", "instagram": "https://www.instagram.com/plaqueboymax", "youtube": "https://www.youtube.com/@plaqueboymax", "wikipedia": "https://en.wikipedia.org/wiki/PlaqueBoyMax"},
    {"position": 32, "channel": "easportsfc", "avg_viewers": 56422, "peak_viewers": 290841, "hours_watched": 1116220, "twitch": "https://www.twitch.tv/easportsfc", "twitter": "https://x.com/EASPORTSFC", "instagram": "https://www.instagram.com/easportsfc", "youtube": "https://www.youtube.com/@easportsfc", "wikipedia": "https://en.wikipedia.org/wiki/EA_Sports_FC"},
    {"position": 33, "channel": "Lacy", "avg_viewers": 14319, "peak_viewers": 77690, "hours_watched": 2976124, "twitch": "https://www.twitch.tv/lacy", "twitter": "https://x.com/LacyHimself", "tiktok": "https://www.tiktok.com/@lacy", "youtube": "", "wikipedia": ""},
    {"position": 34, "channel": "evelone2004", "avg_viewers": 41497, "peak_viewers": 218191, "hours_watched": 1745644, "twitch": "https://www.twitch.tv/evelone2004", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 35, "channel": "zarbex", "avg_viewers": 14912, "peak_viewers": 58722, "hours_watched": 2848265, "twitch": "https://www.twitch.tv/zarbex", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 36, "channel": "N3on", "avg_viewers": 26230, "peak_viewers": 48191, "hours_watched": 2279411, "twitch": "https://www.twitch.tv/n3on", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 37, "channel": "Nix", "avg_viewers": 33773, "peak_viewers": 399855, "hours_watched": 1896932, "twitch": "https://www.twitch.tv/nix", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 38, "channel": "Kamet0", "avg_viewers": 17165, "peak_viewers": 419458, "hours_watched": 2579629, "twitch": "https://www.twitch.tv/kamet0", "twitter": "https://x.com/Kammeto", "instagram": "https://www.instagram.com/kametolol", "facebook": "https://www.facebook.com/Kamet0", "youtube": "https://www.youtube.com/channel/UC-bQgl7oy_rEk05rNWYXafA", "wikipedia": ""},
    {"position": 39, "channel": "dota2_paragon_ru", "avg_viewers": 15704, "peak_viewers": 263498, "hours_watched": 2612643, "twitch": "https://www.twitch.tv/dota2_paragon_ru", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 40, "channel": "jasontheween", "avg_viewers": 16009, "peak_viewers": 118191, "hours_watched": 2507285, "twitch": "https://www.twitch.tv/jasontheween", "twitter": "https://x.com/jasontheween", "instagram": "https://www.instagram.com/jasontheween", "youtube": "https://www.youtube.com/@jasontheween", "tiktok": "https://www.tiktok.com/@jasontheween", "wikipedia": "https://en.wikipedia.org/wiki/Jason_Nguyen"},
    {"position": 41, "channel": "NoWay4u_Sir", "avg_viewers": 12524, "peak_viewers": 49218, "hours_watched": 2638448, "twitch": "https://www.twitch.tv/noway4u_sir", "twitter": "https://x.com/noway4u_sir", "instagram": "https://www.instagram.com/sir_noway4u", "youtube": "https://www.youtube.com/@Noway4u", "tiktok": "https://www.tiktok.com/@NoWay4U", "wikipedia": ""},
    {"position": 42, "channel": "yourragegaming", "avg_viewers": 13189, "peak_viewers": 122820, "hours_watched": 2596275, "twitch": "https://www.twitch.tv/yourragegaming", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 43, "channel": "mokrivskyi", "avg_viewers": 29385, "peak_viewers": 116084, "hours_watched": 1855634, "twitch": "https://www.twitch.tv/mokrivskyi", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 44, "channel": "Marlon", "avg_viewers": 4602, "peak_viewers": 97174, "hours_watched": 2930865, "twitch": "https://www.twitch.tv/marlon", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 45, "channel": "lolesportstw", "avg_viewers": 40626, "peak_viewers": 165491, "hours_watched": 1304767, "twitch": "https://www.twitch.tv/lolesportstw", "twitter": "https://x.com/lolesportstw", "instagram": "https://www.instagram.com/lolesportstw", "youtube": "", "wikipedia": ""},
    {"position": 46, "channel": "anarabdullaev", "avg_viewers": 24387, "peak_viewers": 68065, "hours_watched": 1946856, "twitch": "https://www.twitch.tv/anarabdullaev", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 47, "channel": "Trymacs", "avg_viewers": 12385, "peak_viewers": 365000, "hours_watched": 2464465, "twitch": "https://www.twitch.tv/trymacs", "twitter": "https://x.com/Trymacs", "instagram": "https://www.instagram.com/trymacs", "youtube": "https://www.youtube.com/@Trymacs", "wikipedia": ""},
    {"position": 48, "channel": "StRoGo", "avg_viewers": 16782, "peak_viewers": 80095, "hours_watched": 2247667, "twitch": "https://www.twitch.tv/strogo", "twitter": "", "youtube": "", "wikipedia": ""},
    {"position": 49, "channel": "MontanaBlack88", "avg_viewers": 16214, "peak_viewers": 257202, "hours_watched": 2193466, "twitch": "https://www.twitch.tv/montanablack88", "twitter": "", "instagram": "https://www.instagram.com/montanablack88", "youtube": "", "wikipedia": ""},
    {"position": 50, "channel": "IlloJuan", "avg_viewers": 28891, "peak_viewers": 205005, "hours_watched": 1616468, "twitch": "https://www.twitch.tv/illojuan", "twitter": "https://x.com/IlloJuan", "youtube": "https://www.youtube.com/@IlloJuan_", "wikipedia": "https://en.wikipedia.org/wiki/IlloJuan"},
]
