"""
Baked-in Ulta brand directory, sourced from ulta.com/brand/all.

The list is Ulta's full A-Z brand directory (1046 brands). Each brand links to its
Ulta brand page. Social handles are auto-generated from the brand name and UNVERIFIED,
except a small set of prominent brands with verified Instagram/X handles baked in below.

Sources: https://www.ulta.com/brand/all
"""

ULTA_EDITION = "ulta.com brands A-Z (socials auto-generated; select brands verified)"
ULTA_SOURCE_URL = "https://www.ulta.com/brand/all"

ULTA_BRANDS = [
{"rank": 1, "brand": "107", "ulta_url": "https://www.ulta.com/brand/107"},
{"rank": 2, "brand": "18.21 Man Made", "ulta_url": "https://www.ulta.com/brand/1821-man-made"},
{"rank": 3, "brand": "3H Nails", "ulta_url": "https://www.ulta.com/brand/3h-nails"},
{"rank": 4, "brand": "7 E Wellness", "ulta_url": "https://www.ulta.com/brand/7-e-wellness"},
{"rank": 5, "brand": "760 Skin", "ulta_url": "https://www.ulta.com/brand/760-skin"},
{"rank": 6, "brand": "8Grow", "ulta_url": "https://www.ulta.com/brand/8grow"},
{"rank": 7, "brand": "A313", "ulta_url": "https://www.ulta.com/brand/a313"},
{"rank": 8, "brand": "Abature", "ulta_url": "https://www.ulta.com/brand/abature"},
{"rank": 9, "brand": "about-face", "ulta_url": "https://www.ulta.com/brand/about-face"},
{"rank": 10, "brand": "Acca Kappa", "ulta_url": "https://www.ulta.com/brand/acca-kappa"},
{"rank": 11, "brand": "Active Beauty", "ulta_url": "https://www.ulta.com/brand/active-beauty"},
{"rank": 12, "brand": "Admire My Skin", "ulta_url": "https://www.ulta.com/brand/admire-my-skin"},
{"rank": 13, "brand": "af94", "ulta_url": "https://www.ulta.com/brand/af94"},
{"rank": 14, "brand": "Afnan", "ulta_url": "https://www.ulta.com/brand/afnan"},
{"rank": 15, "brand": "AG Care", "ulta_url": "https://www.ulta.com/brand/ag-care"},
{"rank": 16, "brand": "AG1", "ulta_url": "https://www.ulta.com/brand/ag1"},
{"rank": 17, "brand": "Ahava", "ulta_url": "https://www.ulta.com/brand/ahava"},
{"rank": 18, "brand": "Aippo", "ulta_url": "https://www.ulta.com/brand/aippo"},
{"rank": 19, "brand": "Alexandre.J", "ulta_url": "https://www.ulta.com/brand/alexandrej"},
{"rank": 20, "brand": "Algenist", "ulta_url": "https://www.ulta.com/brand/algenist"},
{"rank": 21, "brand": "Alleyoop", "ulta_url": "https://www.ulta.com/brand/alleyoop"},
{"rank": 22, "brand": "Almost Famous", "ulta_url": "https://www.ulta.com/brand/almost-famous"},
{"rank": 23, "brand": "Alpha Skincare", "ulta_url": "https://www.ulta.com/brand/alpha-skincare"},
{"rank": 24, "brand": "Alterna", "ulta_url": "https://www.ulta.com/brand/alterna"},
{"rank": 25, "brand": "AMAZING COSMETICS", "ulta_url": "https://www.ulta.com/brand/amazing-cosmetics"},
{"rank": 26, "brand": "Amazing Grass", "ulta_url": "https://www.ulta.com/brand/amazing-grass"},
{"rank": 27, "brand": "American Crew", "ulta_url": "https://www.ulta.com/brand/american-crew"},
{"rank": 28, "brand": "amika", "ulta_url": "https://www.ulta.com/brand/amika"},
{"rank": 29, "brand": "AmLactin", "ulta_url": "https://www.ulta.com/brand/amlactin"},
{"rank": 30, "brand": "AMRITARA", "ulta_url": "https://www.ulta.com/brand/amritara"},
{"rank": 31, "brand": "Anastasia Beverly Hills", "ulta_url": "https://www.ulta.com/brand/anastasia-beverly-hills"},
{"rank": 32, "brand": "Andis", "ulta_url": "https://www.ulta.com/brand/andis"},
{"rank": 33, "brand": "Anima Mundi", "ulta_url": "https://www.ulta.com/brand/anima-mundi"},
{"rank": 34, "brand": "Anthony", "ulta_url": "https://www.ulta.com/brand/anthony"},
{"rank": 35, "brand": "ANUA", "ulta_url": "https://www.ulta.com/brand/anua"},
{"rank": 36, "brand": "Aperire", "ulta_url": "https://www.ulta.com/brand/aperire"},
{"rank": 37, "brand": "Apieu", "ulta_url": "https://www.ulta.com/brand/apieu"},
{"rank": 38, "brand": "APLB", "ulta_url": "https://www.ulta.com/brand/aplb"},
{"rank": 39, "brand": "Apostle", "ulta_url": "https://www.ulta.com/brand/apostle"},
{"rank": 40, "brand": "APOTHEKE", "ulta_url": "https://www.ulta.com/brand/apotheke"},
{"rank": 41, "brand": "Apothékary", "ulta_url": "https://www.ulta.com/brand/apothekary"},
{"rank": 42, "brand": "Aquaphor", "ulta_url": "https://www.ulta.com/brand/aquaphor"},
{"rank": 43, "brand": "AquaSonic", "ulta_url": "https://www.ulta.com/brand/aquasonic"},
{"rank": 44, "brand": "ARABIAN CREST DUBAI", "ulta_url": "https://www.ulta.com/brand/arabian-crest-dubai"},
{"rank": 45, "brand": "Aramis", "ulta_url": "https://www.ulta.com/brand/aramis"},
{"rank": 46, "brand": "Aramore", "ulta_url": "https://www.ulta.com/brand/aramore"},
{"rank": 47, "brand": "Arctic Fox", "ulta_url": "https://www.ulta.com/brand/arctic-fox"},
{"rank": 48, "brand": "Ardell", "ulta_url": "https://www.ulta.com/brand/ardell"},
{"rank": 49, "brand": "Ariana Grande", "ulta_url": "https://www.ulta.com/brand/ariana-grande"},
{"rank": 50, "brand": "ARMANI", "ulta_url": "https://www.ulta.com/brand/armani"},
{"rank": 51, "brand": "ARMRA Colostrum", "ulta_url": "https://www.ulta.com/brand/armra-colostrum"},
{"rank": 52, "brand": "arrae", "ulta_url": "https://www.ulta.com/brand/arrae"},
{"rank": 53, "brand": "Artis Brushes", "ulta_url": "https://www.ulta.com/brand/artis-brushes"},
{"rank": 54, "brand": "ASCENTION Parfums", "ulta_url": "https://www.ulta.com/brand/ascention-parfums"},
{"rank": 55, "brand": "ASNA", "ulta_url": "https://www.ulta.com/brand/asna"},
{"rank": 56, "brand": "Athletic Cosmetic Company", "ulta_url": "https://www.ulta.com/brand/athletic-cosmetic-company"},
{"rank": 57, "brand": "ATWATER", "ulta_url": "https://www.ulta.com/brand/atwater"},
{"rank": 58, "brand": "Avatara Skin", "ulta_url": "https://www.ulta.com/brand/avatara-skin"},
{"rank": 59, "brand": "Aveeno", "ulta_url": "https://www.ulta.com/brand/aveeno"},
{"rank": 60, "brand": "Avène", "ulta_url": "https://www.ulta.com/brand/avene"},
{"rank": 61, "brand": "awe", "ulta_url": "https://www.ulta.com/brand/awe"},
{"rank": 62, "brand": "AXIS-Y", "ulta_url": "https://www.ulta.com/brand/axis-y"},
{"rank": 63, "brand": "Azzaro", "ulta_url": "https://www.ulta.com/brand/azzaro"},
{"rank": 64, "brand": "b.tan", "ulta_url": "https://www.ulta.com/brand/btan"},
{"rank": 65, "brand": "Babe Original", "ulta_url": "https://www.ulta.com/brand/babe-original"},
{"rank": 66, "brand": "Baby Foot", "ulta_url": "https://www.ulta.com/brand/baby-foot"},
{"rank": 67, "brand": "BaBylissPRO", "ulta_url": "https://www.ulta.com/brand/babylisspro"},
{"rank": 68, "brand": "Bali Body", "ulta_url": "https://www.ulta.com/brand/bali-body"},
{"rank": 69, "brand": "Balmain Paris", "ulta_url": "https://www.ulta.com/brand/balmain-paris"},
{"rank": 70, "brand": "Baloom", "ulta_url": "https://www.ulta.com/brand/baloom"},
{"rank": 71, "brand": "Banila Co", "ulta_url": "https://www.ulta.com/brand/banila-co"},
{"rank": 72, "brand": "Barbasol Shaving", "ulta_url": "https://www.ulta.com/brand/barbasol-shaving"},
{"rank": 73, "brand": "Barberino's", "ulta_url": "https://www.ulta.com/brand/barberinos"},
{"rank": 74, "brand": "BarberMate", "ulta_url": "https://www.ulta.com/brand/barbermate"},
{"rank": 75, "brand": "bareMinerals", "ulta_url": "https://www.ulta.com/brand/bareminerals"},
{"rank": 76, "brand": "Barrière", "ulta_url": "https://www.ulta.com/brand/barriere"},
{"rank": 77, "brand": "Bath & Body Works", "ulta_url": "https://www.ulta.com/brand/bath-body-works"},
{"rank": 78, "brand": "Batiste", "ulta_url": "https://www.ulta.com/brand/batiste"},
{"rank": 79, "brand": "Baxter of California", "ulta_url": "https://www.ulta.com/brand/baxter-of-california"},
{"rank": 80, "brand": "bdy.", "ulta_url": "https://www.ulta.com/brand/bdy"},
{"rank": 81, "brand": "Be Your Own Desire", "ulta_url": "https://www.ulta.com/brand/be-your-own-desire"},
{"rank": 82, "brand": "Beachwaver Co.", "ulta_url": "https://www.ulta.com/brand/beachwaver-co"},
{"rank": 83, "brand": "BEAUND", "ulta_url": "https://www.ulta.com/brand/beaund"},
{"rank": 84, "brand": "Beautifect", "ulta_url": "https://www.ulta.com/brand/beautifect"},
{"rank": 85, "brand": "Beauty by Bower", "ulta_url": "https://www.ulta.com/brand/beauty-by-bower"},
{"rank": 86, "brand": "Beauty Core", "ulta_url": "https://www.ulta.com/brand/beauty-core"},
{"rank": 87, "brand": "Beauty Finds by ULTA Beauty", "ulta_url": "https://www.ulta.com/brand/beauty-finds-by-ulta-beauty"},
{"rank": 88, "brand": "BeautyBio", "ulta_url": "https://www.ulta.com/brand/beautybio"},
{"rank": 89, "brand": "beautyblender", "ulta_url": "https://www.ulta.com/brand/beautyblender"},
{"rank": 90, "brand": "BeautyStat Cosmetics", "ulta_url": "https://www.ulta.com/brand/beautystat-cosmetics"},
{"rank": 91, "brand": "Bed Head", "ulta_url": "https://www.ulta.com/brand/bed-head"},
{"rank": 92, "brand": "Beekman 1802", "ulta_url": "https://www.ulta.com/brand/beekman-1802"},
{"rank": 93, "brand": "Before Oral Care", "ulta_url": "https://www.ulta.com/brand/before-oral-care"},
{"rank": 94, "brand": "being", "ulta_url": "https://www.ulta.com/brand/being"},
{"rank": 95, "brand": "Being Frenshe", "ulta_url": "https://www.ulta.com/brand/being-frenshe"},
{"rank": 96, "brand": "Bejou", "ulta_url": "https://www.ulta.com/brand/bejou"},
{"rank": 97, "brand": "belif", "ulta_url": "https://www.ulta.com/brand/belif"},
{"rank": 98, "brand": "Benefit Cosmetics", "ulta_url": "https://www.ulta.com/brand/benefit-cosmetics", "instagram": "https://www.instagram.com/benefitcosmetics", "twitter": "https://x.com/BenefitBeauty"},
{"rank": 99, "brand": "BETTER WORLD FRAGRANCE HOUSE", "ulta_url": "https://www.ulta.com/brand/better-world-fragrance-house"},
{"rank": 100, "brand": "BEVEL", "ulta_url": "https://www.ulta.com/brand/bevel"},
{"rank": 101, "brand": "Bewants", "ulta_url": "https://www.ulta.com/brand/bewants"},
{"rank": 102, "brand": "Beyoncé Parfums", "ulta_url": "https://www.ulta.com/brand/beyonce-parfums"},
{"rank": 103, "brand": "Bifi Blanche", "ulta_url": "https://www.ulta.com/brand/bifi-blanche"},
{"rank": 104, "brand": "billie", "ulta_url": "https://www.ulta.com/brand/billie"},
{"rank": 105, "brand": "Billie Eilish", "ulta_url": "https://www.ulta.com/brand/billie-eilish"},
{"rank": 106, "brand": "Bio Ionic", "ulta_url": "https://www.ulta.com/brand/bio-ionic"},
{"rank": 107, "brand": "Bio-Oil", "ulta_url": "https://www.ulta.com/brand/bio-oil"},
{"rank": 108, "brand": "Bioderma", "ulta_url": "https://www.ulta.com/brand/bioderma"},
{"rank": 109, "brand": "Biolage", "ulta_url": "https://www.ulta.com/brand/biolage"},
{"rank": 110, "brand": "Bioré", "ulta_url": "https://www.ulta.com/brand/biore"},
{"rank": 111, "brand": "Biosilk", "ulta_url": "https://www.ulta.com/brand/biosilk"},
{"rank": 112, "brand": "Bird&Be", "ulta_url": "https://www.ulta.com/brand/bird-be"},
{"rank": 113, "brand": "BK Beauty", "ulta_url": "https://www.ulta.com/brand/bk-beauty"},
{"rank": 114, "brand": "Black Girl Sunscreen", "ulta_url": "https://www.ulta.com/brand/black-girl-sunscreen"},
{"rank": 115, "brand": "BLACKWOOD FOR MEN", "ulta_url": "https://www.ulta.com/brand/blackwood-men"},
{"rank": 116, "brand": "Blinc", "ulta_url": "https://www.ulta.com/brand/blinc"},
{"rank": 117, "brand": "Blind Barber", "ulta_url": "https://www.ulta.com/brand/blind-barber"},
{"rank": 118, "brand": "Blissy", "ulta_url": "https://www.ulta.com/brand/blissy"},
{"rank": 119, "brand": "BLK/OPL", "ulta_url": "https://www.ulta.com/brand/blkopl"},
{"rank": 120, "brand": "BLONDME", "ulta_url": "https://www.ulta.com/brand/blondme"},
{"rank": 121, "brand": "Bloom", "ulta_url": "https://www.ulta.com/brand/bloom"},
{"rank": 122, "brand": "Bloomeffects", "ulta_url": "https://www.ulta.com/brand/bloomeffects"},
{"rank": 123, "brand": "BLOSSOM", "ulta_url": "https://www.ulta.com/brand/blossom"},
{"rank": 124, "brand": "Blossom Essentials", "ulta_url": "https://www.ulta.com/brand/blossom-essentials"},
{"rank": 125, "brand": "Blu Atlas", "ulta_url": "https://www.ulta.com/brand/blu-atlas"},
{"rank": 126, "brand": "Blue Lagoon Skin Science", "ulta_url": "https://www.ulta.com/brand/blue-lagoon-skin-science"},
{"rank": 127, "brand": "BLUE LIZARD AUSTRALIAN SUNSCREEN", "ulta_url": "https://www.ulta.com/brand/blue-lizard-australian-sunscreen"},
{"rank": 128, "brand": "BLUME", "ulta_url": "https://www.ulta.com/brand/blume"},
{"rank": 129, "brand": "Blushly", "ulta_url": "https://www.ulta.com/brand/blushly"},
{"rank": 130, "brand": "BOBBI BROWN", "ulta_url": "https://www.ulta.com/brand/bobbi-brown"},
{"rank": 131, "brand": "Bondi Boost", "ulta_url": "https://www.ulta.com/brand/bondi-boost"},
{"rank": 132, "brand": "Bondi Sands", "ulta_url": "https://www.ulta.com/brand/bondi-sands"},
{"rank": 133, "brand": "Bonika Shears", "ulta_url": "https://www.ulta.com/brand/bonika-shears"},
{"rank": 134, "brand": "Borghese", "ulta_url": "https://www.ulta.com/brand/borghese"},
{"rank": 135, "brand": "BREAD BEAUTY SUPPLY", "ulta_url": "https://www.ulta.com/brand/bread-beauty-supply"},
{"rank": 136, "brand": "Bridgerton", "ulta_url": "https://www.ulta.com/brand/bridgerton"},
{"rank": 137, "brand": "Briogeo", "ulta_url": "https://www.ulta.com/brand/briogeo"},
{"rank": 138, "brand": "BRMUD", "ulta_url": "https://www.ulta.com/brand/brmud"},
{"rank": 139, "brand": "Broken Top Candle Co.", "ulta_url": "https://www.ulta.com/brand/broken-top-candle-co"},
{"rank": 140, "brand": "Brush On Block", "ulta_url": "https://www.ulta.com/brand/brush-on-block"},
{"rank": 141, "brand": "Bubble", "ulta_url": "https://www.ulta.com/brand/bubble"},
{"rank": 142, "brand": "Bubble T", "ulta_url": "https://www.ulta.com/brand/bubble-t"},
{"rank": 143, "brand": "Bumble and bumble", "ulta_url": "https://www.ulta.com/brand/bumble-bumble"},
{"rank": 144, "brand": "Burberry", "ulta_url": "https://www.ulta.com/brand/burberry"},
{"rank": 145, "brand": "Bushbalm", "ulta_url": "https://www.ulta.com/brand/bushbalm"},
{"rank": 146, "brand": "Buttah Skin", "ulta_url": "https://www.ulta.com/brand/buttah-skin"},
{"rank": 147, "brand": "Butter Be Kind", "ulta_url": "https://www.ulta.com/brand/butter-be-kind"},
{"rank": 148, "brand": "Buxom", "ulta_url": "https://www.ulta.com/brand/buxom"},
{"rank": 149, "brand": "By the Beach", "ulta_url": "https://www.ulta.com/brand/by-beach"},
{"rank": 150, "brand": "BYOMA", "ulta_url": "https://www.ulta.com/brand/byoma"},
{"rank": 151, "brand": "BYROE", "ulta_url": "https://www.ulta.com/brand/byroe"},
{"rank": 152, "brand": "Caboodles", "ulta_url": "https://www.ulta.com/brand/caboodles"},
{"rank": 153, "brand": "Caire Beauty", "ulta_url": "https://www.ulta.com/brand/caire-beauty"},
{"rank": 154, "brand": "CAKES Body", "ulta_url": "https://www.ulta.com/brand/cakes-body"},
{"rank": 155, "brand": "Caldera + Lab", "ulta_url": "https://www.ulta.com/brand/caldera-lab"},
{"rank": 156, "brand": "Caliber Beauty", "ulta_url": "https://www.ulta.com/brand/caliber-beauty"},
{"rank": 157, "brand": "California Naturals", "ulta_url": "https://www.ulta.com/brand/california-naturals"},
{"rank": 158, "brand": "Calista", "ulta_url": "https://www.ulta.com/brand/calista"},
{"rank": 159, "brand": "Calvin Klein", "ulta_url": "https://www.ulta.com/brand/calvin-klein"},
{"rank": 160, "brand": "Camille Rose", "ulta_url": "https://www.ulta.com/brand/camille-rose"},
{"rank": 161, "brand": "Candorlov", "ulta_url": "https://www.ulta.com/brand/candorlov"},
{"rank": 162, "brand": "Capelli New York", "ulta_url": "https://www.ulta.com/brand/capelli-new-york"},
{"rank": 163, "brand": "Captain Fawcett", "ulta_url": "https://www.ulta.com/brand/captain-fawcett"},
{"rank": 164, "brand": "Carbon Theory.", "ulta_url": "https://www.ulta.com/brand/carbon-theory"},
{"rank": 165, "brand": "Carol's Daughter", "ulta_url": "https://www.ulta.com/brand/carols-daughter"},
{"rank": 166, "brand": "Carolina Herrera", "ulta_url": "https://www.ulta.com/brand/carolina-herrera"},
{"rank": 167, "brand": "Carroten", "ulta_url": "https://www.ulta.com/brand/carroten"},
{"rank": 168, "brand": "Caswell-Massey", "ulta_url": "https://www.ulta.com/brand/caswell-massey"},
{"rank": 169, "brand": "Cayla Gray", "ulta_url": "https://www.ulta.com/brand/cayla-gray"},
{"rank": 170, "brand": "celimax", "ulta_url": "https://www.ulta.com/brand/celimax"},
{"rank": 171, "brand": "Cell Fusion C", "ulta_url": "https://www.ulta.com/brand/cell-fusion-c"},
{"rank": 172, "brand": "Centellian24", "ulta_url": "https://www.ulta.com/brand/centellian24"},
{"rank": 173, "brand": "CeraVe", "ulta_url": "https://www.ulta.com/brand/cerave"},
{"rank": 174, "brand": "Cetaphil", "ulta_url": "https://www.ulta.com/brand/cetaphil"},
{"rank": 175, "brand": "Cha&Mom", "ulta_url": "https://www.ulta.com/brand/cha-mom"},
{"rank": 176, "brand": "CHANEL", "ulta_url": "https://www.ulta.com/brand/chanel", "instagram": "https://www.instagram.com/chanel.beauty", "twitter": "https://x.com/CHANEL"},
{"rank": 177, "brand": "Char Cosmetics", "ulta_url": "https://www.ulta.com/brand/char-cosmetics"},
{"rank": 178, "brand": "Charlotte Tilbury", "ulta_url": "https://www.ulta.com/brand/charlotte-tilbury", "instagram": "https://www.instagram.com/charlottetilbury", "twitter": "https://x.com/CTilburyMakeup"},
{"rank": 179, "brand": "Chasin' Rabbits", "ulta_url": "https://www.ulta.com/brand/chasin-rabbits"},
{"rank": 180, "brand": "CHI", "ulta_url": "https://www.ulta.com/brand/chi"},
{"rank": 181, "brand": "China Glaze", "ulta_url": "https://www.ulta.com/brand/china-glaze"},
{"rank": 182, "brand": "Chloé", "ulta_url": "https://www.ulta.com/brand/chloe"},
{"rank": 183, "brand": "Christophe Robin", "ulta_url": "https://www.ulta.com/brand/christophe-robin"},
{"rank": 184, "brand": "ChungMijung", "ulta_url": "https://www.ulta.com/brand/chungmijung"},
{"rank": 185, "brand": "Cinema Secrets", "ulta_url": "https://www.ulta.com/brand/cinema-secrets"},
{"rank": 186, "brand": "Clairol", "ulta_url": "https://www.ulta.com/brand/clairol"},
{"rank": 187, "brand": "Clarins", "ulta_url": "https://www.ulta.com/brand/clarins"},
{"rank": 188, "brand": "CLE Cosmetics", "ulta_url": "https://www.ulta.com/brand/cle-cosmetics"},
{"rank": 189, "brand": "Clean", "ulta_url": "https://www.ulta.com/brand/clean"},
{"rank": 190, "brand": "Clean Skin Club", "ulta_url": "https://www.ulta.com/brand/clean-skin-club"},
{"rank": 191, "brand": "Clean Your Dirty Face", "ulta_url": "https://www.ulta.com/brand/clean-your-dirty-face"},
{"rank": 192, "brand": "Cleanlogic", "ulta_url": "https://www.ulta.com/brand/cleanlogic"},
{"rank": 193, "brand": "ClearDea.", "ulta_url": "https://www.ulta.com/brand/cleardea"},
{"rank": 194, "brand": "Cleverman", "ulta_url": "https://www.ulta.com/brand/cleverman"},
{"rank": 195, "brand": "Clinique", "ulta_url": "https://www.ulta.com/brand/clinique"},
{"rank": 196, "brand": "clöud café", "ulta_url": "https://www.ulta.com/brand/cloud-cafe"},
{"rank": 197, "brand": "CND", "ulta_url": "https://www.ulta.com/brand/cnd"},
{"rank": 198, "brand": "CNP Laboratory", "ulta_url": "https://www.ulta.com/brand/cnp-laboratory"},
{"rank": 199, "brand": "Coach", "ulta_url": "https://www.ulta.com/brand/coach"},
{"rank": 200, "brand": "Coco & Eve", "ulta_url": "https://www.ulta.com/brand/coco-eve"},
{"rank": 201, "brand": "cocokind", "ulta_url": "https://www.ulta.com/brand/cocokind"},
{"rank": 202, "brand": "CODEAGE", "ulta_url": "https://www.ulta.com/brand/codeage"},
{"rank": 203, "brand": "Codex Labs", "ulta_url": "https://www.ulta.com/brand/codex-labs"},
{"rank": 204, "brand": "Color Wow", "ulta_url": "https://www.ulta.com/brand/color-wow"},
{"rank": 205, "brand": "ColourPop", "ulta_url": "https://www.ulta.com/brand/colourpop"},
{"rank": 206, "brand": "Conair", "ulta_url": "https://www.ulta.com/brand/conair"},
{"rank": 207, "brand": "Conair Accessories", "ulta_url": "https://www.ulta.com/brand/conair-accessories"},
{"rank": 208, "brand": "Contently", "ulta_url": "https://www.ulta.com/brand/contently"},
{"rank": 209, "brand": "COOLA", "ulta_url": "https://www.ulta.com/brand/coola"},
{"rank": 210, "brand": "CORPUS", "ulta_url": "https://www.ulta.com/brand/corpus"},
{"rank": 211, "brand": "CosmoGlo", "ulta_url": "https://www.ulta.com/brand/cosmoglo"},
{"rank": 212, "brand": "Cosnori", "ulta_url": "https://www.ulta.com/brand/cosnori"},
{"rank": 213, "brand": "COSRX", "ulta_url": "https://www.ulta.com/brand/cosrx"},
{"rank": 214, "brand": "CoverGirl", "ulta_url": "https://www.ulta.com/brand/covergirl"},
{"rank": 215, "brand": "Cozy Clip", "ulta_url": "https://www.ulta.com/brand/cozy-clip"},
{"rank": 216, "brand": "Crave", "ulta_url": "https://www.ulta.com/brand/crave"},
{"rank": 217, "brand": "Cricket", "ulta_url": "https://www.ulta.com/brand/cricket"},
{"rank": 218, "brand": "CROC", "ulta_url": "https://www.ulta.com/brand/croc"},
{"rank": 219, "brand": "CRVFT", "ulta_url": "https://www.ulta.com/brand/crvft"},
{"rank": 220, "brand": "Cure Hydration", "ulta_url": "https://www.ulta.com/brand/cure-hydration"},
{"rank": 221, "brand": "Curl Keeper", "ulta_url": "https://www.ulta.com/brand/curl-keeper"},
{"rank": 222, "brand": "CurlMix", "ulta_url": "https://www.ulta.com/brand/curlmix"},
{"rank": 223, "brand": "Curlsmith", "ulta_url": "https://www.ulta.com/brand/curlsmith"},
{"rank": 224, "brand": "Cutting Edge", "ulta_url": "https://www.ulta.com/brand/cutting-edge"},
{"rank": 225, "brand": "Cymbiotika", "ulta_url": "https://www.ulta.com/brand/cymbiotika"},
{"rank": 226, "brand": "CÉCRED", "ulta_url": "https://www.ulta.com/brand/cecred"},
{"rank": 227, "brand": "d'Alba Piedmont", "ulta_url": "https://www.ulta.com/brand/dalba-piedmont"},
{"rank": 228, "brand": "Daeng Gi Meo Ri", "ulta_url": "https://www.ulta.com/brand/daeng-gi-meo-ri"},
{"rank": 229, "brand": "Daily Habits", "ulta_url": "https://www.ulta.com/brand/daily-habits"},
{"rank": 230, "brand": "DAISE", "ulta_url": "https://www.ulta.com/brand/daise"},
{"rank": 231, "brand": "Dashing Diva", "ulta_url": "https://www.ulta.com/brand/dashing-diva"},
{"rank": 232, "brand": "dearcloud", "ulta_url": "https://www.ulta.com/brand/dearcloud"},
{"rank": 233, "brand": "Decorté", "ulta_url": "https://www.ulta.com/brand/decorte"},
{"rank": 234, "brand": "Dehiya Beauty", "ulta_url": "https://www.ulta.com/brand/dehiya-beauty"},
{"rank": 235, "brand": "Denman", "ulta_url": "https://www.ulta.com/brand/denman"},
{"rank": 236, "brand": "DERMA E", "ulta_url": "https://www.ulta.com/brand/derma-e"},
{"rank": 237, "brand": "Dermablend", "ulta_url": "https://www.ulta.com/brand/dermablend"},
{"rank": 238, "brand": "DERMAFLASH", "ulta_url": "https://www.ulta.com/brand/dermaflash"},
{"rank": 239, "brand": "Dermalogica", "ulta_url": "https://www.ulta.com/brand/dermalogica"},
{"rank": 240, "brand": "Dermasuri", "ulta_url": "https://www.ulta.com/brand/dermasuri"},
{"rank": 241, "brand": "Dermelect", "ulta_url": "https://www.ulta.com/brand/dermelect"},
{"rank": 242, "brand": "Design Essentials", "ulta_url": "https://www.ulta.com/brand/design-essentials"},
{"rank": 243, "brand": "DevaCurl", "ulta_url": "https://www.ulta.com/brand/devacurl"},
{"rank": 244, "brand": "DHC", "ulta_url": "https://www.ulta.com/brand/dhc"},
{"rank": 245, "brand": "Diamond Drunk", "ulta_url": "https://www.ulta.com/brand/diamond-drunk"},
{"rank": 246, "brand": "Diane", "ulta_url": "https://www.ulta.com/brand/diane"},
{"rank": 247, "brand": "DIBS Beauty", "ulta_url": "https://www.ulta.com/brand/dibs-beauty"},
{"rank": 248, "brand": "Differin", "ulta_url": "https://www.ulta.com/brand/differin"},
{"rank": 249, "brand": "DIME", "ulta_url": "https://www.ulta.com/brand/dime"},
{"rank": 250, "brand": "Dinto", "ulta_url": "https://www.ulta.com/brand/dinto"},
{"rank": 251, "brand": "Dionis", "ulta_url": "https://www.ulta.com/brand/dionis"},
{"rank": 252, "brand": "Dior", "ulta_url": "https://www.ulta.com/brand/dior"},
{"rank": 253, "brand": "Divi", "ulta_url": "https://www.ulta.com/brand/divi"},
{"rank": 254, "brand": "DKNY", "ulta_url": "https://www.ulta.com/brand/dkny"},
{"rank": 255, "brand": "Dolce Glow", "ulta_url": "https://www.ulta.com/brand/dolce-glow"},
{"rank": 256, "brand": "Dolce&Gabbana", "ulta_url": "https://www.ulta.com/brand/dolce-gabbana"},
{"rank": 257, "brand": "Doll 10", "ulta_url": "https://www.ulta.com/brand/doll-10"},
{"rank": 258, "brand": "Donna Karan", "ulta_url": "https://www.ulta.com/brand/donna-karan"},
{"rank": 259, "brand": "DONNA'S RECIPE", "ulta_url": "https://www.ulta.com/brand/donnas-recipe"},
{"rank": 260, "brand": "Doré", "ulta_url": "https://www.ulta.com/brand/dore"},
{"rank": 261, "brand": "dpHUE", "ulta_url": "https://www.ulta.com/brand/dphue"},
{"rank": 262, "brand": "Dr Rossi, Derm MD", "ulta_url": "https://www.ulta.com/brand/dr-rossi-derm-md"},
{"rank": 263, "brand": "Dr Teal's", "ulta_url": "https://www.ulta.com/brand/dr-teals"},
{"rank": 264, "brand": "Dr. Althea", "ulta_url": "https://www.ulta.com/brand/dr-althea"},
{"rank": 265, "brand": "Dr. Brandt", "ulta_url": "https://www.ulta.com/brand/dr-brandt"},
{"rank": 266, "brand": "Dr. Melaxin", "ulta_url": "https://www.ulta.com/brand/dr-melaxin"},
{"rank": 267, "brand": "Dr. PAWPAW", "ulta_url": "https://www.ulta.com/brand/dr-pawpaw"},
{"rank": 268, "brand": "Dr. Squatch", "ulta_url": "https://www.ulta.com/brand/dr-squatch"},
{"rank": 269, "brand": "Dr.Reju-All", "ulta_url": "https://www.ulta.com/brand/drreju-all"},
{"rank": 270, "brand": "DRMTLGY", "ulta_url": "https://www.ulta.com/brand/drmtlgy"},
{"rank": 271, "brand": "Drowsy", "ulta_url": "https://www.ulta.com/brand/drowsy"},
{"rank": 272, "brand": "Drunk Elephant", "ulta_url": "https://www.ulta.com/brand/drunk-elephant", "instagram": "https://www.instagram.com/drunkelephant", "twitter": "https://x.com/drunkelephant"},
{"rank": 273, "brand": "Drybar", "ulta_url": "https://www.ulta.com/brand/drybar"},
{"rank": 274, "brand": "Dryope", "ulta_url": "https://www.ulta.com/brand/dryope"},
{"rank": 275, "brand": "DS Laboratories", "ulta_url": "https://www.ulta.com/brand/ds-laboratories"},
{"rank": 276, "brand": "DUFT & DOFT", "ulta_url": "https://www.ulta.com/brand/duft-doft"},
{"rank": 277, "brand": "DUNE SUNCARE", "ulta_url": "https://www.ulta.com/brand/dune-suncare"},
{"rank": 278, "brand": "Duo Toothpaste", "ulta_url": "https://www.ulta.com/brand/duo-toothpaste"},
{"rank": 279, "brand": "Dyson", "ulta_url": "https://www.ulta.com/brand/dyson"},
{"rank": 280, "brand": "Dēp Slēpwear", "ulta_url": "https://www.ulta.com/brand/dep-slepwear"},
{"rank": 281, "brand": "e.l.f. Cosmetics", "ulta_url": "https://www.ulta.com/brand/elf-cosmetics"},
{"rank": 282, "brand": "Each & Every", "ulta_url": "https://www.ulta.com/brand/each-every"},
{"rank": 283, "brand": "Earth Harbor", "ulta_url": "https://www.ulta.com/brand/earth-harbor"},
{"rank": 284, "brand": "Earth Therapeutics", "ulta_url": "https://www.ulta.com/brand/earth-therapeutics"},
{"rank": 285, "brand": "Eco Style", "ulta_url": "https://www.ulta.com/brand/eco-style"},
{"rank": 286, "brand": "Ecolline", "ulta_url": "https://www.ulta.com/brand/ecolline"},
{"rank": 287, "brand": "EcoTools", "ulta_url": "https://www.ulta.com/brand/ecotools"},
{"rank": 288, "brand": "Element Brooklyn", "ulta_url": "https://www.ulta.com/brand/element-brooklyn"},
{"rank": 289, "brand": "ELEMIS", "ulta_url": "https://www.ulta.com/brand/elemis"},
{"rank": 290, "brand": "Elizabeth Arden", "ulta_url": "https://www.ulta.com/brand/elizabeth-arden"},
{"rank": 291, "brand": "Elizavecca", "ulta_url": "https://www.ulta.com/brand/elizavecca"},
{"rank": 292, "brand": "Ellis Brooklyn", "ulta_url": "https://www.ulta.com/brand/ellis-brooklyn"},
{"rank": 293, "brand": "Embr Labs", "ulta_url": "https://www.ulta.com/brand/embr-labs"},
{"rank": 294, "brand": "EMBRYOLISSE", "ulta_url": "https://www.ulta.com/brand/embryolisse"},
{"rank": 295, "brand": "ENVIRONMENT", "ulta_url": "https://www.ulta.com/brand/environment"},
{"rank": 296, "brand": "Enzo Milano", "ulta_url": "https://www.ulta.com/brand/enzo-milano"},
{"rank": 297, "brand": "Eos", "ulta_url": "https://www.ulta.com/brand/eos"},
{"rank": 298, "brand": "Equlib", "ulta_url": "https://www.ulta.com/brand/equlib"},
{"rank": 299, "brand": "Erborian", "ulta_url": "https://www.ulta.com/brand/erborian"},
{"rank": 300, "brand": "Ere Perez", "ulta_url": "https://www.ulta.com/brand/ere-perez"},
{"rank": 301, "brand": "ERLY", "ulta_url": "https://www.ulta.com/brand/erly"},
{"rank": 302, "brand": "Esha", "ulta_url": "https://www.ulta.com/brand/esha"},
{"rank": 303, "brand": "Esker Beauty", "ulta_url": "https://www.ulta.com/brand/esker-beauty"},
{"rank": 304, "brand": "Essence", "ulta_url": "https://www.ulta.com/brand/essence"},
{"rank": 305, "brand": "Essie", "ulta_url": "https://www.ulta.com/brand/essie"},
{"rank": 306, "brand": "Estée Lauder", "ulta_url": "https://www.ulta.com/brand/estee-lauder", "instagram": "https://www.instagram.com/esteelauder", "twitter": "https://x.com/EsteeLauder"},
{"rank": 307, "brand": "Ethique Beauty", "ulta_url": "https://www.ulta.com/brand/ethique-beauty"},
{"rank": 308, "brand": "Ettitude", "ulta_url": "https://www.ulta.com/brand/ettitude"},
{"rank": 309, "brand": "ETUDE", "ulta_url": "https://www.ulta.com/brand/etude"},
{"rank": 310, "brand": "Eucerin", "ulta_url": "https://www.ulta.com/brand/eucerin"},
{"rank": 311, "brand": "Eva Nyc", "ulta_url": "https://www.ulta.com/brand/eva-nyc"},
{"rank": 312, "brand": "EvasHair", "ulta_url": "https://www.ulta.com/brand/evashair"},
{"rank": 313, "brand": "Eve Lom", "ulta_url": "https://www.ulta.com/brand/eve-lom"},
{"rank": 314, "brand": "Evian Mineral Spray", "ulta_url": "https://www.ulta.com/brand/evian-mineral-spray"},
{"rank": 315, "brand": "Evil Goods", "ulta_url": "https://www.ulta.com/brand/evil-goods"},
{"rank": 316, "brand": "Evre Skincare", "ulta_url": "https://www.ulta.com/brand/evre-skincare"},
{"rank": 317, "brand": "Exoceuticals", "ulta_url": "https://www.ulta.com/brand/exoceuticals"},
{"rank": 318, "brand": "Exuviance", "ulta_url": "https://www.ulta.com/brand/exuviance"},
{"rank": 319, "brand": "Eyeko", "ulta_url": "https://www.ulta.com/brand/eyeko"},
{"rank": 320, "brand": "Eylure", "ulta_url": "https://www.ulta.com/brand/eylure"},
{"rank": 321, "brand": "Face Republic", "ulta_url": "https://www.ulta.com/brand/face-republic"},
{"rank": 322, "brand": "Fairy Tales", "ulta_url": "https://www.ulta.com/brand/fairy-tales"},
{"rank": 323, "brand": "FARMACY", "ulta_url": "https://www.ulta.com/brand/farmacy"},
{"rank": 324, "brand": "FEKKAI", "ulta_url": "https://www.ulta.com/brand/fekkai"},
{"rank": 325, "brand": "FENTY BEAUTY by Rihanna", "ulta_url": "https://www.ulta.com/brand/fenty-beauty-by-rihanna"},
{"rank": 326, "brand": "FENTY SKIN body", "ulta_url": "https://www.ulta.com/brand/fenty-skin-body"},
{"rank": 327, "brand": "FilterBaby", "ulta_url": "https://www.ulta.com/brand/filterbaby"},
{"rank": 328, "brand": "First Aid Beauty", "ulta_url": "https://www.ulta.com/brand/first-aid-beauty"},
{"rank": 329, "brand": "Flimeal", "ulta_url": "https://www.ulta.com/brand/flimeal"},
{"rank": 330, "brand": "Flora Code", "ulta_url": "https://www.ulta.com/brand/flora-code"},
{"rank": 331, "brand": "Floral Street", "ulta_url": "https://www.ulta.com/brand/floral-street"},
{"rank": 332, "brand": "Florasis", "ulta_url": "https://www.ulta.com/brand/florasis"},
{"rank": 333, "brand": "florence by mills", "ulta_url": "https://www.ulta.com/brand/florence-by-mills"},
{"rank": 334, "brand": "Flower Knows", "ulta_url": "https://www.ulta.com/brand/flower-knows"},
{"rank": 335, "brand": "Flowery", "ulta_url": "https://www.ulta.com/brand/flowery"},
{"rank": 336, "brand": "FMS", "ulta_url": "https://www.ulta.com/brand/fms"},
{"rank": 337, "brand": "FOREO", "ulta_url": "https://www.ulta.com/brand/foreo"},
{"rank": 338, "brand": "Foria", "ulta_url": "https://www.ulta.com/brand/foria"},
{"rank": 339, "brand": "Forte Series", "ulta_url": "https://www.ulta.com/brand/forte-series"},
{"rank": 340, "brand": "frank body", "ulta_url": "https://www.ulta.com/brand/frank-body"},
{"rank": 341, "brand": "fresh", "ulta_url": "https://www.ulta.com/brand/fresh"},
{"rank": 342, "brand": "Fromm", "ulta_url": "https://www.ulta.com/brand/fromm"},
{"rank": 343, "brand": "FRUDIA", "ulta_url": "https://www.ulta.com/brand/frudia"},
{"rank": 344, "brand": "Fur", "ulta_url": "https://www.ulta.com/brand/fur"},
{"rank": 345, "brand": "fwee", "ulta_url": "https://www.ulta.com/brand/fwee"},
{"rank": 346, "brand": "Ga.Ma Italy Professional", "ulta_url": "https://www.ulta.com/brand/gama-italy-professional"},
{"rank": 347, "brand": "Garden of Life", "ulta_url": "https://www.ulta.com/brand/garden-of-life"},
{"rank": 348, "brand": "Garnier", "ulta_url": "https://www.ulta.com/brand/garnier"},
{"rank": 349, "brand": "Geologie", "ulta_url": "https://www.ulta.com/brand/geologie"},
{"rank": 350, "brand": "Geske", "ulta_url": "https://www.ulta.com/brand/geske"},
{"rank": 351, "brand": "ghd", "ulta_url": "https://www.ulta.com/brand/ghd"},
{"rank": 352, "brand": "Gigi", "ulta_url": "https://www.ulta.com/brand/gigi"},
{"rank": 353, "brand": "GIMME beauty", "ulta_url": "https://www.ulta.com/brand/gimme-beauty"},
{"rank": 354, "brand": "Ginger Milk", "ulta_url": "https://www.ulta.com/brand/ginger-milk"},
{"rank": 355, "brand": "Givenchy", "ulta_url": "https://www.ulta.com/brand/givenchy"},
{"rank": 356, "brand": "Glam & Grace", "ulta_url": "https://www.ulta.com/brand/glam-grace"},
{"rank": 357, "brand": "Glamnetic", "ulta_url": "https://www.ulta.com/brand/glamnetic"},
{"rank": 358, "brand": "Glamnetic x Fanatics Nail", "ulta_url": "https://www.ulta.com/brand/glamnetic-x-fanatics-nail"},
{"rank": 359, "brand": "Glimmer Wish", "ulta_url": "https://www.ulta.com/brand/glimmer-wish"},
{"rank": 360, "brand": "GLISTER", "ulta_url": "https://www.ulta.com/brand/glister"},
{"rank": 361, "brand": "Glo24k", "ulta_url": "https://www.ulta.com/brand/glo24k"},
{"rank": 362, "brand": "glowiest", "ulta_url": "https://www.ulta.com/brand/glowiest"},
{"rank": 363, "brand": "Goli Nutrition", "ulta_url": "https://www.ulta.com/brand/goli-nutrition"},
{"rank": 364, "brand": "good day by Patchology", "ulta_url": "https://www.ulta.com/brand/good-day-by-patchology"},
{"rank": 365, "brand": "Good Dye Young", "ulta_url": "https://www.ulta.com/brand/good-dye-young"},
{"rank": 366, "brand": "good light", "ulta_url": "https://www.ulta.com/brand/good-light"},
{"rank": 367, "brand": "Good Molecules", "ulta_url": "https://www.ulta.com/brand/good-molecules"},
{"rank": 368, "brand": "GOONGBE", "ulta_url": "https://www.ulta.com/brand/goongbe"},
{"rank": 369, "brand": "goop", "ulta_url": "https://www.ulta.com/brand/goop"},
{"rank": 370, "brand": "got2b", "ulta_url": "https://www.ulta.com/brand/got2b"},
{"rank": 371, "brand": "Grande Cosmetics", "ulta_url": "https://www.ulta.com/brand/grande-cosmetics"},
{"rank": 372, "brand": "GROWUS", "ulta_url": "https://www.ulta.com/brand/growus"},
{"rank": 373, "brand": "Grüns", "ulta_url": "https://www.ulta.com/brand/gruns"},
{"rank": 374, "brand": "Gucci", "ulta_url": "https://www.ulta.com/brand/gucci"},
{"rank": 375, "brand": "Guerlain", "ulta_url": "https://www.ulta.com/brand/guerlain"},
{"rank": 376, "brand": "GuruNanda", "ulta_url": "https://www.ulta.com/brand/gurunanda"},
{"rank": 377, "brand": "HAAN", "ulta_url": "https://www.ulta.com/brand/haan"},
{"rank": 378, "brand": "HackU", "ulta_url": "https://www.ulta.com/brand/hacku"},
{"rank": 379, "brand": "Hair+", "ulta_url": "https://www.ulta.com/brand/hair"},
{"rank": 380, "brand": "Hairmax", "ulta_url": "https://www.ulta.com/brand/hairmax"},
{"rank": 381, "brand": "Hairstory", "ulta_url": "https://www.ulta.com/brand/hairstory"},
{"rank": 382, "brand": "HAIRtamin", "ulta_url": "https://www.ulta.com/brand/hairtamin"},
{"rank": 383, "brand": "HALEYS Beauty", "ulta_url": "https://www.ulta.com/brand/haleys-beauty"},
{"rank": 384, "brand": "HALF MAGIC", "ulta_url": "https://www.ulta.com/brand/half-magic"},
{"rank": 385, "brand": "HALLY", "ulta_url": "https://www.ulta.com/brand/hally"},
{"rank": 386, "brand": "Hampton Sun", "ulta_url": "https://www.ulta.com/brand/hampton-sun"},
{"rank": 387, "brand": "Hanskin", "ulta_url": "https://www.ulta.com/brand/hanskin"},
{"rank": 388, "brand": "HAPPYSKINCO", "ulta_url": "https://www.ulta.com/brand/happyskinco"},
{"rank": 389, "brand": "Hatch", "ulta_url": "https://www.ulta.com/brand/hatch"},
{"rank": 390, "brand": "HATCH MAMA", "ulta_url": "https://www.ulta.com/brand/hatch-mama"},
{"rank": 391, "brand": "Hauteness", "ulta_url": "https://www.ulta.com/brand/hauteness"},
{"rank": 392, "brand": "Hawkins & Brimble", "ulta_url": "https://www.ulta.com/brand/hawkins-brimble"},
{"rank": 393, "brand": "Hawthorne", "ulta_url": "https://www.ulta.com/brand/hawthorne"},
{"rank": 394, "brand": "Healing Bird", "ulta_url": "https://www.ulta.com/brand/healing-bird"},
{"rank": 395, "brand": "Heimish", "ulta_url": "https://www.ulta.com/brand/heimish"},
{"rank": 396, "brand": "Helight", "ulta_url": "https://www.ulta.com/brand/helight"},
{"rank": 397, "brand": "Hempz", "ulta_url": "https://www.ulta.com/brand/hempz"},
{"rank": 398, "brand": "Her Own", "ulta_url": "https://www.ulta.com/brand/her-own"},
{"rank": 399, "brand": "HERBIVORE", "ulta_url": "https://www.ulta.com/brand/herbivore"},
{"rank": 400, "brand": "Heritage Store", "ulta_url": "https://www.ulta.com/brand/heritage-store"},
{"rank": 401, "brand": "Hero Cosmetics", "ulta_url": "https://www.ulta.com/brand/hero-cosmetics"},
{"rank": 402, "brand": "Hey Honey", "ulta_url": "https://www.ulta.com/brand/hey-honey"},
{"rank": 403, "brand": "Heywell", "ulta_url": "https://www.ulta.com/brand/heywell"},
{"rank": 404, "brand": "HigherDOSE", "ulta_url": "https://www.ulta.com/brand/higherdose"},
{"rank": 405, "brand": "Hollywood Fashion Secrets", "ulta_url": "https://www.ulta.com/brand/hollywood-fashion-secrets"},
{"rank": 406, "brand": "Holo Taco", "ulta_url": "https://www.ulta.com/brand/holo-taco"},
{"rank": 407, "brand": "Homebody", "ulta_url": "https://www.ulta.com/brand/homebody"},
{"rank": 408, "brand": "Honest Beauty", "ulta_url": "https://www.ulta.com/brand/honest-beauty"},
{"rank": 409, "brand": "Hot Tools", "ulta_url": "https://www.ulta.com/brand/hot-tools"},
{"rank": 410, "brand": "HOURGLASS", "ulta_url": "https://www.ulta.com/brand/hourglass"},
{"rank": 411, "brand": "hOURS haircare", "ulta_url": "https://www.ulta.com/brand/hours-haircare"},
{"rank": 412, "brand": "House of Foils", "ulta_url": "https://www.ulta.com/brand/house-of-foils"},
{"rank": 413, "brand": "House of Harlow 1960", "ulta_url": "https://www.ulta.com/brand/house-of-harlow-1960"},
{"rank": 414, "brand": "House of Lashes", "ulta_url": "https://www.ulta.com/brand/house-of-lashes"},
{"rank": 415, "brand": "Hugger Mugger", "ulta_url": "https://www.ulta.com/brand/hugger-mugger"},
{"rank": 416, "brand": "Hugo Boss", "ulta_url": "https://www.ulta.com/brand/hugo-boss"},
{"rank": 417, "brand": "Hum Nutrition", "ulta_url": "https://www.ulta.com/brand/hum-nutrition"},
{"rank": 418, "brand": "Humanist Beauty", "ulta_url": "https://www.ulta.com/brand/humanist-beauty"},
{"rank": 419, "brand": "Hwarang", "ulta_url": "https://www.ulta.com/brand/hwarang"},
{"rank": 420, "brand": "Hyggee", "ulta_url": "https://www.ulta.com/brand/hyggee"},
{"rank": 421, "brand": "Hygiene Hero", "ulta_url": "https://www.ulta.com/brand/hygiene-hero"},
{"rank": 422, "brand": "Hypothesis", "ulta_url": "https://www.ulta.com/brand/hypothesis"},
{"rank": 423, "brand": "I Dew Care", "ulta_url": "https://www.ulta.com/brand/i-dew-care"},
{"rank": 424, "brand": "I'm From", "ulta_url": "https://www.ulta.com/brand/im-from"},
{"rank": 425, "brand": "Ialuset", "ulta_url": "https://www.ulta.com/brand/ialuset"},
{"rank": 426, "brand": "ICONIC LONDON", "ulta_url": "https://www.ulta.com/brand/iconic-london"},
{"rank": 427, "brand": "iDesign", "ulta_url": "https://www.ulta.com/brand/idesign"},
{"rank": 428, "brand": "IGK", "ulta_url": "https://www.ulta.com/brand/igk"},
{"rank": 429, "brand": "iHome", "ulta_url": "https://www.ulta.com/brand/ihome"},
{"rank": 430, "brand": "ILIA", "ulta_url": "https://www.ulta.com/brand/ilia"},
{"rank": 431, "brand": "Ilso", "ulta_url": "https://www.ulta.com/brand/ilso"},
{"rank": 432, "brand": "Imarais Beauty", "ulta_url": "https://www.ulta.com/brand/imarais-beauty"},
{"rank": 433, "brand": "Impressions Vanity", "ulta_url": "https://www.ulta.com/brand/impressions-vanity"},
{"rank": 434, "brand": "In Common", "ulta_url": "https://www.ulta.com/brand/in-common"},
{"rank": 435, "brand": "INDIE LEE", "ulta_url": "https://www.ulta.com/brand/indie-lee"},
{"rank": 436, "brand": "InfoDPlus", "ulta_url": "https://www.ulta.com/brand/infodplus"},
{"rank": 437, "brand": "inh HAIR", "ulta_url": "https://www.ulta.com/brand/inh-hair"},
{"rank": 438, "brand": "Inked by Dani", "ulta_url": "https://www.ulta.com/brand/inked-by-dani"},
{"rank": 439, "brand": "INNER CIRCLE", "ulta_url": "https://www.ulta.com/brand/inner-circle"},
{"rank": 440, "brand": "Innersense Organic Beauty", "ulta_url": "https://www.ulta.com/brand/innersense-organic-beauty"},
{"rank": 441, "brand": "iota", "ulta_url": "https://www.ulta.com/brand/iota"},
{"rank": 442, "brand": "isima", "ulta_url": "https://www.ulta.com/brand/isima"},
{"rank": 443, "brand": "ISOI", "ulta_url": "https://www.ulta.com/brand/isoi"},
{"rank": 444, "brand": "Isopure Protein", "ulta_url": "https://www.ulta.com/brand/isopure-protein"},
{"rank": 445, "brand": "IT Brushes For ULTA", "ulta_url": "https://www.ulta.com/brand/it-brushes-ulta"},
{"rank": 446, "brand": "IT Cosmetics", "ulta_url": "https://www.ulta.com/brand/it-cosmetics"},
{"rank": 447, "brand": "It's A 10", "ulta_url": "https://www.ulta.com/brand/its-a-10"},
{"rank": 448, "brand": "iUNIK", "ulta_url": "https://www.ulta.com/brand/iunik"},
{"rank": 449, "brand": "Izzy Zero Waste Beauty", "ulta_url": "https://www.ulta.com/brand/izzy-zero-waste-beauty"},
{"rank": 450, "brand": "J.Cat Beauty", "ulta_url": "https://www.ulta.com/brand/jcat-beauty"},
{"rank": 451, "brand": "Jack Black", "ulta_url": "https://www.ulta.com/brand/jack-black"},
{"rank": 452, "brand": "Jack Henry", "ulta_url": "https://www.ulta.com/brand/jack-henry"},
{"rank": 453, "brand": "Jackfir", "ulta_url": "https://www.ulta.com/brand/jackfir"},
{"rank": 454, "brand": "jane iredale", "ulta_url": "https://www.ulta.com/brand/jane-iredale"},
{"rank": 455, "brand": "Janet Collection", "ulta_url": "https://www.ulta.com/brand/janet-collection"},
{"rank": 456, "brand": "JB Skrub", "ulta_url": "https://www.ulta.com/brand/jb-skrub"},
{"rank": 457, "brand": "Jean Paul Gaultier", "ulta_url": "https://www.ulta.com/brand/jean-paul-gaultier"},
{"rank": 458, "brand": "Jenny Patinkin", "ulta_url": "https://www.ulta.com/brand/jenny-patinkin"},
{"rank": 459, "brand": "Jill", "ulta_url": "https://www.ulta.com/brand/jill"},
{"rank": 460, "brand": "Jimmy Choo", "ulta_url": "https://www.ulta.com/brand/jimmy-choo"},
{"rank": 461, "brand": "Joan & David", "ulta_url": "https://www.ulta.com/brand/joan-david"},
{"rank": 462, "brand": "Johnny B. Hair Care", "ulta_url": "https://www.ulta.com/brand/johnny-b-hair-care"},
{"rank": 463, "brand": "Joico", "ulta_url": "https://www.ulta.com/brand/joico"},
{"rank": 464, "brand": "Jolie", "ulta_url": "https://www.ulta.com/brand/jolie"},
{"rank": 465, "brand": "JooY", "ulta_url": "https://www.ulta.com/brand/jooy"},
{"rank": 466, "brand": "Jouer Cosmetics", "ulta_url": "https://www.ulta.com/brand/jouer-cosmetics"},
{"rank": 467, "brand": "JoyBright by Ulta Beauty", "ulta_url": "https://www.ulta.com/brand/joybright-by-ulta-beauty"},
{"rank": 468, "brand": "Joylux", "ulta_url": "https://www.ulta.com/brand/joylux"},
{"rank": 469, "brand": "JudyDoll", "ulta_url": "https://www.ulta.com/brand/judydoll"},
{"rank": 470, "brand": "Juicy Couture", "ulta_url": "https://www.ulta.com/brand/juicy-couture"},
{"rank": 471, "brand": "JUNOCO", "ulta_url": "https://www.ulta.com/brand/junoco"},
{"rank": 472, "brand": "Juvia's Place", "ulta_url": "https://www.ulta.com/brand/juvias-place"},
{"rank": 473, "brand": "JVN", "ulta_url": "https://www.ulta.com/brand/jvn"},
{"rank": 474, "brand": "KAHI", "ulta_url": "https://www.ulta.com/brand/kahi"},
{"rank": 475, "brand": "Kaine", "ulta_url": "https://www.ulta.com/brand/kaine"},
{"rank": 476, "brand": "Kaja", "ulta_url": "https://www.ulta.com/brand/kaja"},
{"rank": 477, "brand": "Kate Somerville", "ulta_url": "https://www.ulta.com/brand/kate-somerville"},
{"rank": 478, "brand": "Kate Spade New York", "ulta_url": "https://www.ulta.com/brand/kate-spade-new-york"},
{"rank": 479, "brand": "Kenneth Cole New York", "ulta_url": "https://www.ulta.com/brand/kenneth-cole-new-york"},
{"rank": 480, "brand": "Kenra Professional", "ulta_url": "https://www.ulta.com/brand/kenra-professional"},
{"rank": 481, "brand": "Keracolor", "ulta_url": "https://www.ulta.com/brand/keracolor"},
{"rank": 482, "brand": "Keranique", "ulta_url": "https://www.ulta.com/brand/keranique"},
{"rank": 483, "brand": "Keratin Complex", "ulta_url": "https://www.ulta.com/brand/keratin-complex"},
{"rank": 484, "brand": "Kevyn Aucoin", "ulta_url": "https://www.ulta.com/brand/kevyn-aucoin"},
{"rank": 485, "brand": "KHLOÉ KARDASHIAN", "ulta_url": "https://www.ulta.com/brand/khloe-kardashian"},
{"rank": 486, "brand": "Kiehl's Since 1851", "ulta_url": "https://www.ulta.com/brand/kiehls-since-1851"},
{"rank": 487, "brand": "KimChi Chic Beauty", "ulta_url": "https://www.ulta.com/brand/kimchi-chic-beauty"},
{"rank": 488, "brand": "Kind Patches", "ulta_url": "https://www.ulta.com/brand/kind-patches"},
{"rank": 489, "brand": "Kings Domain Melbourne", "ulta_url": "https://www.ulta.com/brand/kings-domain-melbourne"},
{"rank": 490, "brand": "Kiss", "ulta_url": "https://www.ulta.com/brand/kiss"},
{"rank": 491, "brand": "Kitsch", "ulta_url": "https://www.ulta.com/brand/kitsch"},
{"rank": 492, "brand": "Klairs", "ulta_url": "https://www.ulta.com/brand/klairs"},
{"rank": 493, "brand": "Knemo", "ulta_url": "https://www.ulta.com/brand/knemo"},
{"rank": 494, "brand": "Knours.", "ulta_url": "https://www.ulta.com/brand/knours"},
{"rank": 495, "brand": "KOCOSTAR", "ulta_url": "https://www.ulta.com/brand/kocostar"},
{"rank": 496, "brand": "Kopari Beauty", "ulta_url": "https://www.ulta.com/brand/kopari-beauty"},
{"rank": 497, "brand": "KORRES", "ulta_url": "https://www.ulta.com/brand/korres"},
{"rank": 498, "brand": "Kreyòl Essence", "ulta_url": "https://www.ulta.com/brand/kreyol-essence"},
{"rank": 499, "brand": "KRISTIN ESS HAIR", "ulta_url": "https://www.ulta.com/brand/kristin-ess-hair"},
{"rank": 500, "brand": "Kumbra With Love", "ulta_url": "https://www.ulta.com/brand/kumbra-with-love"},
{"rank": 501, "brand": "KUNDAL", "ulta_url": "https://www.ulta.com/brand/kundal"},
{"rank": 502, "brand": "KVD Beauty", "ulta_url": "https://www.ulta.com/brand/kvd-beauty"},
{"rank": 503, "brand": "KYLIE COSMETICS", "ulta_url": "https://www.ulta.com/brand/kylie-cosmetics"},
{"rank": 504, "brand": "L'ange", "ulta_url": "https://www.ulta.com/brand/lange"},
{"rank": 505, "brand": "L'anza", "ulta_url": "https://www.ulta.com/brand/lanza"},
{"rank": 506, "brand": "L'Occitane", "ulta_url": "https://www.ulta.com/brand/loccitane"},
{"rank": 507, "brand": "L'Oréal", "ulta_url": "https://www.ulta.com/brand/loreal"},
{"rank": 508, "brand": "L'Oréal Professionnel", "ulta_url": "https://www.ulta.com/brand/loreal-professionnel"},
{"rank": 509, "brand": "L.A. Girl", "ulta_url": "https://www.ulta.com/brand/la-girl"},
{"rank": 510, "brand": "L3VEL3", "ulta_url": "https://www.ulta.com/brand/l3vel3"},
{"rank": 511, "brand": "La Roche-Posay", "ulta_url": "https://www.ulta.com/brand/la-roche-posay"},
{"rank": 512, "brand": "LADOR", "ulta_url": "https://www.ulta.com/brand/lador"},
{"rank": 513, "brand": "Laifen", "ulta_url": "https://www.ulta.com/brand/laifen"},
{"rank": 514, "brand": "Lake & Skye", "ulta_url": "https://www.ulta.com/brand/lake-skye"},
{"rank": 515, "brand": "LALARECIPE", "ulta_url": "https://www.ulta.com/brand/lalarecipe"},
{"rank": 516, "brand": "LAMIK Beauty", "ulta_url": "https://www.ulta.com/brand/lamik-beauty"},
{"rank": 517, "brand": "Lancer Skincare", "ulta_url": "https://www.ulta.com/brand/lancer-skincare"},
{"rank": 518, "brand": "Lancôme", "ulta_url": "https://www.ulta.com/brand/lancome"},
{"rank": 519, "brand": "Landing International", "ulta_url": "https://www.ulta.com/brand/landing-international"},
{"rank": 520, "brand": "Lanolips", "ulta_url": "https://www.ulta.com/brand/lanolips"},
{"rank": 521, "brand": "Lapcos", "ulta_url": "https://www.ulta.com/brand/lapcos"},
{"rank": 522, "brand": "Lash Luks", "ulta_url": "https://www.ulta.com/brand/lash-luks"},
{"rank": 523, "brand": "Lattafa", "ulta_url": "https://www.ulta.com/brand/lattafa"},
{"rank": 524, "brand": "Laundry Sauce", "ulta_url": "https://www.ulta.com/brand/laundry-sauce"},
{"rank": 525, "brand": "LAURA GELLER", "ulta_url": "https://www.ulta.com/brand/laura-geller"},
{"rank": 526, "brand": "Laura Mercier", "ulta_url": "https://www.ulta.com/brand/laura-mercier"},
{"rank": 527, "brand": "LAVANILA", "ulta_url": "https://www.ulta.com/brand/lavanila"},
{"rank": 528, "brand": "Le Mini Macaron", "ulta_url": "https://www.ulta.com/brand/le-mini-macaron"},
{"rank": 529, "brand": "LE MONDE GOURMAND", "ulta_url": "https://www.ulta.com/brand/le-monde-gourmand"},
{"rank": 530, "brand": "Leland Francis", "ulta_url": "https://www.ulta.com/brand/leland-francis"},
{"rank": 531, "brand": "Lemme", "ulta_url": "https://www.ulta.com/brand/lemme"},
{"rank": 532, "brand": "Lemon and Co. Collagen", "ulta_url": "https://www.ulta.com/brand/lemon-co-collagen"},
{"rank": 533, "brand": "Leonor Greyl", "ulta_url": "https://www.ulta.com/brand/leonor-greyl"},
{"rank": 534, "brand": "Leverden", "ulta_url": "https://www.ulta.com/brand/leverden"},
{"rank": 535, "brand": "LILA by Akunbem", "ulta_url": "https://www.ulta.com/brand/lila-by-akunbem"},
{"rank": 536, "brand": "Lilly Lashes", "ulta_url": "https://www.ulta.com/brand/lilly-lashes"},
{"rank": 537, "brand": "Lilyeve", "ulta_url": "https://www.ulta.com/brand/lilyeve"},
{"rank": 538, "brand": "Lime Crime", "ulta_url": "https://www.ulta.com/brand/lime-crime"},
{"rank": 539, "brand": "Lip Smacker", "ulta_url": "https://www.ulta.com/brand/lip-smacker"},
{"rank": 540, "brand": "LIQUID I.V.", "ulta_url": "https://www.ulta.com/brand/liquid-iv"},
{"rank": 541, "brand": "Live Tinted", "ulta_url": "https://www.ulta.com/brand/live-tinted"},
{"rank": 542, "brand": "Living Proof", "ulta_url": "https://www.ulta.com/brand/living-proof"},
{"rank": 543, "brand": "Locks & Mane", "ulta_url": "https://www.ulta.com/brand/locks-mane"},
{"rank": 544, "brand": "LOLA", "ulta_url": "https://www.ulta.com/brand/lola"},
{"rank": 545, "brand": "Lola From Rio", "ulta_url": "https://www.ulta.com/brand/lola-from-rio"},
{"rank": 546, "brand": "LolaVie", "ulta_url": "https://www.ulta.com/brand/lolavie"},
{"rank": 547, "brand": "Londontown", "ulta_url": "https://www.ulta.com/brand/londontown"},
{"rank": 548, "brand": "LOOPS", "ulta_url": "https://www.ulta.com/brand/loops"},
{"rank": 549, "brand": "LORAC", "ulta_url": "https://www.ulta.com/brand/lorac"},
{"rank": 550, "brand": "Lottie London", "ulta_url": "https://www.ulta.com/brand/lottie-london"},
{"rank": 551, "brand": "Love & Pebble", "ulta_url": "https://www.ulta.com/brand/love-pebble"},
{"rank": 552, "brand": "Love Wellness", "ulta_url": "https://www.ulta.com/brand/love-wellness"},
{"rank": 553, "brand": "Love, Indus", "ulta_url": "https://www.ulta.com/brand/love-indus"},
{"rank": 554, "brand": "Lovery", "ulta_url": "https://www.ulta.com/brand/lovery"},
{"rank": 555, "brand": "Loving Tan", "ulta_url": "https://www.ulta.com/brand/loving-tan"},
{"rank": 556, "brand": "Lume", "ulta_url": "https://www.ulta.com/brand/lume"},
{"rank": 557, "brand": "Lumify", "ulta_url": "https://www.ulta.com/brand/lumify"},
{"rank": 558, "brand": "LuminaNRG", "ulta_url": "https://www.ulta.com/brand/luminanrg"},
{"rank": 559, "brand": "Luna Bronze", "ulta_url": "https://www.ulta.com/brand/luna-bronze"},
{"rank": 560, "brand": "Luna Daily", "ulta_url": "https://www.ulta.com/brand/luna-daily"},
{"rank": 561, "brand": "Luna Nectar", "ulta_url": "https://www.ulta.com/brand/luna-nectar"},
{"rank": 562, "brand": "Lunar Beauty", "ulta_url": "https://www.ulta.com/brand/lunar-beauty"},
{"rank": 563, "brand": "Lunya", "ulta_url": "https://www.ulta.com/brand/lunya"},
{"rank": 564, "brand": "LUSH", "ulta_url": "https://www.ulta.com/brand/lush"},
{"rank": 565, "brand": "LUV SCRUB", "ulta_url": "https://www.ulta.com/brand/luv-scrub"},
{"rank": 566, "brand": "Luvum", "ulta_url": "https://www.ulta.com/brand/luvum"},
{"rank": 567, "brand": "M3", "ulta_url": "https://www.ulta.com/brand/m3"},
{"rank": 568, "brand": "ma:nyo", "ulta_url": "https://www.ulta.com/brand/manyo"},
{"rank": 569, "brand": "MAC", "ulta_url": "https://www.ulta.com/brand/mac"},
{"rank": 570, "brand": "Mad Hippie", "ulta_url": "https://www.ulta.com/brand/mad-hippie"},
{"rank": 571, "brand": "Mad Rabbit", "ulta_url": "https://www.ulta.com/brand/mad-rabbit"},
{"rank": 572, "brand": "Made By Mitchell", "ulta_url": "https://www.ulta.com/brand/made-by-mitchell"},
{"rank": 573, "brand": "Madeca Derma", "ulta_url": "https://www.ulta.com/brand/madeca-derma"},
{"rank": 574, "brand": "Madison Reed", "ulta_url": "https://www.ulta.com/brand/madison-reed"},
{"rank": 575, "brand": "Magic Molecule", "ulta_url": "https://www.ulta.com/brand/magic-molecule"},
{"rank": 576, "brand": "Maison Louis Marie", "ulta_url": "https://www.ulta.com/brand/maison-louis-marie"},
{"rank": 577, "brand": "Maison Noir", "ulta_url": "https://www.ulta.com/brand/maison-noir"},
{"rank": 578, "brand": "Makari", "ulta_url": "https://www.ulta.com/brand/makari"},
{"rank": 579, "brand": "Make Time Wellness", "ulta_url": "https://www.ulta.com/brand/make-time-wellness"},
{"rank": 580, "brand": "Malibu Apothecary", "ulta_url": "https://www.ulta.com/brand/malibu-apothecary"},
{"rank": 581, "brand": "Mania Holic", "ulta_url": "https://www.ulta.com/brand/mania-holic"},
{"rank": 582, "brand": "Manucurist", "ulta_url": "https://www.ulta.com/brand/manucurist"},
{"rank": 583, "brand": "Marc Jacobs", "ulta_url": "https://www.ulta.com/brand/marc-jacobs"},
{"rank": 584, "brand": "Marie Hunter", "ulta_url": "https://www.ulta.com/brand/marie-hunter"},
{"rank": 585, "brand": "Mario Badescu", "ulta_url": "https://www.ulta.com/brand/mario-badescu"},
{"rank": 586, "brand": "Marley Fragrance", "ulta_url": "https://www.ulta.com/brand/marley-fragrance"},
{"rank": 587, "brand": "MaryRuth's", "ulta_url": "https://www.ulta.com/brand/maryruths"},
{"rank": 588, "brand": "Masami", "ulta_url": "https://www.ulta.com/brand/masami"},
{"rank": 589, "brand": "Matrix", "ulta_url": "https://www.ulta.com/brand/matrix"},
{"rank": 590, "brand": "Maui Babe", "ulta_url": "https://www.ulta.com/brand/maui-babe"},
{"rank": 591, "brand": "Maybelline", "ulta_url": "https://www.ulta.com/brand/maybelline"},
{"rank": 592, "brand": "MAËLYS", "ulta_url": "https://www.ulta.com/brand/maelys"},
{"rank": 593, "brand": "MDSolarSciences", "ulta_url": "https://www.ulta.com/brand/mdsolarsciences"},
{"rank": 594, "brand": "Medicine Mama", "ulta_url": "https://www.ulta.com/brand/medicine-mama"},
{"rank": 595, "brand": "Medicool", "ulta_url": "https://www.ulta.com/brand/medicool"},
{"rank": 596, "brand": "medicube", "ulta_url": "https://www.ulta.com/brand/medicube"},
{"rank": 597, "brand": "MEDIHEAL", "ulta_url": "https://www.ulta.com/brand/mediheal"},
{"rank": 598, "brand": "Medix 5.5", "ulta_url": "https://www.ulta.com/brand/medix-55"},
{"rank": 599, "brand": "MEGAN THEE STALLION", "ulta_url": "https://www.ulta.com/brand/megan-thee-stallion"},
{"rank": 600, "brand": "Mela Vitamins", "ulta_url": "https://www.ulta.com/brand/mela-vitamins"},
{"rank": 601, "brand": "Mello", "ulta_url": "https://www.ulta.com/brand/mello"},
{"rank": 602, "brand": "Menokin", "ulta_url": "https://www.ulta.com/brand/menokin"},
{"rank": 603, "brand": "Merythod", "ulta_url": "https://www.ulta.com/brand/merythod"},
{"rank": 604, "brand": "Messi Fragrances", "ulta_url": "https://www.ulta.com/brand/messi-fragrances"},
{"rank": 605, "brand": "Metamorphosis", "ulta_url": "https://www.ulta.com/brand/metamorphosis"},
{"rank": 606, "brand": "method", "ulta_url": "https://www.ulta.com/brand/method"},
{"rank": 607, "brand": "Mia Secret", "ulta_url": "https://www.ulta.com/brand/mia-secret"},
{"rank": 608, "brand": "Miami Beach Bum", "ulta_url": "https://www.ulta.com/brand/miami-beach-bum"},
{"rank": 609, "brand": "Michael Malul", "ulta_url": "https://www.ulta.com/brand/michael-malul"},
{"rank": 610, "brand": "Michael Todd Beauty", "ulta_url": "https://www.ulta.com/brand/michael-todd-beauty"},
{"rank": 611, "brand": "Mielle", "ulta_url": "https://www.ulta.com/brand/mielle"},
{"rank": 612, "brand": "Miko", "ulta_url": "https://www.ulta.com/brand/miko"},
{"rank": 613, "brand": "Mila Moursi Skin Care", "ulta_url": "https://www.ulta.com/brand/mila-moursi-skin-care"},
{"rank": 614, "brand": "Milani", "ulta_url": "https://www.ulta.com/brand/milani"},
{"rank": 615, "brand": "Milk + Honey", "ulta_url": "https://www.ulta.com/brand/milk-honey"},
{"rank": 616, "brand": "MILK MAKEUP", "ulta_url": "https://www.ulta.com/brand/milk-makeup"},
{"rank": 617, "brand": "Mini Brands", "ulta_url": "https://www.ulta.com/brand/mini-brands"},
{"rank": 618, "brand": "Minimalist", "ulta_url": "https://www.ulta.com/brand/minimalist"},
{"rank": 619, "brand": "Mintier", "ulta_url": "https://www.ulta.com/brand/mintier"},
{"rank": 620, "brand": "MISSHA", "ulta_url": "https://www.ulta.com/brand/missha"},
{"rank": 621, "brand": "MISTR", "ulta_url": "https://www.ulta.com/brand/mistr"},
{"rank": 622, "brand": "Miu Miu", "ulta_url": "https://www.ulta.com/brand/miu-miu"},
{"rank": 623, "brand": "Mixed Chicks", "ulta_url": "https://www.ulta.com/brand/mixed-chicks"},
{"rank": 624, "brand": "Mixsoon", "ulta_url": "https://www.ulta.com/brand/mixsoon"},
{"rank": 625, "brand": "Molvany", "ulta_url": "https://www.ulta.com/brand/molvany"},
{"rank": 626, "brand": "MOMENTUM", "ulta_url": "https://www.ulta.com/brand/momentum"},
{"rank": 627, "brand": "Moncho Moreno", "ulta_url": "https://www.ulta.com/brand/moncho-moreno"},
{"rank": 628, "brand": "MONDAY Haircare", "ulta_url": "https://www.ulta.com/brand/monday-haircare"},
{"rank": 629, "brand": "Monika Blunder Beauty", "ulta_url": "https://www.ulta.com/brand/monika-blunder-beauty"},
{"rank": 630, "brand": "Monpure", "ulta_url": "https://www.ulta.com/brand/monpure"},
{"rank": 631, "brand": "Montblanc", "ulta_url": "https://www.ulta.com/brand/montblanc"},
{"rank": 632, "brand": "Moon", "ulta_url": "https://www.ulta.com/brand/moon"},
{"rank": 633, "brand": "Moon Juice", "ulta_url": "https://www.ulta.com/brand/moon-juice"},
{"rank": 634, "brand": "Moroccanoil", "ulta_url": "https://www.ulta.com/brand/moroccanoil"},
{"rank": 635, "brand": "Morphe", "ulta_url": "https://www.ulta.com/brand/morphe"},
{"rank": 636, "brand": "Morris Flamingo", "ulta_url": "https://www.ulta.com/brand/morris-flamingo"},
{"rank": 637, "brand": "Moschino", "ulta_url": "https://www.ulta.com/brand/moschino"},
{"rank": 638, "brand": "Mount Lai", "ulta_url": "https://www.ulta.com/brand/mount-lai"},
{"rank": 639, "brand": "MUGLER", "ulta_url": "https://www.ulta.com/brand/mugler"},
{"rank": 640, "brand": "Murad", "ulta_url": "https://www.ulta.com/brand/murad"},
{"rank": 641, "brand": "Murdock London", "ulta_url": "https://www.ulta.com/brand/murdock-london"},
{"rank": 642, "brand": "Mustela", "ulta_url": "https://www.ulta.com/brand/mustela"},
{"rank": 643, "brand": "My Neighbor's Tallow", "ulta_url": "https://www.ulta.com/brand/my-neighbors-tallow"},
{"rank": 644, "brand": "MySmile", "ulta_url": "https://www.ulta.com/brand/mysmile"},
{"rank": 645, "brand": "MYTAGALONGS", "ulta_url": "https://www.ulta.com/brand/mytagalongs"},
{"rank": 646, "brand": "MÜHLE", "ulta_url": "https://www.ulta.com/brand/muhle"},
{"rank": 647, "brand": "NABLA", "ulta_url": "https://www.ulta.com/brand/nabla"},
{"rank": 648, "brand": "Nads Natural", "ulta_url": "https://www.ulta.com/brand/nads-natural"},
{"rank": 649, "brand": "Nail Reformation", "ulta_url": "https://www.ulta.com/brand/nail-reformation"},
{"rank": 650, "brand": "Nail Tek", "ulta_url": "https://www.ulta.com/brand/nail-tek"},
{"rank": 651, "brand": "Nails Inc.", "ulta_url": "https://www.ulta.com/brand/nails-inc"},
{"rank": 652, "brand": "Nair", "ulta_url": "https://www.ulta.com/brand/nair"},
{"rank": 653, "brand": "Najeau", "ulta_url": "https://www.ulta.com/brand/najeau"},
{"rank": 654, "brand": "Naked Sundays", "ulta_url": "https://www.ulta.com/brand/naked-sundays"},
{"rank": 655, "brand": "NAKERY BEAUTY", "ulta_url": "https://www.ulta.com/brand/nakery-beauty"},
{"rank": 656, "brand": "narka", "ulta_url": "https://www.ulta.com/brand/narka"},
{"rank": 657, "brand": "NARS", "ulta_url": "https://www.ulta.com/brand/nars", "instagram": "https://www.instagram.com/narsissist", "twitter": "https://x.com/NARSissist"},
{"rank": 658, "brand": "NassifMD Skincare", "ulta_url": "https://www.ulta.com/brand/nassifmd-skincare"},
{"rank": 659, "brand": "NATASHA DENONA", "ulta_url": "https://www.ulta.com/brand/natasha-denona"},
{"rank": 660, "brand": "Nature's Bounty", "ulta_url": "https://www.ulta.com/brand/natures-bounty"},
{"rank": 661, "brand": "NatureLab. Tokyo", "ulta_url": "https://www.ulta.com/brand/naturelab-tokyo"},
{"rank": 662, "brand": "Naturium", "ulta_url": "https://www.ulta.com/brand/naturium"},
{"rank": 663, "brand": "Neal's Yard Remedies", "ulta_url": "https://www.ulta.com/brand/neals-yard-remedies"},
{"rank": 664, "brand": "Nemat", "ulta_url": "https://www.ulta.com/brand/nemat"},
{"rank": 665, "brand": "NEOGEN", "ulta_url": "https://www.ulta.com/brand/neogen"},
{"rank": 666, "brand": "NEOM Wellbeing", "ulta_url": "https://www.ulta.com/brand/neom-wellbeing"},
{"rank": 667, "brand": "NEST New York", "ulta_url": "https://www.ulta.com/brand/nest-new-york"},
{"rank": 668, "brand": "Neutrogena", "ulta_url": "https://www.ulta.com/brand/neutrogena"},
{"rank": 669, "brand": "Nexxus", "ulta_url": "https://www.ulta.com/brand/nexxus"},
{"rank": 670, "brand": "Nick Stenson Beauty", "ulta_url": "https://www.ulta.com/brand/nick-stenson-beauty"},
{"rank": 671, "brand": "Nimbi", "ulta_url": "https://www.ulta.com/brand/nimbi"},
{"rank": 672, "brand": "Nioxin", "ulta_url": "https://www.ulta.com/brand/nioxin"},
{"rank": 673, "brand": "Nishane", "ulta_url": "https://www.ulta.com/brand/nishane"},
{"rank": 674, "brand": "Nixit", "ulta_url": "https://www.ulta.com/brand/nixit"},
{"rank": 675, "brand": "No7", "ulta_url": "https://www.ulta.com/brand/no7"},
{"rank": 676, "brand": "Nodpod", "ulta_url": "https://www.ulta.com/brand/nodpod"},
{"rank": 677, "brand": "Nopalera", "ulta_url": "https://www.ulta.com/brand/nopalera"},
{"rank": 678, "brand": "Not Your Mother's", "ulta_url": "https://www.ulta.com/brand/not-your-mothers"},
{"rank": 679, "brand": "NOTO Botanics", "ulta_url": "https://www.ulta.com/brand/noto-botanics"},
{"rank": 680, "brand": "NOYZ", "ulta_url": "https://www.ulta.com/brand/noyz"},
{"rank": 681, "brand": "nu119", "ulta_url": "https://www.ulta.com/brand/nu119"},
{"rank": 682, "brand": "NUDESTIX", "ulta_url": "https://www.ulta.com/brand/nudestix"},
{"rank": 683, "brand": "NuFACE", "ulta_url": "https://www.ulta.com/brand/nuface"},
{"rank": 684, "brand": "NULASTIN", "ulta_url": "https://www.ulta.com/brand/nulastin"},
{"rank": 685, "brand": "numbuzin", "ulta_url": "https://www.ulta.com/brand/numbuzin"},
{"rank": 686, "brand": "NUTRAFOL", "ulta_url": "https://www.ulta.com/brand/nutrafol"},
{"rank": 687, "brand": "Nuxe", "ulta_url": "https://www.ulta.com/brand/nuxe"},
{"rank": 688, "brand": "NYX Professional Makeup", "ulta_url": "https://www.ulta.com/brand/nyx-professional-makeup"},
{"rank": 689, "brand": "Nēmah", "ulta_url": "https://www.ulta.com/brand/nemah"},
{"rank": 690, "brand": "Oak Bishop", "ulta_url": "https://www.ulta.com/brand/oak-bishop"},
{"rank": 691, "brand": "Oak Essentials", "ulta_url": "https://www.ulta.com/brand/oak-essentials"},
{"rank": 692, "brand": "Oars + Alps", "ulta_url": "https://www.ulta.com/brand/oars-alps"},
{"rank": 693, "brand": "OCOA", "ulta_url": "https://www.ulta.com/brand/ocoa"},
{"rank": 694, "brand": "OCTAVIA MORGAN LOS ANGELES", "ulta_url": "https://www.ulta.com/brand/octavia-morgan-los-angeles"},
{"rank": 695, "brand": "Odele", "ulta_url": "https://www.ulta.com/brand/odele"},
{"rank": 696, "brand": "Ofra Cosmetics", "ulta_url": "https://www.ulta.com/brand/ofra-cosmetics"},
{"rank": 697, "brand": "Ogee", "ulta_url": "https://www.ulta.com/brand/ogee"},
{"rank": 698, "brand": "OGX", "ulta_url": "https://www.ulta.com/brand/ogx"},
{"rank": 699, "brand": "Oh K!", "ulta_url": "https://www.ulta.com/brand/oh-k"},
{"rank": 700, "brand": "OLAPLEX", "ulta_url": "https://www.ulta.com/brand/olaplex"},
{"rank": 701, "brand": "OLAS Wellness", "ulta_url": "https://www.ulta.com/brand/olas-wellness"},
{"rank": 702, "brand": "Olay", "ulta_url": "https://www.ulta.com/brand/olay"},
{"rank": 703, "brand": "OLEHENRIKSEN", "ulta_url": "https://www.ulta.com/brand/olehenriksen"},
{"rank": 704, "brand": "OLFACTORY X", "ulta_url": "https://www.ulta.com/brand/olfactory-x"},
{"rank": 705, "brand": "Oliere Paris", "ulta_url": "https://www.ulta.com/brand/oliere-paris"},
{"rank": 706, "brand": "Olivarrier", "ulta_url": "https://www.ulta.com/brand/olivarrier"},
{"rank": 707, "brand": "Olive & June", "ulta_url": "https://www.ulta.com/brand/olive-june"},
{"rank": 708, "brand": "Olivia Garden", "ulta_url": "https://www.ulta.com/brand/olivia-garden"},
{"rank": 709, "brand": "OLLY", "ulta_url": "https://www.ulta.com/brand/olly"},
{"rank": 710, "brand": "OmySalon", "ulta_url": "https://www.ulta.com/brand/omysalon"},
{"rank": 711, "brand": "Onekind", "ulta_url": "https://www.ulta.com/brand/onekind"},
{"rank": 712, "brand": "ONYX Professional", "ulta_url": "https://www.ulta.com/brand/onyx-professional"},
{"rank": 713, "brand": "OPI", "ulta_url": "https://www.ulta.com/brand/opi"},
{"rank": 714, "brand": "Optimum Nutrition", "ulta_url": "https://www.ulta.com/brand/optimum-nutrition"},
{"rank": 715, "brand": "Orebella", "ulta_url": "https://www.ulta.com/brand/orebella"},
{"rank": 716, "brand": "Organyc", "ulta_url": "https://www.ulta.com/brand/organyc"},
{"rank": 717, "brand": "Orientica Perfumes", "ulta_url": "https://www.ulta.com/brand/orientica-perfumes"},
{"rank": 718, "brand": "Origins", "ulta_url": "https://www.ulta.com/brand/origins"},
{"rank": 719, "brand": "Orly", "ulta_url": "https://www.ulta.com/brand/orly"},
{"rank": 720, "brand": "Ortega Beauty", "ulta_url": "https://www.ulta.com/brand/ortega-beauty"},
{"rank": 721, "brand": "OSEA", "ulta_url": "https://www.ulta.com/brand/osea"},
{"rank": 722, "brand": "Oster Professional", "ulta_url": "https://www.ulta.com/brand/oster-professional"},
{"rank": 723, "brand": "OUAI", "ulta_url": "https://www.ulta.com/brand/ouai"},
{"rank": 724, "brand": "Ouidad", "ulta_url": "https://www.ulta.com/brand/ouidad"},
{"rank": 725, "brand": "Overtone", "ulta_url": "https://www.ulta.com/brand/overtone"},
{"rank": 726, "brand": "P.CALM", "ulta_url": "https://www.ulta.com/brand/pcalm"},
{"rank": 727, "brand": "Pacifica", "ulta_url": "https://www.ulta.com/brand/pacifica"},
{"rank": 728, "brand": "Pai-Shau", "ulta_url": "https://www.ulta.com/brand/pai-shau"},
{"rank": 729, "brand": "Palladio Beauty", "ulta_url": "https://www.ulta.com/brand/palladio-beauty"},
{"rank": 730, "brand": "Panasonic", "ulta_url": "https://www.ulta.com/brand/panasonic"},
{"rank": 731, "brand": "PanOxyl", "ulta_url": "https://www.ulta.com/brand/panoxyl"},
{"rank": 732, "brand": "Paris Hilton Fragrances", "ulta_url": "https://www.ulta.com/brand/paris-hilton-fragrances"},
{"rank": 733, "brand": "Particle for Men", "ulta_url": "https://www.ulta.com/brand/particle-men"},
{"rank": 734, "brand": "Party of You", "ulta_url": "https://www.ulta.com/brand/party-of-you"},
{"rank": 735, "brand": "PAT McGRATH LABS", "ulta_url": "https://www.ulta.com/brand/pat-mcgrath-labs"},
{"rank": 736, "brand": "Patchology", "ulta_url": "https://www.ulta.com/brand/patchology"},
{"rank": 737, "brand": "PATTERN", "ulta_url": "https://www.ulta.com/brand/pattern"},
{"rank": 738, "brand": "Paul Mitchell", "ulta_url": "https://www.ulta.com/brand/paul-mitchell"},
{"rank": 739, "brand": "PAUME", "ulta_url": "https://www.ulta.com/brand/paume"},
{"rank": 740, "brand": "Peace Out", "ulta_url": "https://www.ulta.com/brand/peace-out"},
{"rank": 741, "brand": "PEACH & LILY", "ulta_url": "https://www.ulta.com/brand/peach-lily"},
{"rank": 742, "brand": "Peach Slices", "ulta_url": "https://www.ulta.com/brand/peach-slices"},
{"rank": 743, "brand": "Perricone MD", "ulta_url": "https://www.ulta.com/brand/perricone-md"},
{"rank": 744, "brand": "Perry Ellis", "ulta_url": "https://www.ulta.com/brand/perry-ellis"},
{"rank": 745, "brand": "Persona", "ulta_url": "https://www.ulta.com/brand/persona"},
{"rank": 746, "brand": "Personal Day", "ulta_url": "https://www.ulta.com/brand/personal-day"},
{"rank": 747, "brand": "Pete & Pedro", "ulta_url": "https://www.ulta.com/brand/pete-pedro"},
{"rank": 748, "brand": "Peter Thomas Roth", "ulta_url": "https://www.ulta.com/brand/peter-thomas-roth"},
{"rank": 749, "brand": "Philosophy", "ulta_url": "https://www.ulta.com/brand/philosophy"},
{"rank": 750, "brand": "Physicians Formula", "ulta_url": "https://www.ulta.com/brand/physicians-formula"},
{"rank": 751, "brand": "Pink Pewter", "ulta_url": "https://www.ulta.com/brand/pink-pewter"},
{"rank": 752, "brand": "Pink Rabbit Cosmetics", "ulta_url": "https://www.ulta.com/brand/pink-rabbit-cosmetics"},
{"rank": 753, "brand": "PINKWONDER", "ulta_url": "https://www.ulta.com/brand/pinkwonder"},
{"rank": 754, "brand": "Pinrose", "ulta_url": "https://www.ulta.com/brand/pinrose"},
{"rank": 755, "brand": "Pirette", "ulta_url": "https://www.ulta.com/brand/pirette"},
{"rank": 756, "brand": "Pixi", "ulta_url": "https://www.ulta.com/brand/pixi"},
{"rank": 757, "brand": "PLA Beauty", "ulta_url": "https://www.ulta.com/brand/pla-beauty"},
{"rank": 758, "brand": "Plantkos", "ulta_url": "https://www.ulta.com/brand/plantkos"},
{"rank": 759, "brand": "Playground", "ulta_url": "https://www.ulta.com/brand/playground"},
{"rank": 760, "brand": "PLU", "ulta_url": "https://www.ulta.com/brand/plu"},
{"rank": 761, "brand": "plusOne", "ulta_url": "https://www.ulta.com/brand/plusone"},
{"rank": 762, "brand": "PMD", "ulta_url": "https://www.ulta.com/brand/pmd"},
{"rank": 763, "brand": "Polite Society", "ulta_url": "https://www.ulta.com/brand/polite-society"},
{"rank": 764, "brand": "Poom", "ulta_url": "https://www.ulta.com/brand/poom"},
{"rank": 765, "brand": "Poo~Pourri", "ulta_url": "https://www.ulta.com/brand/poopourri"},
{"rank": 766, "brand": "Poppy & Pout", "ulta_url": "https://www.ulta.com/brand/poppy-pout"},
{"rank": 767, "brand": "POUND CAKE", "ulta_url": "https://www.ulta.com/brand/pound-cake"},
{"rank": 768, "brand": "Prada", "ulta_url": "https://www.ulta.com/brand/prada"},
{"rank": 769, "brand": "PRAI Beauty", "ulta_url": "https://www.ulta.com/brand/prai-beauty"},
{"rank": 770, "brand": "Prime Prometics", "ulta_url": "https://www.ulta.com/brand/prime-prometics"},
{"rank": 771, "brand": "Proactiv", "ulta_url": "https://www.ulta.com/brand/proactiv"},
{"rank": 772, "brand": "Product-obsessed", "ulta_url": "https://www.ulta.com/brand/product-obsessed"},
{"rank": 773, "brand": "Productos LATINA", "ulta_url": "https://www.ulta.com/brand/productos-latina"},
{"rank": 774, "brand": "PROVENCE Beauty", "ulta_url": "https://www.ulta.com/brand/provence-beauty"},
{"rank": 775, "brand": "Pura", "ulta_url": "https://www.ulta.com/brand/pura"},
{"rank": 776, "brand": "Pure Daily Care", "ulta_url": "https://www.ulta.com/brand/pure-daily-care"},
{"rank": 777, "brand": "Pure Mama", "ulta_url": "https://www.ulta.com/brand/pure-mama"},
{"rank": 778, "brand": "Pure Silk", "ulta_url": "https://www.ulta.com/brand/pure-silk"},
{"rank": 779, "brand": "Pureology", "ulta_url": "https://www.ulta.com/brand/pureology"},
{"rank": 780, "brand": "Purito", "ulta_url": "https://www.ulta.com/brand/purito"},
{"rank": 781, "brand": "PURSONIC", "ulta_url": "https://www.ulta.com/brand/pursonic"},
{"rank": 782, "brand": "PÜR Minerals", "ulta_url": "https://www.ulta.com/brand/pur-minerals"},
{"rank": 783, "brand": "Qhemet Biologics", "ulta_url": "https://www.ulta.com/brand/qhemet-biologics"},
{"rank": 784, "brand": "Queen Cosmetics", "ulta_url": "https://www.ulta.com/brand/queen-cosmetics"},
{"rank": 785, "brand": "Quiet Mind", "ulta_url": "https://www.ulta.com/brand/quiet-mind"},
{"rank": 786, "brand": "r.e.m. beauty", "ulta_url": "https://www.ulta.com/brand/rem-beauty"},
{"rank": 787, "brand": "Rabanne", "ulta_url": "https://www.ulta.com/brand/rabanne"},
{"rank": 788, "brand": "Rael", "ulta_url": "https://www.ulta.com/brand/rael"},
{"rank": 789, "brand": "Ralph Lauren", "ulta_url": "https://www.ulta.com/brand/ralph-lauren"},
{"rank": 790, "brand": "Rare Beauty", "ulta_url": "https://www.ulta.com/brand/rare-beauty"},
{"rank": 791, "brand": "RAZOR MD", "ulta_url": "https://www.ulta.com/brand/razor-md"},
{"rank": 792, "brand": "Real Techniques", "ulta_url": "https://www.ulta.com/brand/real-techniques"},
{"rank": 793, "brand": "Rebundle", "ulta_url": "https://www.ulta.com/brand/rebundle"},
{"rank": 794, "brand": "Red Carpet Manicure", "ulta_url": "https://www.ulta.com/brand/red-carpet-manicure"},
{"rank": 795, "brand": "Redken", "ulta_url": "https://www.ulta.com/brand/redken"},
{"rank": 796, "brand": "Refilled", "ulta_url": "https://www.ulta.com/brand/refilled"},
{"rank": 797, "brand": "RescueMD", "ulta_url": "https://www.ulta.com/brand/rescuemd"},
{"rank": 798, "brand": "Returnu", "ulta_url": "https://www.ulta.com/brand/returnu"},
{"rank": 799, "brand": "REUZEL", "ulta_url": "https://www.ulta.com/brand/reuzel"},
{"rank": 800, "brand": "RevAir", "ulta_url": "https://www.ulta.com/brand/revair"},
{"rank": 801, "brand": "Revive Collagen", "ulta_url": "https://www.ulta.com/brand/revive-collagen"},
{"rank": 802, "brand": "Revlon", "ulta_url": "https://www.ulta.com/brand/revlon"},
{"rank": 803, "brand": "Revolution Beauty", "ulta_url": "https://www.ulta.com/brand/revolution-beauty"},
{"rank": 804, "brand": "Richualist", "ulta_url": "https://www.ulta.com/brand/richualist"},
{"rank": 805, "brand": "Ritual", "ulta_url": "https://www.ulta.com/brand/ritual"},
{"rank": 806, "brand": "Rizos Curls", "ulta_url": "https://www.ulta.com/brand/rizos-curls"},
{"rank": 807, "brand": "RMS Beauty", "ulta_url": "https://www.ulta.com/brand/rms-beauty"},
{"rank": 808, "brand": "RoC", "ulta_url": "https://www.ulta.com/brand/roc"},
{"rank": 809, "brand": "RODAN + FIELDS", "ulta_url": "https://www.ulta.com/brand/rodan-fields"},
{"rank": 810, "brand": "Rookie Wellness", "ulta_url": "https://www.ulta.com/brand/rookie-wellness"},
{"rank": 811, "brand": "Root Candles", "ulta_url": "https://www.ulta.com/brand/root-candles"},
{"rank": 812, "brand": "ROOTON", "ulta_url": "https://www.ulta.com/brand/rooton"},
{"rank": 813, "brand": "Rosebud Perfume Co.", "ulta_url": "https://www.ulta.com/brand/rosebud-perfume-co"},
{"rank": 814, "brand": "Rosebud Woman", "ulta_url": "https://www.ulta.com/brand/rosebud-woman"},
{"rank": 815, "brand": "ROSEN", "ulta_url": "https://www.ulta.com/brand/rosen"},
{"rank": 816, "brand": "Rosendo Mateu", "ulta_url": "https://www.ulta.com/brand/rosendo-mateu"},
{"rank": 817, "brand": "Rosy & Earnest", "ulta_url": "https://www.ulta.com/brand/rosy-earnest"},
{"rank": 818, "brand": "ROUND LAB", "ulta_url": "https://www.ulta.com/brand/round-lab"},
{"rank": 819, "brand": "Rovectin", "ulta_url": "https://www.ulta.com/brand/rovectin"},
{"rank": 820, "brand": "Rude", "ulta_url": "https://www.ulta.com/brand/rude"},
{"rank": 821, "brand": "Saalt", "ulta_url": "https://www.ulta.com/brand/saalt"},
{"rank": 822, "brand": "Sabrina Carpenter", "ulta_url": "https://www.ulta.com/brand/sabrina-carpenter"},
{"rank": 823, "brand": "SACHEU", "ulta_url": "https://www.ulta.com/brand/sacheu"},
{"rank": 824, "brand": "Saint Jane", "ulta_url": "https://www.ulta.com/brand/saint-jane"},
{"rank": 825, "brand": "Saje Natural Wellness", "ulta_url": "https://www.ulta.com/brand/saje-natural-wellness"},
{"rank": 826, "brand": "SAKARA", "ulta_url": "https://www.ulta.com/brand/sakara"},
{"rank": 827, "brand": "Sally Hansen", "ulta_url": "https://www.ulta.com/brand/sally-hansen"},
{"rank": 828, "brand": "Salon Step", "ulta_url": "https://www.ulta.com/brand/salon-step"},
{"rank": 829, "brand": "Saltair", "ulta_url": "https://www.ulta.com/brand/saltair"},
{"rank": 830, "brand": "Sam Edelman", "ulta_url": "https://www.ulta.com/brand/sam-edelman"},
{"rank": 831, "brand": "Sand and Sky", "ulta_url": "https://www.ulta.com/brand/sand-sky"},
{"rank": 832, "brand": "Sans Savon", "ulta_url": "https://www.ulta.com/brand/sans-savon"},
{"rank": 833, "brand": "Santu", "ulta_url": "https://www.ulta.com/brand/santu"},
{"rank": 834, "brand": "Sara Happ", "ulta_url": "https://www.ulta.com/brand/sara-happ"},
{"rank": 835, "brand": "Saturday Skin", "ulta_url": "https://www.ulta.com/brand/saturday-skin"},
{"rank": 836, "brand": "Sauce Beauty", "ulta_url": "https://www.ulta.com/brand/sauce-beauty"},
{"rank": 837, "brand": "Scarlet by RedDrop", "ulta_url": "https://www.ulta.com/brand/scarlet-by-reddrop"},
{"rank": 838, "brand": "Schick", "ulta_url": "https://www.ulta.com/brand/schick"},
{"rank": 839, "brand": "Scruples", "ulta_url": "https://www.ulta.com/brand/scruples"},
{"rank": 840, "brand": "Sebastian", "ulta_url": "https://www.ulta.com/brand/sebastian"},
{"rank": 841, "brand": "Seche", "ulta_url": "https://www.ulta.com/brand/seche"},
{"rank": 842, "brand": "SEEN", "ulta_url": "https://www.ulta.com/brand/seen"},
{"rank": 843, "brand": "SEKKISEI", "ulta_url": "https://www.ulta.com/brand/sekkisei"},
{"rank": 844, "brand": "SelpH", "ulta_url": "https://www.ulta.com/brand/selph"},
{"rank": 845, "brand": "Seoul Ceuticals", "ulta_url": "https://www.ulta.com/brand/seoul-ceuticals"},
{"rank": 846, "brand": "SeroVital", "ulta_url": "https://www.ulta.com/brand/serovital"},
{"rank": 847, "brand": "Sexy Hair", "ulta_url": "https://www.ulta.com/brand/sexy-hair"},
{"rank": 848, "brand": "SHAMPOOHOTEL", "ulta_url": "https://www.ulta.com/brand/shampoohotel"},
{"rank": 849, "brand": "Shaquille O'Neal Fragrance", "ulta_url": "https://www.ulta.com/brand/shaquille-oneal-fragrance"},
{"rank": 850, "brand": "Shark Beauty", "ulta_url": "https://www.ulta.com/brand/shark-beauty"},
{"rank": 851, "brand": "Sharper Image", "ulta_url": "https://www.ulta.com/brand/sharper-image"},
{"rank": 852, "brand": "SHAZ & KIKS", "ulta_url": "https://www.ulta.com/brand/shaz-kiks"},
{"rank": 853, "brand": "SheaMoisture", "ulta_url": "https://www.ulta.com/brand/sheamoisture"},
{"rank": 854, "brand": "Shiseido", "ulta_url": "https://www.ulta.com/brand/shiseido"},
{"rank": 855, "brand": "SickScience Labs", "ulta_url": "https://www.ulta.com/brand/sickscience-labs"},
{"rank": 856, "brand": "Sigma Beauty", "ulta_url": "https://www.ulta.com/brand/sigma-beauty"},
{"rank": 857, "brand": "Sitting Pretty", "ulta_url": "https://www.ulta.com/brand/sitting-pretty"},
{"rank": 858, "brand": "Skin Gym", "ulta_url": "https://www.ulta.com/brand/skin-gym"},
{"rank": 859, "brand": "SKIN1004", "ulta_url": "https://www.ulta.com/brand/skin1004"},
{"rank": 860, "brand": "skinChemists", "ulta_url": "https://www.ulta.com/brand/skinchemists"},
{"rank": 861, "brand": "Skull Shaver", "ulta_url": "https://www.ulta.com/brand/skull-shaver"},
{"rank": 862, "brand": "Skyn Iceland", "ulta_url": "https://www.ulta.com/brand/skyn-iceland"},
{"rank": 863, "brand": "Sleek’e", "ulta_url": "https://www.ulta.com/brand/sleeke"},
{"rank": 864, "brand": "Sleepy Tie", "ulta_url": "https://www.ulta.com/brand/sleepy-tie"},
{"rank": 865, "brand": "Slip", "ulta_url": "https://www.ulta.com/brand/slip"},
{"rank": 866, "brand": "Smashbox", "ulta_url": "https://www.ulta.com/brand/smashbox"},
{"rank": 867, "brand": "Smile Makers", "ulta_url": "https://www.ulta.com/brand/smile-makers"},
{"rank": 868, "brand": "Snif", "ulta_url": "https://www.ulta.com/brand/snif"},
{"rank": 869, "brand": "Soapbox", "ulta_url": "https://www.ulta.com/brand/soapbox"},
{"rank": 870, "brand": "SoCozy", "ulta_url": "https://www.ulta.com/brand/socozy"},
{"rank": 871, "brand": "Sol de Janeiro", "ulta_url": "https://www.ulta.com/brand/sol-de-janeiro", "instagram": "https://www.instagram.com/soldejaneiro", "twitter": "https://x.com/soldejaneiro"},
{"rank": 872, "brand": "Solawave", "ulta_url": "https://www.ulta.com/brand/solawave"},
{"rank": 873, "brand": "SOME BY MI", "ulta_url": "https://www.ulta.com/brand/some-by-mi"},
{"rank": 874, "brand": "SOSHE Beauty", "ulta_url": "https://www.ulta.com/brand/soshe-beauty"},
{"rank": 875, "brand": "Spa Sciences", "ulta_url": "https://www.ulta.com/brand/spa-sciences"},
{"rank": 876, "brand": "Sparkle Wellness", "ulta_url": "https://www.ulta.com/brand/sparkle-wellness"},
{"rank": 877, "brand": "SPATCH", "ulta_url": "https://www.ulta.com/brand/spatch"},
{"rank": 878, "brand": "Spectrum", "ulta_url": "https://www.ulta.com/brand/spectrum"},
{"rank": 879, "brand": "Spongeables", "ulta_url": "https://www.ulta.com/brand/spongeables"},
{"rank": 880, "brand": "SPONGELLE", "ulta_url": "https://www.ulta.com/brand/spongelle"},
{"rank": 881, "brand": "Squishmallows", "ulta_url": "https://www.ulta.com/brand/squishmallows"},
{"rank": 882, "brand": "Squishmallows Fragrances", "ulta_url": "https://www.ulta.com/brand/squishmallows-fragrances"},
{"rank": 883, "brand": "St. Tropez", "ulta_url": "https://www.ulta.com/brand/st-tropez"},
{"rank": 884, "brand": "STARFACE", "ulta_url": "https://www.ulta.com/brand/starface"},
{"rank": 885, "brand": "Stephan", "ulta_url": "https://www.ulta.com/brand/stephan"},
{"rank": 886, "brand": "Stila", "ulta_url": "https://www.ulta.com/brand/stila"},
{"rank": 887, "brand": "Stimmie", "ulta_url": "https://www.ulta.com/brand/stimmie"},
{"rank": 888, "brand": "STRIPES BEAUTY by Naomi Watts", "ulta_url": "https://www.ulta.com/brand/stripes-beauty-by-naomi-watts"},
{"rank": 889, "brand": "StriVectin", "ulta_url": "https://www.ulta.com/brand/strivectin"},
{"rank": 890, "brand": "SUBTL. Beauty", "ulta_url": "https://www.ulta.com/brand/subtl-beauty"},
{"rank": 891, "brand": "Sugarbear", "ulta_url": "https://www.ulta.com/brand/sugarbear"},
{"rank": 892, "brand": "sugardoh", "ulta_url": "https://www.ulta.com/brand/sugardoh"},
{"rank": 893, "brand": "Sun Bum", "ulta_url": "https://www.ulta.com/brand/sun-bum"},
{"rank": 894, "brand": "SUNDAY RILEY", "ulta_url": "https://www.ulta.com/brand/sunday-riley"},
{"rank": 895, "brand": "Sunday || Sunday", "ulta_url": "https://www.ulta.com/brand/sunday-sunday"},
{"rank": 896, "brand": "SUNGBOON EDITOR", "ulta_url": "https://www.ulta.com/brand/sungboon-editor"},
{"rank": 897, "brand": "Sunnee BAEskin", "ulta_url": "https://www.ulta.com/brand/sunnee-baeskin"},
{"rank": 898, "brand": "Superegg", "ulta_url": "https://www.ulta.com/brand/superegg"},
{"rank": 899, "brand": "Supergoop!", "ulta_url": "https://www.ulta.com/brand/supergoop"},
{"rank": 900, "brand": "Supermush", "ulta_url": "https://www.ulta.com/brand/supermush"},
{"rank": 901, "brand": "Supersmile", "ulta_url": "https://www.ulta.com/brand/supersmile"},
{"rank": 902, "brand": "Supersuite", "ulta_url": "https://www.ulta.com/brand/supersuite"},
{"rank": 903, "brand": "Supply Co.", "ulta_url": "https://www.ulta.com/brand/supply-co"},
{"rank": 904, "brand": "Surface Deep", "ulta_url": "https://www.ulta.com/brand/surface-deep"},
{"rank": 905, "brand": "Surratt Beauty", "ulta_url": "https://www.ulta.com/brand/surratt-beauty"},
{"rank": 906, "brand": "Sweet & Shimmer", "ulta_url": "https://www.ulta.com/brand/sweet-shimmer"},
{"rank": 907, "brand": "Sweet July Skin", "ulta_url": "https://www.ulta.com/brand/sweet-july-skin"},
{"rank": 908, "brand": "Swishables", "ulta_url": "https://www.ulta.com/brand/swishables"},
{"rank": 909, "brand": "Swiss Arabian", "ulta_url": "https://www.ulta.com/brand/swiss-arabian"},
{"rank": 910, "brand": "T3", "ulta_url": "https://www.ulta.com/brand/t3"},
{"rank": 911, "brand": "TABBEAU", "ulta_url": "https://www.ulta.com/brand/tabbeau"},
{"rank": 912, "brand": "TAD", "ulta_url": "https://www.ulta.com/brand/tad"},
{"rank": 913, "brand": "Tallow Me Pretty", "ulta_url": "https://www.ulta.com/brand/tallow-me-pretty"},
{"rank": 914, "brand": "Talova Labs", "ulta_url": "https://www.ulta.com/brand/talova-labs"},
{"rank": 915, "brand": "TAN-LUXE", "ulta_url": "https://www.ulta.com/brand/tan-luxe"},
{"rank": 916, "brand": "Tangle Teezer", "ulta_url": "https://www.ulta.com/brand/tangle-teezer"},
{"rank": 917, "brand": "Tanologist", "ulta_url": "https://www.ulta.com/brand/tanologist"},
{"rank": 918, "brand": "TanOrganic", "ulta_url": "https://www.ulta.com/brand/tanorganic"},
{"rank": 919, "brand": "Tartan + Twine", "ulta_url": "https://www.ulta.com/brand/tartan-twine"},
{"rank": 920, "brand": "Tarte", "ulta_url": "https://www.ulta.com/brand/tarte"},
{"rank": 921, "brand": "TATCHA", "ulta_url": "https://www.ulta.com/brand/tatcha"},
{"rank": 922, "brand": "Taylor of Old Bond Street", "ulta_url": "https://www.ulta.com/brand/taylor-of-old-bond-street"},
{"rank": 923, "brand": "TEABLESS", "ulta_url": "https://www.ulta.com/brand/teabless"},
{"rank": 924, "brand": "Tech Activated Beauty", "ulta_url": "https://www.ulta.com/brand/tech-activated-beauty"},
{"rank": 925, "brand": "TELETIES", "ulta_url": "https://www.ulta.com/brand/teleties"},
{"rank": 926, "brand": "Teluris", "ulta_url": "https://www.ulta.com/brand/teluris"},
{"rank": 927, "brand": "Tenoverten", "ulta_url": "https://www.ulta.com/brand/tenoverten"},
{"rank": 928, "brand": "TFIT", "ulta_url": "https://www.ulta.com/brand/tfit"},
{"rank": 929, "brand": "tgin", "ulta_url": "https://www.ulta.com/brand/tgin"},
{"rank": 930, "brand": "Thank You Farmer", "ulta_url": "https://www.ulta.com/brand/thank-you-farmer"},
{"rank": 931, "brand": "Thayers", "ulta_url": "https://www.ulta.com/brand/thayers"},
{"rank": 932, "brand": "The Body Firm", "ulta_url": "https://www.ulta.com/brand/body-firm"},
{"rank": 933, "brand": "The Crème Shop", "ulta_url": "https://www.ulta.com/brand/creme-shop"},
{"rank": 934, "brand": "The Face Shop", "ulta_url": "https://www.ulta.com/brand/face-shop"},
{"rank": 935, "brand": "The Frontal Queen", "ulta_url": "https://www.ulta.com/brand/frontal-queen"},
{"rank": 936, "brand": "The Good Patch", "ulta_url": "https://www.ulta.com/brand/good-patch"},
{"rank": 937, "brand": "The Hair Edit", "ulta_url": "https://www.ulta.com/brand/hair-edit"},
{"rank": 938, "brand": "The Honey Pot Company", "ulta_url": "https://www.ulta.com/brand/honey-pot-company"},
{"rank": 939, "brand": "The INKEY List", "ulta_url": "https://www.ulta.com/brand/inkey-list"},
{"rank": 940, "brand": "The Lip Bar", "ulta_url": "https://www.ulta.com/brand/lip-bar"},
{"rank": 941, "brand": "The Nue Co.", "ulta_url": "https://www.ulta.com/brand/nue-co"},
{"rank": 942, "brand": "The Ordinary", "ulta_url": "https://www.ulta.com/brand/ordinary"},
{"rank": 943, "brand": "The Organic Skin Co.", "ulta_url": "https://www.ulta.com/brand/organic-skin-co"},
{"rank": 944, "brand": "THE ROUTE", "ulta_url": "https://www.ulta.com/brand/route"},
{"rank": 945, "brand": "The Vintage Cosmetic Company", "ulta_url": "https://www.ulta.com/brand/vintage-cosmetic-company"},
{"rank": 946, "brand": "Therabody", "ulta_url": "https://www.ulta.com/brand/therabody"},
{"rank": 947, "brand": "TheraBreath", "ulta_url": "https://www.ulta.com/brand/therabreath"},
{"rank": 948, "brand": "Tiege Hanley", "ulta_url": "https://www.ulta.com/brand/tiege-hanley"},
{"rank": 949, "brand": "Tiffany & Co.", "ulta_url": "https://www.ulta.com/brand/tiffany-co"},
{"rank": 950, "brand": "Timebeam", "ulta_url": "https://www.ulta.com/brand/timebeam"},
{"rank": 951, "brand": "Tippy Type", "ulta_url": "https://www.ulta.com/brand/tippy-type"},
{"rank": 952, "brand": "Tiri Pro", "ulta_url": "https://www.ulta.com/brand/tiri-pro"},
{"rank": 953, "brand": "TIRTIR", "ulta_url": "https://www.ulta.com/brand/tirtir"},
{"rank": 954, "brand": "TOCCA", "ulta_url": "https://www.ulta.com/brand/tocca"},
{"rank": 955, "brand": "TOM FORD", "ulta_url": "https://www.ulta.com/brand/tom-ford", "instagram": "https://www.instagram.com/tomfordbeauty", "twitter": "https://x.com/TOMFORD"},
{"rank": 956, "brand": "TONYMOLY", "ulta_url": "https://www.ulta.com/brand/tonymoly"},
{"rank": 957, "brand": "Too Faced", "ulta_url": "https://www.ulta.com/brand/too-faced", "instagram": "https://www.instagram.com/toofaced", "twitter": "https://x.com/toofaced"},
{"rank": 958, "brand": "Toppik", "ulta_url": "https://www.ulta.com/brand/toppik"},
{"rank": 959, "brand": "Tory Burch", "ulta_url": "https://www.ulta.com/brand/tory-burch"},
{"rank": 960, "brand": "Touchland", "ulta_url": "https://www.ulta.com/brand/touchland"},
{"rank": 961, "brand": "TPOB", "ulta_url": "https://www.ulta.com/brand/tpob"},
{"rank": 962, "brand": "Tranquil Blisser", "ulta_url": "https://www.ulta.com/brand/tranquil-blisser"},
{"rank": 963, "brand": "Tree Hut", "ulta_url": "https://www.ulta.com/brand/tree-hut"},
{"rank": 964, "brand": "Tricoci", "ulta_url": "https://www.ulta.com/brand/tricoci"},
{"rank": 965, "brand": "Trilastin", "ulta_url": "https://www.ulta.com/brand/trilastin"},
{"rank": 966, "brand": "Triumph & Disaster", "ulta_url": "https://www.ulta.com/brand/triumph-disaster"},
{"rank": 967, "brand": "True + Pure Texture", "ulta_url": "https://www.ulta.com/brand/true-pure-texture"},
{"rank": 968, "brand": "Truezyme", "ulta_url": "https://www.ulta.com/brand/truezyme"},
{"rank": 969, "brand": "Truly", "ulta_url": "https://www.ulta.com/brand/truly"},
{"rank": 970, "brand": "TruSkin", "ulta_url": "https://www.ulta.com/brand/truskin"},
{"rank": 971, "brand": "TULA", "ulta_url": "https://www.ulta.com/brand/tula"},
{"rank": 972, "brand": "Tweezerman", "ulta_url": "https://www.ulta.com/brand/tweezerman"},
{"rank": 973, "brand": "TYMO Beauty", "ulta_url": "https://www.ulta.com/brand/tymo-beauty"},
{"rank": 974, "brand": "Ulike", "ulta_url": "https://www.ulta.com/brand/ulike"},
{"rank": 975, "brand": "ULTA Beauty Collection", "ulta_url": "https://www.ulta.com/brand/ulta-beauty-collection"},
{"rank": 976, "brand": "Unbound", "ulta_url": "https://www.ulta.com/brand/unbound"},
{"rank": 977, "brand": "UNbrush", "ulta_url": "https://www.ulta.com/brand/unbrush"},
{"rank": 978, "brand": "Undefined Beauty", "ulta_url": "https://www.ulta.com/brand/undefined-beauty"},
{"rank": 979, "brand": "Uni", "ulta_url": "https://www.ulta.com/brand/uni"},
{"rank": 980, "brand": "UNITE Hair", "ulta_url": "https://www.ulta.com/brand/unite-hair"},
{"rank": 981, "brand": "Unleashia", "ulta_url": "https://www.ulta.com/brand/unleashia"},
{"rank": 982, "brand": "Urang", "ulta_url": "https://www.ulta.com/brand/urang"},
{"rank": 983, "brand": "Urban Decay Cosmetics", "ulta_url": "https://www.ulta.com/brand/urban-decay-cosmetics"},
{"rank": 984, "brand": "Urban Hydration", "ulta_url": "https://www.ulta.com/brand/urban-hydration"},
{"rank": 985, "brand": "Urban Skin Rx", "ulta_url": "https://www.ulta.com/brand/urban-skin-rx"},
{"rank": 986, "brand": "Urban Veda", "ulta_url": "https://www.ulta.com/brand/urban-veda"},
{"rank": 987, "brand": "Ursa Major", "ulta_url": "https://www.ulta.com/brand/ursa-major"},
{"rank": 988, "brand": "V by Velour", "ulta_url": "https://www.ulta.com/brand/v-by-velour"},
{"rank": 989, "brand": "Vacation", "ulta_url": "https://www.ulta.com/brand/vacation"},
{"rank": 990, "brand": "Vahy", "ulta_url": "https://www.ulta.com/brand/vahy"},
{"rank": 991, "brand": "Valentino", "ulta_url": "https://www.ulta.com/brand/valentino"},
{"rank": 992, "brand": "VANICREAM", "ulta_url": "https://www.ulta.com/brand/vanicream"},
{"rank": 993, "brand": "Vanity Planet", "ulta_url": "https://www.ulta.com/brand/vanity-planet"},
{"rank": 994, "brand": "Variety", "ulta_url": "https://www.ulta.com/brand/variety"},
{"rank": 995, "brand": "Vaseline", "ulta_url": "https://www.ulta.com/brand/vaseline"},
{"rank": 996, "brand": "Veea Face by Dr. Suzan Obagi", "ulta_url": "https://www.ulta.com/brand/veea-face-by-dr-suzan-obagi"},
{"rank": 997, "brand": "Veggimins", "ulta_url": "https://www.ulta.com/brand/veggimins"},
{"rank": 998, "brand": "Velour Lashes", "ulta_url": "https://www.ulta.com/brand/velour-lashes"},
{"rank": 999, "brand": "Vera Wang", "ulta_url": "https://www.ulta.com/brand/vera-wang"},
{"rank": 1000, "brand": "Verb", "ulta_url": "https://www.ulta.com/brand/verb"},
{"rank": 1001, "brand": "Veriphy Skincare", "ulta_url": "https://www.ulta.com/brand/veriphy-skincare"},
{"rank": 1002, "brand": "Versace", "ulta_url": "https://www.ulta.com/brand/versace"},
{"rank": 1003, "brand": "Versed", "ulta_url": "https://www.ulta.com/brand/versed"},
{"rank": 1004, "brand": "Vichy", "ulta_url": "https://www.ulta.com/brand/vichy"},
{"rank": 1005, "brand": "VIDIVICI", "ulta_url": "https://www.ulta.com/brand/vidivici"},
{"rank": 1006, "brand": "Viktor&Rolf", "ulta_url": "https://www.ulta.com/brand/viktor-rolf"},
{"rank": 1007, "brand": "Vintage Noon", "ulta_url": "https://www.ulta.com/brand/vintage-noon"},
{"rank": 1008, "brand": "VIO2", "ulta_url": "https://www.ulta.com/brand/vio2"},
{"rank": 1009, "brand": "Virtue", "ulta_url": "https://www.ulta.com/brand/virtue"},
{"rank": 1010, "brand": "Vital Proteins", "ulta_url": "https://www.ulta.com/brand/vital-proteins"},
{"rank": 1011, "brand": "Vitruvi", "ulta_url": "https://www.ulta.com/brand/vitruvi"},
{"rank": 1012, "brand": "VIVAIODAYS", "ulta_url": "https://www.ulta.com/brand/vivaiodays"},
{"rank": 1013, "brand": "Viviscal", "ulta_url": "https://www.ulta.com/brand/viviscal"},
{"rank": 1014, "brand": "VOESH", "ulta_url": "https://www.ulta.com/brand/voesh"},
{"rank": 1015, "brand": "VOLITION", "ulta_url": "https://www.ulta.com/brand/volition"},
{"rank": 1016, "brand": "Voloom", "ulta_url": "https://www.ulta.com/brand/voloom"},
{"rank": 1017, "brand": "VT Cosmetics", "ulta_url": "https://www.ulta.com/brand/vt-cosmetics"},
{"rank": 1018, "brand": "VUSH", "ulta_url": "https://www.ulta.com/brand/vush"},
{"rank": 1019, "brand": "Wakse", "ulta_url": "https://www.ulta.com/brand/wakse"},
{"rank": 1020, "brand": "Wangi Wellness", "ulta_url": "https://www.ulta.com/brand/wangi-wellness"},
{"rank": 1021, "brand": "Water.io", "ulta_url": "https://www.ulta.com/brand/waterio"},
{"rank": 1022, "brand": "Wavytalk", "ulta_url": "https://www.ulta.com/brand/wavytalk"},
{"rank": 1023, "brand": "WeGym", "ulta_url": "https://www.ulta.com/brand/wegym"},
{"rank": 1024, "brand": "Well People", "ulta_url": "https://www.ulta.com/brand/well-people"},
{"rank": 1025, "brand": "Wella", "ulta_url": "https://www.ulta.com/brand/wella"},
{"rank": 1026, "brand": "Wet Brush", "ulta_url": "https://www.ulta.com/brand/wet-brush"},
{"rank": 1027, "brand": "Wet n Wild", "ulta_url": "https://www.ulta.com/brand/wet-n-wild"},
{"rank": 1028, "brand": "White Lotus Beauty", "ulta_url": "https://www.ulta.com/brand/white-lotus-beauty"},
{"rank": 1029, "brand": "Who Is Elijah", "ulta_url": "https://www.ulta.com/brand/who-elijah"},
{"rank": 1030, "brand": "Wigo", "ulta_url": "https://www.ulta.com/brand/wigo"},
{"rank": 1031, "brand": "Wildfleur", "ulta_url": "https://www.ulta.com/brand/wildfleur"},
{"rank": 1032, "brand": "Winky Lux", "ulta_url": "https://www.ulta.com/brand/winky-lux"},
{"rank": 1033, "brand": "Womaness", "ulta_url": "https://www.ulta.com/brand/womaness"},
{"rank": 1034, "brand": "Wrinkles Schminkles", "ulta_url": "https://www.ulta.com/brand/wrinkles-schminkles"},
{"rank": 1035, "brand": "WTHN", "ulta_url": "https://www.ulta.com/brand/wthn"},
{"rank": 1036, "brand": "Wunderbrow", "ulta_url": "https://www.ulta.com/brand/wunderbrow"},
{"rank": 1037, "brand": "WYLYS", "ulta_url": "https://www.ulta.com/brand/wylys"},
{"rank": 1038, "brand": "XMONDO", "ulta_url": "https://www.ulta.com/brand/xmondo"},
{"rank": 1039, "brand": "Yadah", "ulta_url": "https://www.ulta.com/brand/yadah"},
{"rank": 1040, "brand": "Yoga Design Lab", "ulta_url": "https://www.ulta.com/brand/yoga-design-lab"},
{"rank": 1041, "brand": "Youngblood", "ulta_url": "https://www.ulta.com/brand/youngblood"},
{"rank": 1042, "brand": "Your Reformer", "ulta_url": "https://www.ulta.com/brand/your-reformer"},
{"rank": 1043, "brand": "Youthforia", "ulta_url": "https://www.ulta.com/brand/youthforia"},
{"rank": 1044, "brand": "Yves Saint Laurent", "ulta_url": "https://www.ulta.com/brand/yves-saint-laurent", "instagram": "https://www.instagram.com/yslbeauty", "twitter": "https://x.com/YSLBeauty"},
{"rank": 1045, "brand": "Zadro", "ulta_url": "https://www.ulta.com/brand/zadro"},
{"rank": 1046, "brand": "Zoya", "ulta_url": "https://www.ulta.com/brand/zoya"},
]
