"""Major video game franchises. Source: Wikipedia (List of video game franchises)."""
VGFRAN_EDITION = "Major franchises"
VGFRAN_SOURCE_URL = "https://en.wikipedia.org/wiki/List_of_video_game_franchises"
W="https://en.wikipedia.org/wiki/"
def _t(rank,name,pub,wiki):
    return {"rank":rank,"franchise":name,"publisher":pub,"website":"","wikipedia":W+wiki}
VG_FRANCHISES=[
 _t(1,"Mario","Nintendo","Mario_(franchise)"),
 _t(2,"Pokémon","Nintendo / The Pokémon Company","Pokémon"),
 _t(3,"Call of Duty","Activision","Call_of_Duty"),
 _t(4,"Grand Theft Auto","Rockstar Games","Grand_Theft_Auto"),
 _t(5,"EA Sports FC (FIFA)","Electronic Arts","EA_Sports_FC"),
 _t(6,"The Legend of Zelda","Nintendo","The_Legend_of_Zelda"),
 _t(7,"Minecraft","Mojang / Xbox Game Studios","Minecraft"),
 _t(8,"Tetris","The Tetris Company","Tetris"),
 _t(9,"Final Fantasy","Square Enix","Final_Fantasy"),
 _t(10,"Assassin's Creed","Ubisoft","Assassin's_Creed"),
 _t(11,"The Sims","Electronic Arts","The_Sims"),
 _t(12,"Need for Speed","Electronic Arts","Need_for_Speed"),
 _t(13,"Battlefield","Electronic Arts","Battlefield_(video_game_series)"),
 _t(14,"Madden NFL","EA Sports","Madden_NFL"),
 _t(15,"Sonic the Hedgehog","Sega","Sonic_the_Hedgehog"),
 _t(16,"Tomb Raider","Crystal Dynamics","Tomb_Raider"),
 _t(17,"Resident Evil","Capcom","Resident_Evil"),
 _t(18,"Street Fighter","Capcom","Street_Fighter"),
 _t(19,"Mortal Kombat","Warner Bros. Games","Mortal_Kombat"),
 _t(20,"Halo","Xbox Game Studios","Halo_(franchise)"),
 _t(21,"Gran Turismo","Sony Interactive Entertainment","Gran_Turismo"),
 _t(22,"Metal Gear","Konami","Metal_Gear"),
 _t(23,"The Elder Scrolls","Bethesda Softworks","The_Elder_Scrolls"),
 _t(24,"Fallout","Bethesda Softworks","Fallout_(franchise)"),
 _t(25,"Far Cry","Ubisoft","Far_Cry"),
 _t(26,"Counter-Strike","Valve","Counter-Strike"),
 _t(27,"Diablo","Blizzard Entertainment","Diablo_(series)"),
 _t(28,"Warcraft","Blizzard Entertainment","Warcraft"),
 _t(29,"StarCraft","Blizzard Entertainment","StarCraft"),
 _t(30,"Doom","id Software / Bethesda","Doom_(franchise)"),
 _t(31,"Mega Man","Capcom","Mega_Man"),
 _t(32,"Dragon Quest","Square Enix","Dragon_Quest"),
 _t(33,"Kingdom Hearts","Square Enix","Kingdom_Hearts"),
 _t(34,"Crash Bandicoot","Activision","Crash_Bandicoot"),
 _t(35,"God of War","Sony Interactive Entertainment","God_of_War"),
 _t(36,"Uncharted","Sony Interactive Entertainment","Uncharted"),
 _t(37,"The Last of Us","Sony Interactive Entertainment","The_Last_of_Us"),
 _t(38,"Animal Crossing","Nintendo","Animal_Crossing"),
 _t(39,"Kirby","Nintendo","Kirby_(series)"),
 _t(40,"Metroid","Nintendo","Metroid"),
 _t(41,"Donkey Kong","Nintendo","Donkey_Kong"),
 _t(42,"Borderlands","2K","Borderlands"),
 _t(43,"Forza","Xbox Game Studios","Forza"),
 _t(44,"Gears of War","Xbox Game Studios","Gears_of_War"),
 _t(45,"FromSoftware (Dark Souls / Elden Ring)","Bandai Namco / FromSoftware","Dark_Souls"),
]
